import test from 'node:test';
import assert from 'node:assert/strict';
import { applyFsrsRating, plannedSkillsForCard, requiredSkillsForCard, unlockedSkillsForCard, getDueSkillItems } from '../src/fsrs-scheduler.js';
import { checkAnswer, sanitizeCardInput } from '../src/learning.js';
import { summarizeCalibration } from '../src/progress.js';

const reviewed=(reps=1)=>({due:Date.now(),stability:3,difficulty:5,elapsed_days:1,scheduled_days:1,learning_steps:0,reps,lapses:0,state:2,last_review:Date.now()});
test('active word keeps the full goal while unlocking skills progressively',()=>{const base=sanitizeCardInput({front:'retain',back:'ghi nhớ',learningGoal:'active',status:'learning'});assert.deepEqual(plannedSkillsForCard(base),['recognition','recall','listening','production']);assert.deepEqual(requiredSkillsForCard(base),plannedSkillsForCard(base));assert.deepEqual(unlockedSkillsForCard(base),['recognition','recall']);const foundation={...base,fsrsBySkill:{recognition:reviewed(),recall:reviewed()}};assert.deepEqual(unlockedSkillsForCard(foundation),['recognition','recall','listening']);const heard={...foundation,fsrsBySkill:{...foundation.fsrsBySkill,listening:reviewed()}};assert.deepEqual(unlockedSkillsForCard(heard),['recognition','recall','listening','production']);assert.equal(getDueSkillItems([base]).some(item=>item.skill==='production'),false);});
test('aggregate scheduling never selects a locked skill',()=>{const now=1_700_000_000_000;const base=sanitizeCardInput({front:'retain',back:'ghi nhớ',learningGoal:'active',status:'learning',createdAt:now});const recognition=applyFsrsRating(base,'good',now,undefined,'recognition').card;assert.equal(recognition.nextSkill,'recall');const recall=applyFsrsRating(recognition,'good',now+1_000,undefined,'recall').card;assert.equal(recall.nextSkill,'listening');assert.equal(recall.skillCoverage,.5);const custom=sanitizeCardInput({front:'deploy',back:'triển khai',targetSkills:['production'],status:'learning'});assert.deepEqual(unlockedSkillsForCard(custom),['production']);});
test('collocation production waits for foundation, collocation and listening',()=>{const card=sanitizeCardInput({front:'take into account',back:'cân nhắc',type:'collocation',learningGoal:'active',status:'learning',fsrsBySkill:{recognition:reviewed(),recall:reviewed()}});assert.deepEqual(requiredSkillsForCard(card),['recognition','recall','collocation','listening','production']);assert.deepEqual(unlockedSkillsForCard(card),['recognition','recall','collocation']);});
test('accepted answer is scoped to exercise direction',()=>{const card=sanitizeCardInput({front:'bank',back:'bờ sông',acceptedByExercise:{choice:['river bank'],typing:['bank']}});assert.equal(checkAnswer(card,{kind:'choice',skill:'recognition',answer:'bank'},'river bank').correct,true);assert.equal(checkAnswer(card,{kind:'meaning-choice',skill:'recognition',answer:'bờ sông'},'river bank').correct,false);assert.equal(checkAnswer(card,{kind:'typing',skill:'recall',answer:'bank'},'river bank').correct,false);});
test('storage timestamps survive card sanitization',()=>{const card=sanitizeCardInput({front:'durable',back:'bền',storageUpdatedAt:123,storageBaseUpdatedAt:100});assert.equal(card.storageUpdatedAt,123);assert.equal(card.storageBaseUpdatedAt,100);});
test('calibration reports predicted vs observed recall',()=>{const result=summarizeCalibration([{rating:'good',metadata:{predictedRetrievability:.8}},{rating:'again',metadata:{predictedRetrievability:.6}}]);assert.equal(result.sampleSize,2);assert.equal(result.predicted,70);assert.equal(result.observed,50);});
