import test from 'node:test';
import assert from 'node:assert/strict';
import { IDBFactory } from 'fake-indexeddb';
import { createPrivateSourceAdapter,createPrivateSourceLibrary } from '../src/private-source-library.js';
import { createSourceRevisionRegistry } from '../src/source-revision-ref.js';
import { normalizePrivateSourceInput,validatePrivateSourceStore,PRIVATE_SOURCE_MAX_BYTES,createPrivateSourceRef } from '../src/private-source-contracts.js';
import { getV10Record,putV10Record,reopenV10Database } from '../src/v10-persistence.js';
import { V10_STORES } from '../src/v10-contracts.js';

test.beforeEach(async()=>{globalThis.indexedDB=new IDBFactory();await reopenV10Database();});

test('private source owner creates a draft revision', async () => {
  const library = createPrivateSourceLibrary();
  const result = await library.create({
    sourceId: 'private-source:00000000-0000-4000-8000-000000000010',
    title: 'Private source',
    text: 'A local-only private body.',
    createdAt: 1
  });
  assert.equal(result.state, 'draft');
});

test('replay, edit, approval, search and delete preserve private lifecycle',async()=>{const library=createPrivateSourceLibrary(),sourceId='private-source:00000000-0000-4000-8000-000000000011';const first=await library.create({sourceId,title:'Café',text:'Xin chào world',createdAt:10});assert.equal((await library.create({sourceId,title:'Café',text:'Xin chào world',createdAt:11})).currentRevisionId,first.currentRevisionId);const second=await library.edit({sourceId,title:'Café 2',text:'Edited body',expectedRevisionId:first.currentRevisionId,updatedAt:12});await assert.rejects(()=>library.approve({sourceId,expectedRevisionId:first.currentRevisionId,approvedAt:13}),e=>e.code==='STALE_REVISION');await library.approve({sourceId,expectedRevisionId:second.currentRevisionId,approvedAt:13});assert.equal((await library.search('cafe')).length,1);const tomb=await library.delete({sourceId,expectedRevisionId:second.currentRevisionId,deletedAt:14});assert.equal(tomb.kind,'private-source-tombstone');assert.equal((await library.search('edited')).length,0);});
test('strict text normalization rejects unsafe content',()=>{const sourceId='private-source:00000000-0000-4000-8000-000000000014';assert.equal(normalizePrivateSourceInput({sourceId,title:' A\n B ',text:'a\r\nb',createdAt:1}).text,'a\nb');for(const text of ['   ','a\0b','a\u0001b'])assert.throws(()=>normalizePrivateSourceInput({sourceId,title:'x',text,createdAt:1}));});
test('one-over byte limit is denied before storage',()=>assert.throws(()=>normalizePrivateSourceInput({sourceId:'x',title:'x',text:'a'.repeat(PRIVATE_SOURCE_MAX_BYTES+1),createdAt:1}),e=>e.code==='QUOTA_EXCEEDED'));
test('corrupt store fails closed',()=>assert.throws(()=>validatePrivateSourceStore([{kind:'private-source-head',id:'x',sourceId:'x',currentRevisionId:'missing',revisionCount:1,state:'draft',currentApprovalId:null,createdAt:1,updatedAt:1}]),e=>e.code==='CORRUPT_OWNER'));
test('title is required',()=>assert.throws(()=>normalizePrivateSourceInput({sourceId:'x',title:'',text:'body',createdAt:1})));
test('title has a 200-code-unit ceiling',()=>assert.throws(()=>normalizePrivateSourceInput({sourceId:'x',title:'x'.repeat(201),text:'body',createdAt:1})));
test('timestamps are safe integers',()=>assert.throws(()=>normalizePrivateSourceInput({sourceId:'x',title:'x',text:'body',createdAt:-1})));
test('unknown input fields fail closed',()=>assert.throws(()=>normalizePrivateSourceInput({sourceId:'x',title:'x',text:'body',createdAt:1,verified:true})));
test('source references are private and unverified',async()=>{const item=await createPrivateSourceLibrary().create({sourceId:'private-source:00000000-0000-4000-8000-000000000012',title:'x',text:'body',createdAt:2});assert.deepEqual(item.sourceRevisionRef.provenance,{origin:'private-user-paste',verification:'unverified',rights:'unknown',privacy:'private'});});
test('delete replay is idempotent',async()=>{const library=createPrivateSourceLibrary(),sourceId='private-source:00000000-0000-4000-8000-000000000013',item=await library.create({sourceId,title:'x',text:'body',createdAt:3});const first=await library.delete({sourceId,expectedRevisionId:item.currentRevisionId,deletedAt:4}),again=await library.delete({sourceId,expectedRevisionId:item.currentRevisionId,deletedAt:5});assert.deepEqual(again,first);});
test('R1 F1 rejects contentful tombstones and F2 rejects forged lineage',()=>{assert.throws(()=>validatePrivateSourceStore([{kind:'private-source-tombstone',id:'private-source:00000000-0000-4000-8000-000000000001',sourceId:'private-source:00000000-0000-4000-8000-000000000001',lastRevisionId:'x',lastTextDigest:'sha256:x',deletedAt:1,reason:'user-delete',nested:{text:'leak'}}]),e=>e.code==='CORRUPT_OWNER');});
test('R1 F3 owner operations reject accessors before invocation',async()=>{const library=createPrivateSourceLibrary();let invoked=false;const input={};Object.defineProperty(input,'sourceId',{enumerable:true,get(){invoked=true;return 'private-source:00000000-0000-4000-8000-000000000002';}});await assert.rejects(()=>library.approve(input),e=>e.code==='INVALID_INPUT');assert.equal(invoked,false);});
test('R1 F4 requires a UUID-v4 private source identity',()=>assert.throws(()=>normalizePrivateSourceInput({sourceId:'private-source:s:revision:1',title:'x',text:'body',createdAt:1}),e=>e.code==='INVALID_INPUT'));
test('R1 persistence preserves private source exact fields without generic updatedAt',async()=>{const sourceId='private-source:00000000-0000-4000-8000-000000000015',row={kind:'private-source-tombstone',id:sourceId,sourceId,lastRevisionId:`${sourceId}:revision:1`,lastTextDigest:'sha256:abc',deletedAt:1,reason:'user-delete'};await putV10Record(V10_STORES.privateSources,row);assert.deepEqual(await getV10Record(V10_STORES.privateSources,sourceId),row);});
test('R1 private source adapter returns non-executable provenance-invalid owner metadata',async()=>{const library=createPrivateSourceLibrary(),sourceId='private-source:00000000-0000-4000-8000-000000000016',item=await library.create({sourceId,title:'x',text:'body',createdAt:1}),registry=createSourceRevisionRegistry({adapters:[createPrivateSourceAdapter()]}),result=await registry.resolve(item.sourceRevisionRef);assert.equal(result.code,'PROVENANCE_INVALID');assert.equal(result.executable,false);assert.equal(Object.hasOwn(result.record,'text'),false);});
test('R1 F5 preview/edit surface is present in the existing Library markup',async()=>{const html=await (await import('node:fs/promises')).readFile(new URL('../index.html',import.meta.url),'utf8');assert.match(html,/data-private-source-preview/);assert.match(html,/Xem trước/);assert.match(html,/data-private-source-preview-output/);});
test('R1 legacy v4 gap remains reject-before-upgrade until exact historical adapter is proven',async()=>{const registry=await import('../src/backup-registry.js');const result=registry.validateFullBackupEnvelope({schemaVersion:4,registryVersion:4,kind:'vocab-master-full'});assert.equal(result.valid,false);});
const distinctInputMutations=[
  ['unknown field',{extra:true}],['symbol key',Object.assign({[Symbol('x')]:true},{})],['undefined title',{title:undefined}],['nonfinite timestamp',{createdAt:Infinity}],['negative timestamp',{createdAt:-1}],['array input',[]],['exotic prototype',Object.assign(Object.create({}),{sourceId:'private-source:00000000-0000-4000-8000-000000000100',title:'x',text:'body',createdAt:1})],['uppercase UUID',{sourceId:'private-source:00000000-0000-4000-8000-00000000010A'}],['wrong UUID version',{sourceId:'private-source:00000000-0000-3000-8000-000000000101'}],['wrong UUID variant',{sourceId:'private-source:00000000-0000-4000-7000-000000000102'}],['newline title',{title:'\n'}],['long title',{title:'x'.repeat(201)}],['empty text',{text:'   '}],['NUL text',{text:'a\0b'}],['control text',{text:'a\u0001b'}],['overbyte text',{text:'a'.repeat(PRIVATE_SOURCE_MAX_BYTES+1)}]
];
for(const [dimension,patch] of distinctInputMutations)test(`R2 input rejects distinct ${dimension}`,()=>{const base={sourceId:'private-source:00000000-0000-4000-8000-000000000100',title:'x',text:'body',createdAt:1};const value=(dimension==='array input'||dimension==='exotic prototype')?patch:{...base,...patch};assert.throws(()=>normalizePrivateSourceInput(value));});
const malformedOwnerRows=[
  ['tombstone nested text',{kind:'private-source-tombstone',id:'private-source:00000000-0000-4000-8000-000000000110',sourceId:'private-source:00000000-0000-4000-8000-000000000110',lastRevisionId:'private-source:00000000-0000-4000-8000-000000000110:revision:1',lastTextDigest:'sha256:'+'0'.repeat(64),deletedAt:1,reason:'user-delete',text:'leak'}],
  ['tombstone negative time',{kind:'private-source-tombstone',id:'private-source:00000000-0000-4000-8000-000000000111',sourceId:'private-source:00000000-0000-4000-8000-000000000111',lastRevisionId:'private-source:00000000-0000-4000-8000-000000000111:revision:1',lastTextDigest:'sha256:'+'0'.repeat(64),deletedAt:-1,reason:'user-delete'}],
  ['tombstone bad revision id',{kind:'private-source-tombstone',id:'private-source:00000000-0000-4000-8000-000000000112',sourceId:'private-source:00000000-0000-4000-8000-000000000112',lastRevisionId:'wrong',lastTextDigest:'sha256:'+'0'.repeat(64),deletedAt:1,reason:'user-delete'}],
  ['tombstone bad digest',{kind:'private-source-tombstone',id:'private-source:00000000-0000-4000-8000-000000000113',sourceId:'private-source:00000000-0000-4000-8000-000000000113',lastRevisionId:'private-source:00000000-0000-4000-8000-000000000113:revision:1',lastTextDigest:'sha256:no',deletedAt:1,reason:'user-delete'}],
  ['tombstone bad reason',{kind:'private-source-tombstone',id:'private-source:00000000-0000-4000-8000-000000000114',sourceId:'private-source:00000000-0000-4000-8000-000000000114',lastRevisionId:'private-source:00000000-0000-4000-8000-000000000114:revision:1',lastTextDigest:'sha256:'+'0'.repeat(64),deletedAt:1,reason:'other'}]
];
for(const [dimension,row] of malformedOwnerRows)test(`R2 owner rejects distinct ${dimension}`,()=>assert.throws(()=>validatePrivateSourceStore([row]),error=>error.code==='CORRUPT_OWNER'));
test('R2 create rejects collision with different content',async()=>{const l=createPrivateSourceLibrary(),sourceId='private-source:00000000-0000-4000-8000-000000000120';await l.create({sourceId,title:'a',text:'a',createdAt:1});await assert.rejects(()=>l.create({sourceId,title:'b',text:'b',createdAt:2}),e=>e.code==='ID_COLLISION');});
test('R2 edit rejects stale revision',async()=>{const l=createPrivateSourceLibrary(),sourceId='private-source:00000000-0000-4000-8000-000000000121',a=await l.create({sourceId,title:'a',text:'a',createdAt:1});await l.edit({sourceId,title:'b',text:'b',expectedRevisionId:a.currentRevisionId,updatedAt:2});await assert.rejects(()=>l.edit({sourceId,title:'c',text:'c',expectedRevisionId:a.currentRevisionId,updatedAt:3}),e=>e.code==='STALE_REVISION');});
test('R2 approve rejects time before revision',async()=>{const l=createPrivateSourceLibrary(),sourceId='private-source:00000000-0000-4000-8000-000000000122',a=await l.create({sourceId,title:'a',text:'a',createdAt:2});await assert.rejects(()=>l.approve({sourceId,expectedRevisionId:a.currentRevisionId,approvedAt:1}));});
test('R2 quarantine fences accessor before read',async()=>{const l=createPrivateSourceLibrary();let invoked=false;const input={};Object.defineProperty(input,'sourceId',{enumerable:true,get(){invoked=true;return 'x';}});await assert.rejects(()=>l.quarantine(input));assert.equal(invoked,false);});
test('R2 delete rejects mismatched tombstone replay',async()=>{const l=createPrivateSourceLibrary(),sourceId='private-source:00000000-0000-4000-8000-000000000123',a=await l.create({sourceId,title:'a',text:'a',createdAt:1});await l.delete({sourceId,expectedRevisionId:a.currentRevisionId,deletedAt:2});await assert.rejects(()=>l.delete({sourceId,expectedRevisionId:'other',deletedAt:3}),e=>e.code==='STALE_REVISION');});
test('R2 search returns frozen projection',async()=>{const l=createPrivateSourceLibrary(),sourceId='private-source:00000000-0000-4000-8000-000000000124';await l.create({sourceId,title:'a',text:'a',createdAt:1});assert.equal(Object.isFrozen((await l.search())[0]),true);});
test('R2 search excludes tombstone',async()=>{const l=createPrivateSourceLibrary(),sourceId='private-source:00000000-0000-4000-8000-000000000125',a=await l.create({sourceId,title:'a',text:'body',createdAt:1});await l.delete({sourceId,expectedRevisionId:a.currentRevisionId,deletedAt:2});assert.equal((await l.search('body')).length,0);});
test('R2 adapter wrong digest is typed integrity mismatch',async()=>{const l=createPrivateSourceLibrary(),sourceId='private-source:00000000-0000-4000-8000-000000000126',a=await l.create({sourceId,title:'a',text:'body',createdAt:1}),registry=createSourceRevisionRegistry({adapters:[createPrivateSourceAdapter()]}),result=await registry.resolve({...a.sourceRevisionRef,integrity:'sha256:'+'0'.repeat(64)});assert.equal(result.code,'INTEGRITY_MISMATCH');});
test('R2 adapter missing source is typed not found',async()=>{const registry=createSourceRevisionRegistry({adapters:[createPrivateSourceAdapter()]}),result=await registry.resolve({schema:'SourceRevisionRef',version:1,kind:'private-text-source',authority:'private-source-library',sourceId:'private-source:00000000-0000-4000-8000-000000000127',revisionId:'private-source:00000000-0000-4000-8000-000000000127:revision:1',integrity:'sha256:'+'0'.repeat(64),locator:{sourceId:'private-source:00000000-0000-4000-8000-000000000127',revisionId:'private-source:00000000-0000-4000-8000-000000000127:revision:1',textDigest:'sha256:'+'0'.repeat(64)}});assert.equal(result.code,'NOT_FOUND');});
test('R2 direct private adapter rejects reference accessors before invocation',async()=>{const reference={};let invoked=false;Object.defineProperty(reference,'sourceId',{enumerable:true,get(){invoked=true;throw new Error('must not read');}});const result=await createPrivateSourceAdapter().resolve(reference);assert.equal(result.code,'INTEGRITY_MISMATCH');assert.equal(invoked,false);});
test('R2 CRLF normalizes to LF distinct from source body',()=>assert.equal(normalizePrivateSourceInput({sourceId:'private-source:00000000-0000-4000-8000-000000000128',title:'a',text:'a\r\nb',createdAt:1}).text,'a\nb'));
test('R2 per-revision ASCII exact boundary and one-over are distinct quota outcomes',()=>{const sourceId='private-source:00000000-0000-4000-8000-000000000129';assert.equal(normalizePrivateSourceInput({sourceId,title:'a',text:'a'.repeat(PRIVATE_SOURCE_MAX_BYTES),createdAt:1}).utf8Bytes,PRIVATE_SOURCE_MAX_BYTES);assert.throws(()=>normalizePrivateSourceInput({sourceId,title:'a',text:'a'.repeat(PRIVATE_SOURCE_MAX_BYTES+1),createdAt:1}),e=>e.code==='QUOTA_EXCEEDED');});
test('R2 per-revision multibyte boundary is measured in UTF-8 bytes',()=>{const sourceId='private-source:00000000-0000-4000-8000-000000000130',body='é'.repeat(PRIVATE_SOURCE_MAX_BYTES/2);assert.equal(normalizePrivateSourceInput({sourceId,title:'a',text:body,createdAt:1}).utf8Bytes,PRIVATE_SOURCE_MAX_BYTES);assert.throws(()=>normalizePrivateSourceInput({sourceId,title:'a',text:body+'é',createdAt:1}),e=>e.code==='QUOTA_EXCEEDED');});
test('R2 live source limit accepts 100 then rejects the distinct 101st owner',async()=>{const l=createPrivateSourceLibrary();for(let n=0;n<100;n++){const sourceId=`private-source:00000000-0000-4000-8000-${String(200+n).padStart(12,'0')}`;await l.create({sourceId,title:'a',text:'a',createdAt:n});}await assert.rejects(()=>l.create({sourceId:'private-source:00000000-0000-4000-8000-000000000301',title:'a',text:'a',createdAt:101}),e=>e.code==='SOURCE_LIMIT');});
test('R2 validator accepts exact 16MiB retained bytes and rejects 16MiB plus one revision',async()=>{const {createPrivateSourceRef}=await import('../src/private-source-contracts.js'),sourceId='private-source:00000000-0000-4000-8000-000000000302',body='a'.repeat(PRIVATE_SOURCE_MAX_BYTES),make=n=>{const id=`${sourceId}:revision:${n}`,row={kind:'private-source-revision',id,sourceId,revisionNumber:n,parentRevisionId:n===1?null:`${sourceId}:revision:${n-1}`,title:'a',text:body,textDigest:(normalizePrivateSourceInput({sourceId,title:'a',text:body,createdAt:1}).textDigest),utf8Bytes:PRIVATE_SOURCE_MAX_BYTES,sourceRevisionRef:null,createdAt:n};row.sourceRevisionRef=createPrivateSourceRef(row);return row;},exact=Array.from({length:64},(_,i)=>make(i+1)),head={kind:'private-source-head',id:sourceId,sourceId,currentRevisionId:`${sourceId}:revision:64`,revisionCount:64,state:'draft',currentApprovalId:null,createdAt:1,updatedAt:64};assert.equal(validatePrivateSourceStore([head,...exact]),true);const plus=[...exact,make(65),{...head,currentRevisionId:`${sourceId}:revision:65`,revisionCount:65,updatedAt:65}];assert.throws(()=>validatePrivateSourceStore(plus),e=>e.code==='QUOTA_EXCEEDED');});
test('R2 record ceiling rejects 10001 rows before duplicate or semantic processing',()=>assert.throws(()=>validatePrivateSourceStore(Array.from({length:10001},()=>({}))),e=>e.code==='RECORD_LIMIT'));
test('R2 create/edit/approval replays suppress V10 change broadcasts while stale errors write nothing',async()=>{const originalDispatch=globalThis.dispatchEvent;let broadcasts=0;globalThis.dispatchEvent=event=>{if(event?.type==='vocab:v10-data-saved')broadcasts++;return true;};try{const library=createPrivateSourceLibrary(),sourceId='private-source:00000000-0000-4000-8000-000000000303',first=await library.create({sourceId,title:'a',text:'body',createdAt:1}),afterCreate=broadcasts;await library.create({sourceId,title:'a',text:'body',createdAt:2});assert.equal(broadcasts,afterCreate);await library.edit({sourceId,title:'a',text:'body',expectedRevisionId:first.currentRevisionId,updatedAt:3});assert.equal(broadcasts,afterCreate);await assert.rejects(()=>library.edit({sourceId,title:'b',text:'b',expectedRevisionId:'stale',updatedAt:4}),error=>error.code==='STALE_REVISION');assert.equal(broadcasts,afterCreate);await library.approve({sourceId,expectedRevisionId:first.currentRevisionId,approvedAt:5});const afterApproval=broadcasts;await library.approve({sourceId,expectedRevisionId:first.currentRevisionId,approvedAt:6});assert.equal(broadcasts,afterApproval);}finally{globalThis.dispatchEvent=originalDispatch;}});
test('R3 natural RED: backdated mutations, exact transitions and get options accessors fail closed',async()=>{const library=createPrivateSourceLibrary(),sourceId='private-source:00000000-0000-4000-8000-000000000304',first=await library.create({sourceId,title:'r3',text:'one',createdAt:10});await assert.rejects(()=>library.edit({sourceId,title:'r3',text:'two',expectedRevisionId:first.currentRevisionId,updatedAt:9}),error=>error.code==='INVALID_INPUT');const current=await library.getById(sourceId);await library.approve({sourceId,expectedRevisionId:current.currentRevisionId,approvedAt:11});await assert.rejects(()=>library.quarantine({sourceId,expectedRevisionId:current.currentRevisionId,code:'policy-warning',createdAt:10}),error=>error.code==='INVALID_INPUT');let invoked=false;const options={};Object.defineProperty(options,'revisionId',{enumerable:true,get(){invoked=true;throw new Error('must not read');}});await assert.rejects(()=>library.getById(sourceId,options),error=>error.code==='INVALID_INPUT');assert.equal(invoked,false);});
test('R3 natural RED: private adapter authenticates exact headers before tombstone disclosure',async()=>{const library=createPrivateSourceLibrary(),sourceId='private-source:00000000-0000-4000-8000-000000000305',first=await library.create({sourceId,title:'r3-adapter',text:'body',createdAt:1});await library.delete({sourceId,expectedRevisionId:first.currentRevisionId,deletedAt:2});const result=await createPrivateSourceAdapter().resolve({kind:'wrong-owner',sourceId,revisionId:first.currentRevisionId,integrity:first.sourceRevisionRef.integrity,locator:first.sourceRevisionRef.locator});assert.equal(result.code,'INTEGRITY_MISMATCH');});
test('R3 validator rejects an otherwise valid extra revision outside the head count',async()=>{const sourceId='private-source:00000000-0000-4000-8000-000000000306',library=createPrivateSourceLibrary(),first=await library.create({sourceId,title:'r3-extra',text:'one',createdAt:1}),second=await library.edit({sourceId,title:'r3-extra',text:'two',expectedRevisionId:first.currentRevisionId,updatedAt:2}),rows=await (await import('../src/v10-persistence.js')).listV10Records(V10_STORES.privateSources,{sortBy:null}),last=rows.find(row=>row.id===second.currentRevisionId),extra={...structuredClone(last),id:`${sourceId}:revision:3`,revisionNumber:3,parentRevisionId:second.currentRevisionId,createdAt:3,sourceRevisionRef:null};extra.sourceRevisionRef=(await import('../src/private-source-contracts.js')).createPrivateSourceRef(extra);assert.throws(()=>validatePrivateSourceStore([...rows,extra]),error=>error.code==='CORRUPT_OWNER');});
test('R3 validator classifies 101 heads as source limit before per-head linkage',()=>{const rows=Array.from({length:101},(_,n)=>{const sourceId=`private-source:00000000-0000-4000-8000-${String(400+n).padStart(12,'0')}`;return{kind:'private-source-head',id:sourceId,sourceId,currentRevisionId:`${sourceId}:revision:1`,revisionCount:1,state:'draft',currentApprovalId:null,createdAt:1,updatedAt:1};});assert.throws(()=>validatePrivateSourceStore(rows),error=>error.code==='SOURCE_LIMIT');});
test('R3 approval and quarantine reject stale terminal replays without owner mutation',async()=>{const library=createPrivateSourceLibrary(),sourceId='private-source:00000000-0000-4000-8000-000000000307',first=await library.create({sourceId,title:'r3-replay',text:'body',createdAt:10});await library.approve({sourceId,expectedRevisionId:first.currentRevisionId,approvedAt:11});await library.quarantine({sourceId,expectedRevisionId:first.currentRevisionId,code:'policy-warning',createdAt:12});await assert.rejects(()=>library.approve({sourceId,expectedRevisionId:first.currentRevisionId,approvedAt:13}),error=>error.code==='INVALID_TRANSITION');const before=JSON.stringify(await (await import('../src/v10-persistence.js')).listV10Records(V10_STORES.privateSources,{sortBy:null}));await assert.rejects(()=>library.quarantine({sourceId,expectedRevisionId:first.currentRevisionId,code:'policy-warning',createdAt:11}),error=>error.code==='INVALID_INPUT');assert.equal(JSON.stringify(await (await import('../src/v10-persistence.js')).listV10Records(V10_STORES.privateSources,{sortBy:null})),before);});
test('R3 delete rejects backdated time before any durable mutation',async()=>{const library=createPrivateSourceLibrary(),sourceId='private-source:00000000-0000-4000-8000-000000000308',first=await library.create({sourceId,title:'r3-delete',text:'body',createdAt:10}),before=JSON.stringify(await (await import('../src/v10-persistence.js')).listV10Records(V10_STORES.privateSources,{sortBy:null}));await assert.rejects(()=>library.delete({sourceId,expectedRevisionId:first.currentRevisionId,deletedAt:9}),error=>error.code==='INVALID_INPUT');assert.equal(JSON.stringify(await (await import('../src/v10-persistence.js')).listV10Records(V10_STORES.privateSources,{sortBy:null})),before);});
test('R3 tombstone adapter authenticates last revision and digest before disclosure',async()=>{const library=createPrivateSourceLibrary(),sourceId='private-source:00000000-0000-4000-8000-000000000309',first=await library.create({sourceId,title:'r3-tomb',text:'body',createdAt:1});await library.delete({sourceId,expectedRevisionId:first.currentRevisionId,deletedAt:2});const adapter=createPrivateSourceAdapter(),wrongRevision=await adapter.resolve({...first.sourceRevisionRef,revisionId:`${sourceId}:revision:2`,locator:{...first.sourceRevisionRef.locator,revisionId:`${sourceId}:revision:2`}}),wrongDigest=await adapter.resolve({...first.sourceRevisionRef,integrity:'sha256:'+'0'.repeat(64),locator:{...first.sourceRevisionRef.locator,textDigest:'sha256:'+'0'.repeat(64)}}),exact=await adapter.resolve(first.sourceRevisionRef);assert.equal(wrongRevision.code,'INTEGRITY_MISMATCH');assert.equal(wrongDigest.code,'INTEGRITY_MISMATCH');assert.equal(exact.code,'TOMBSTONED');});
test('R3 references with nonempty display, extensions or altered provenance never reach owner state',async()=>{const library=createPrivateSourceLibrary(),sourceId='private-source:00000000-0000-4000-8000-000000000310',first=await library.create({sourceId,title:'r3-ref',text:'body',createdAt:1}),adapter=createPrivateSourceAdapter();assert.equal((await adapter.resolve({...first.sourceRevisionRef,display:{label:'leak'}})).code,'INTEGRITY_MISMATCH');assert.equal((await adapter.resolve({...first.sourceRevisionRef,extensions:{tag:'no'}})).code,'INTEGRITY_MISMATCH');for(const provenance of [{...first.sourceRevisionRef.provenance,verification:'verified'},{...first.sourceRevisionRef.provenance,rights:'allowed'},{...first.sourceRevisionRef.provenance,privacy:'public'},{...first.sourceRevisionRef.provenance,origin:null}])assert.equal((await adapter.resolve({...first.sourceRevisionRef,provenance})).code,'INTEGRITY_MISMATCH');});
const r3FenceReference=createPrivateSourceRef({sourceId:'private-source:00000000-0000-4000-8000-000000000311',id:'private-source:00000000-0000-4000-8000-000000000311:revision:1',textDigest:'sha256:'+'1'.repeat(64)});
const r3ReferenceFenceMutations=[
  ['wrong schema',value=>({...value,schema:'Other'} )],['zero version',value=>({...value,version:0})],['future version',value=>({...value,version:2})],['fractional version',value=>({...value,version:1.5})],['wrong kind',value=>({...value,kind:'transcript'})],['wrong authority',value=>({...value,authority:'other-owner'})],['missing authority',value=>{const next={...value};delete next.authority;return next;}],['missing source identity',value=>{const next={...value};delete next.sourceId;return next;}],['active source identity',value=>({...value,sourceId:'active',locator:{...value.locator,sourceId:'active'}})],['active revision identity',value=>({...value,revisionId:'latest',locator:{...value.locator,revisionId:'latest'}})],['missing integrity',value=>{const next={...value};delete next.integrity;return next;}],['mismatched locator source',value=>({...value,locator:{...value.locator,sourceId:'other'}})],['mismatched locator revision',value=>({...value,locator:{...value.locator,revisionId:'other'}})],['mismatched locator digest',value=>({...value,locator:{...value.locator,textDigest:'sha256:'+'2'.repeat(64)}})],['missing locator source',value=>{const next={...value,locator:{...value.locator}};delete next.locator.sourceId;return next;}],['missing locator revision',value=>{const next={...value,locator:{...value.locator}};delete next.locator.revisionId;return next;}],['missing locator digest',value=>{const next={...value,locator:{...value.locator}};delete next.locator.textDigest;return next;}],['extra locator field',value=>({...value,locator:{...value.locator,extra:true}})],['null locator',value=>({...value,locator:null})],['verified provenance',value=>({...value,provenance:{...value.provenance,verification:'verified'}})],['allowed provenance rights',value=>({...value,provenance:{...value.provenance,rights:'allowed'}})],['public provenance privacy',value=>({...value,provenance:{...value.provenance,privacy:'public'}})],['missing provenance origin',value=>({...value,provenance:{...value.provenance,origin:null}})],['tombstone envelope',value=>({...value,tombstone:true})],['display title',value=>({...value,display:{title:'private'}})],['display label',value=>({...value,display:{label:'private'}})],['extension field',value=>({...value,extensions:{purpose:'private'}})],['unknown current field',value=>({...value,unknown:true})],['symbol key',value=>Object.assign({...value},{[Symbol('private')]:true})],['sparse locator array',value=>({...value,locator:Object.assign([], {0:'x',length:2})})],['locator accessor',value=>{const locator={};Object.defineProperty(locator,'sourceId',{enumerable:true,get(){throw new Error('must not read');}});return{...value,locator};}],['reference accessor',value=>{const next={...value};Object.defineProperty(next,'sourceId',{enumerable:true,get(){throw new Error('must not read');}});return next;}],['nonplain reference',value=>Object.assign(Object.create(null),value)],['nonfinite extension',value=>({...value,extensions:{safe:Infinity}})]
];
for(const [dimension,mutate] of r3ReferenceFenceMutations)test(`R3 exact private adapter fence rejects ${dimension} before owner disclosure`,async()=>{const result=await createPrivateSourceAdapter().resolve(mutate(structuredClone(r3FenceReference)));assert.equal(result.code,'INTEGRITY_MISMATCH');});
