import assert from 'node:assert/strict';
import test from 'node:test';
import { readFile } from 'node:fs/promises';
import { indexedDB,IDBKeyRange } from 'fake-indexeddb';
globalThis.indexedDB=indexedDB;globalThis.IDBKeyRange=IDBKeyRange;globalThis.dispatchEvent=()=>true;globalThis.CustomEvent??=class CustomEvent{constructor(type,{detail}={}){this.detail=detail;}};
import { createIeltsReadingSourceRevision,IELTS_STORE_NAMES } from '../src/ielts-domain.js';
import { createIeltsObjectiveInventoryItem,deriveIeltsObjectiveInventoryId } from '../src/ielts-profile-inventory.js';
import { createIeltsReadingObjectiveTextOwnerAdapter,createDurableIeltsReadingObjectiveTextOwnerAdapter,adaptIeltsReadingObjectiveTextItem,createIeltsReadingSourceAdapter } from '../src/ielts-reading-question-activity.js';
import { createObjectiveTextResponseOwnerAdapter,createObjectiveTextResponseQuestion,createQuestionRegistry,executeQuestionActivity,READING_ASSISTANCE_COLLECTION_MODE } from '../src/question-activity-contracts.js';
import { scoreObjectiveTextResponse } from '../src/objective-text-response.js';
import { composeTodayPlan } from '../src/today-composer.js';
import { createSourceRevisionRegistry } from '../src/source-revision-ref.js';
import { V10_STORES } from '../src/v10-contracts.js';
import { getV10Record,putV10Record,deleteV10Record,reopenV10Database } from '../src/v10-persistence.js';
import { buildCombinedBackup,restoreCombinedBackup,validateCombinedBackup } from '../src/ielts-backup.js';
import { canonicalBackupDigest,sha256Hex } from '../src/backup-registry.js';
import * as persistence from '../src/ielts-persistence.js';

const fixture=JSON.parse(await readFile(new URL('./fixtures/wave4-reading-spatial-fixture.json',import.meta.url),'utf8'));
function recomputeBackupIntegrity(envelope){for(const entry of envelope.manifest.stores){if(entry.backupRule==='exclude')continue;const rows=envelope.domains[entry.owner].stores[entry.store];entry.recordCount=rows.length;entry.contentDigest=`sha256:${sha256Hex(JSON.stringify(rows))}`;}envelope.payloadDigest=canonicalBackupDigest(envelope.domains);return envelope;}
const approval=(kind,digest)=>kind==='rights'?{schemaVersion:2,id:'spatial-reading-rights',status:'approved',licenseId:'project-created-local',rightsHolder:'VocabMaster project',basis:'project-created',assertedAt:'2026-08-11T00:00:00.000Z',expiresAt:null,aiAsserted:false}:kind==='provenance'?{schemaVersion:2,id:'spatial-reading-provenance',sourceType:'original-human-authored',sourceDescription:'CONTROLLED_LOCAL_TEST_ONLY project fixture',authorOrOrigin:'VocabMaster project',createdAt:'2026-08-11T00:00:00.000Z',aiDraft:false}:{schemaVersion:2,id:'spatial-reading-review',status:'approved',reviewerType:'human',reviewerId:'controlled-reviewer',reviewedAt:'2026-08-11T00:01:00.000Z',scopeDigest:digest,checks:['rights','pedagogy','accuracy'],selfApprovedByAi:false};
function readingSource(id,items=[]){return createIeltsReadingSourceRevision({id,revision:1,profile:'academic',title:'Controlled spatial Reading source',passage:'A project-created local passage supplies the controlled diagram context.',objectiveItems:items,status:'verified',createdAt:1,updatedAt:1});}
function activity(question,id){const plan=composeTodayPlan({content:[{id,type:'reading',target:question.item.target,executor:'objective-text-response',estimatedSeconds:60}],now:120_000,minutes:5});return {...plan.activities[0],execution:{kind:'objective-text-response',status:'ready'},assistanceCollectionMode:READING_ASSISTANCE_COLLECTION_MODE,launchBinding:`${id}:spatial-reading`,launch:{promptRevision:question.promptRevision,configRevision:question.registryRevision,configDigest:question.promptDigest},evaluationBinding:{applicable:true,revision:question.registryRevision,keyRevision:question.keyRevision,keyDigest:question.keyDigest,rubricRevision:question.rubricRevision,rubricDigest:question.rubricDigest,scoringPolicyRevision:question.scorer.id,reviewPolicyRevision:question.reviewPolicyRevision}};}
function payloadFor(source,id){return{id,kind:fixture.definition.kind,prompt:fixture.definition.prompt,slots:[{id:'one',label:'First label',wordLimit:1,acceptedAnswers:['north']},{id:'two',label:'Second label',wordLimit:1,acceptedAnswers:['south']}],spatialPrompt:structuredClone(fixture.definition.spatialPrompt),target:{schemaVersion:2,targetType:'ielts-objective-item',targetId:id,cardId:null,senseId:null,skill:'reading',sourceId:source.sourceRevisionRef.sourceId,sourceRevision:source.sourceRevisionRef.revisionId},sourceRevisionRef:source.sourceRevisionRef,createdAt:1,updatedAt:1};}
function binding(question){return{kind:question.kind,schemaVersion:question.version,registryRevision:question.registryRevision,questionId:question.id,promptRevision:question.promptRevision,promptDigest:question.promptDigest,keyRevision:question.keyRevision,keyDigest:question.keyDigest,rubricRevision:question.rubricRevision,rubricDigest:question.rubricDigest,scorer:question.scorer,reviewPolicyRevision:question.reviewPolicyRevision,requiredCapabilities:question.requiredCapabilities};}
async function durableSpatialHarness(id){
  const sourceId=`wave4-spatial-reading-${id}`,provisional=readingSource(sourceId),inventoryId=deriveIeltsObjectiveInventoryId({skill:'reading',profiles:['academic'],form:{id:'wave4-spatial-reading-form',revision:1},section:{id:'wave4-spatial-reading-section',revision:1,number:1},order:1,itemId:`${id}-item`,itemRevision:1}),sealed=readingSource(sourceId,[{inventoryId,kind:fixture.definition.kind,schemaVersion:1}]),payload=payloadFor(sealed,inventoryId),seed=createObjectiveTextResponseQuestion(payload,{ownerAdapter:createObjectiveTextResponseOwnerAdapter({readVerifiedQuestion:()=>payload})}),draft=createIeltsObjectiveInventoryItem({kind:'ielts-objective-inventory-item',schemaVersion:1,itemId:`${id}-item`,itemRevision:1,skill:'reading',profiles:['academic'],form:{id:'wave4-spatial-reading-form',revision:1},section:{id:'wave4-spatial-reading-section',revision:1,number:1},order:1,sourceRevisionRef:sealed.sourceRevisionRef,questionBinding:binding(seed),questionPayload:payload,status:'draft',createdAt:'2026-08-11T00:00:00.000Z',verifiedAt:null,retiredAt:null,retirementReason:null,rights:null,provenance:null,humanReview:null,extensions:{fixture:'CONTROLLED_LOCAL_TEST_ONLY'}}),verified=createIeltsObjectiveInventoryItem({...draft,status:'verified',verifiedAt:'2026-08-11T00:01:00.000Z',rights:approval('rights',draft.contentDigest),provenance:approval('provenance',draft.contentDigest),humanReview:approval('review',draft.contentDigest)}),promotionOwner=createIeltsReadingObjectiveTextOwnerAdapter({readVerifiedInventory:async value=>value===verified.id?verified:null,readVerifiedSource:async value=>value.revisionId===sealed.sourceRevisionRef.revisionId?sealed:null}),promotionQuestion=await adaptIeltsReadingObjectiveTextItem(verified,sealed.sourceRevisionRef,{ownerAdapter:promotionOwner});
  await persistence.initializeIeltsPersistence();await persistence.saveIeltsReadingSourceRevision(sealed);await persistence.saveIeltsObjectiveInventoryItem(draft);await persistence.saveIeltsObjectiveInventoryItem(verified,{at:Date.parse(verified.verifiedAt),questionActivity:promotionQuestion});await persistence.reopenIeltsDatabase();const inventory=await persistence.getIeltsObjectiveInventoryItem(verified.id),question=await adaptIeltsReadingObjectiveTextItem(inventory,sealed.sourceRevisionRef,{ownerAdapter:createDurableIeltsReadingObjectiveTextOwnerAdapter()}),registry=createQuestionRegistry();registry.registerExecutor(question.kind,question.version,question.requiredCapabilities);return{source:sealed,inventory,question,registry,sourceRegistry:createSourceRevisionRegistry({adapters:[createIeltsReadingSourceAdapter()]})};
}

test('Reading diagram-label completion projects only declarative spatial data and delegates text scoring',async()=>{
  const source=readingSource('spatial-reading-projection'),id=`ielts-objective:${'c'.repeat(64)}`,definition=payloadFor(source,id),question=createObjectiveTextResponseQuestion(definition,{ownerAdapter:createObjectiveTextResponseOwnerAdapter({readVerifiedQuestion:()=>structuredClone(definition)})});assert.equal(question.registryRevision,'qar-objective-spatial-text-response-registry-v1');assert.deepEqual(question.item.spatialPrompt,fixture.definition.spatialPrompt);assert.equal(JSON.stringify(question).includes('acceptedAnswers'),false);assert.equal(scoreObjectiveTextResponse(question,{slots:[{slotId:'one',text:'north'},{slotId:'two',text:'south'}]}).disposition,'correct');
});

test('Reading spatial durable lifecycle validates backup before mutation, restores deleted exact owner/source/terminal, and fails closed on terminal binding tamper',async()=>{
  const harness=await durableSpatialHarness('backup'),response={slots:[{slotId:'one',text:'north'},{slotId:'two',text:'south'}]},runActivity=activity(harness.question,'spatial-reading-backup'),terminal=await executeQuestionActivity({activity:runActivity,question:harness.question,response,sourceRegistry:harness.sourceRegistry,questionRegistry:harness.registry,now:120_001}),run=await getV10Record(V10_STORES.todayRuns,terminal.run.id),backup=await buildCombinedBackup(),beforeDigest=(await buildCombinedBackup()).payloadDigest;
  assert.equal(terminal.score.disposition,'correct');assert.equal(terminal.decision.eligible,false);assert.equal(terminal.decision.affectsSchedule,false);assert.equal(JSON.stringify(terminal.run).includes('acceptedAnswers'),false);assert.equal(JSON.stringify(terminal.run).includes('Controlled spatial Reading source'),false);assert.equal(JSON.stringify(terminal.score).includes('keyDigest'),true);
  for(const mutate of [value=>value.domains.ielts.stores.objectiveInventory.find(row=>row.id===harness.inventory.id).questionPayload.spatialPrompt.title='tampered',value=>value.domains.ielts.stores.objectiveInventory.find(row=>row.id===harness.inventory.id).questionBinding.keyDigest='tampered',value=>value.domains.v10.stores.todayRuns.find(row=>row.id===run.id).envelope.receipt.metadata.questionResult.keyDigest='tampered']){const tampered=structuredClone(backup);mutate(tampered);await assert.rejects(restoreCombinedBackup(tampered),error=>error.code==='BACKUP_INVALID');assert.equal((await buildCombinedBackup()).payloadDigest,beforeDigest);}
  for(const mutate of [value=>value.domains.ielts.stores.objectiveInventory.find(row=>row.id===harness.inventory.id).questionPayload.spatialPrompt.title='tampered-recomputed',value=>value.domains.ielts.stores.objectiveInventory.find(row=>row.id===harness.inventory.id).questionBinding.keyDigest='tampered-recomputed',value=>value.domains.v10.stores.todayRuns.find(row=>row.id===run.id).envelope.receipt.metadata.questionResult.keyDigest='tampered-recomputed',value=>value.domains.v10.stores.todayRuns.find(row=>row.id===run.id).activitySpec.target.targetId='ielts-objective:missing-spatial-owner']){const recomputedTamper=recomputeBackupIntegrity(structuredClone(backup));mutate(recomputedTamper);recomputeBackupIntegrity(recomputedTamper);assert.equal(validateCombinedBackup(recomputedTamper).valid,false,'a recomputed outer digest cannot authenticate a tampered spatial owner or terminal');await assert.rejects(restoreCombinedBackup(recomputedTamper),error=>error.code==='BACKUP_INVALID');assert.equal((await buildCombinedBackup()).payloadDigest,beforeDigest);}
  await persistence.__testing.deleteOne(IELTS_STORE_NAMES.readingPassages,harness.source.id);await persistence.__testing.deleteOne(IELTS_STORE_NAMES.objectiveInventory,harness.inventory.id);await deleteV10Record(V10_STORES.todayRuns,run.id,'wave4-reading-spatial-backup-delete');await persistence.reopenIeltsDatabase();await reopenV10Database();assert.equal(await persistence.getIeltsReadingSourceRevision(harness.source.id),null);assert.equal(await persistence.getIeltsObjectiveInventoryItem(harness.inventory.id),null);assert.equal(await getV10Record(V10_STORES.todayRuns,run.id),undefined);
  await restoreCombinedBackup(backup);await persistence.reopenIeltsDatabase();await reopenV10Database();assert.deepEqual(await persistence.getIeltsReadingSourceRevision(harness.source.id),harness.source);assert.deepEqual(await persistence.getIeltsObjectiveInventoryItem(harness.inventory.id),harness.inventory);assert.deepEqual(await getV10Record(V10_STORES.todayRuns,run.id),run);
  const restoredInventory=await persistence.getIeltsObjectiveInventoryItem(harness.inventory.id),restoredSource=await persistence.getIeltsReadingSourceRevision(harness.source.id),restoredQuestion=await adaptIeltsReadingObjectiveTextItem(restoredInventory,restoredSource.sourceRevisionRef,{ownerAdapter:createDurableIeltsReadingObjectiveTextOwnerAdapter()}),restoredRegistry=createQuestionRegistry();restoredRegistry.registerExecutor(restoredQuestion.kind,restoredQuestion.version,restoredQuestion.requiredCapabilities);const restoredContext={sourceRegistry:createSourceRevisionRegistry({adapters:[createIeltsReadingSourceAdapter()]}),questionRegistry:restoredRegistry},replay=await executeQuestionActivity({activity:activity(restoredQuestion,'spatial-reading-backup'),question:restoredQuestion,response,...restoredContext,now:120_002});assert.equal(replay.run.receiptId,terminal.run.receiptId);await assert.rejects(executeQuestionActivity({activity:activity(restoredQuestion,'spatial-reading-backup'),question:restoredQuestion,response:{slots:[{slotId:'one',text:'south'},{slotId:'two',text:'north'}]},...restoredContext,now:120_003}),error=>error.code==='QUESTION_ACTIVITY_TERMINAL_RESPONSE_CONFLICT');
  const tamperedRun=structuredClone(run);tamperedRun.envelope.receipt.metadata.questionResult.keyDigest='tampered-live';await putV10Record(V10_STORES.todayRuns,tamperedRun,'wave4-reading-spatial-terminal-tamper');await assert.rejects(executeQuestionActivity({activity:activity(restoredQuestion,'spatial-reading-backup'),question:restoredQuestion,response,...restoredContext,now:120_004}),error=>error.code==='QUESTION_ACTIVITY_TERMINAL_RESPONSE_CONFLICT');await putV10Record(V10_STORES.todayRuns,run,'wave4-reading-spatial-terminal-recover');const recovered=await executeQuestionActivity({activity:activity(restoredQuestion,'spatial-reading-backup'),question:restoredQuestion,response,...restoredContext,now:120_005});assert.equal(recovered.run.receiptId,run.receiptId);
});
