import test from 'node:test';
import assert from 'node:assert/strict';
import { indexedDB, IDBKeyRange } from 'fake-indexeddb';

globalThis.indexedDB=indexedDB;
globalThis.IDBKeyRange=IDBKeyRange;
import { createTranscriptAggregate } from '../src/transcript-aggregate.js';
import { createIeltsReadingSourceRevision,IELTS_STORE_NAMES } from '../src/ielts-domain.js';
import { createIeltsObjectiveInventoryItem,deriveIeltsObjectiveInventoryId,IELTS_LISTENING_MATCHING_KINDS } from '../src/ielts-profile-inventory.js';
import { createObjectiveMatchingResponseOwnerAdapter,createObjectiveMatchingResponseQuestion,createQuestionRegistry,executeQuestionActivity,getQuestionCoverageReport } from '../src/question-activity-contracts.js';
import { createIeltsListeningMatchingOwnerAdapter,adaptIeltsListeningMatchingItem,createIeltsListeningSourceAdapter } from '../src/ielts-listening-question-activity.js';
import { createSourceRevisionRegistry,createTranscriptSourceAdapter } from '../src/source-revision-ref.js';
import { composeTodayPlan } from '../src/today-composer.js';
import { readFile } from 'node:fs/promises';
import { listV10Records } from '../src/v10-persistence.js';
import { V10_STORES } from '../src/v10-contracts.js';
import { getV10Record,putV10Record,deleteV10Record,reopenV10Database } from '../src/v10-persistence.js';
import { saveIeltsObjectiveInventoryItem,getIeltsObjectiveInventoryItem,listIeltsObjectiveInventoryItems,reopenIeltsDatabase,__testing as ieltsTesting } from '../src/ielts-persistence.js';
import { buildCombinedBackup,restoreCombinedBackup } from '../src/ielts-backup.js';
import { getTranscriptAggregate } from '../src/transcript-aggregate.js';
import { createControlledListeningMatchingProof } from '../src/listening-value-slice-ui.js';
import { listReviewEvents } from '../src/persistence.js';
import { listErrorCandidates } from '../src/error-candidate.js';

const approval=(kind,digest)=>kind==='rights'?{schemaVersion:2,id:'lm-rights',status:'approved',licenseId:'controlled-local',rightsHolder:'project',basis:'project-created',assertedAt:'2026-08-11T00:00:00.000Z',expiresAt:null,aiAsserted:false}:kind==='provenance'?{schemaVersion:2,id:'lm-provenance',sourceType:'rights-cleared-source',sourceDescription:'CONTROLLED_LOCAL_TEST_ONLY mathematical waveform',authorOrOrigin:'project',createdAt:'2026-08-11T00:00:00.000Z',aiDraft:false}:{schemaVersion:2,id:'lm-review',status:'approved',reviewerType:'human',reviewerId:'controlled-reviewer',reviewedAt:'2026-08-11T00:01:00.000Z',scopeDigest:digest,checks:['rights','pedagogy','accuracy'],selfApprovedByAi:false};
const controlledFixture=JSON.parse(await readFile(new URL('./fixtures/wave4-listening-matching-fixture.json',import.meta.url),'utf8'));

function fixture(reusePolicy='SINGLE_USE'){
  const aggregate=createTranscriptAggregate({source:{id:'wave4-listening-matching-source',kind:'transcript-source',schemaVersion:1,namespace:'private',externalId:'wave4-listening-matching-source',sourceType:'controlled-test-fixture',title:'Controlled mathematical tones',url:null,language:'en',status:'verified',createdAt:1,updatedAt:1,complete:true},segments:[{startMs:0,endMs:600,text:'low tone',language:'en',status:'verified',confidence:1,speaker:null,aligned:true},{startMs:600,endMs:1200,text:'high tone',language:'en',status:'verified',confidence:1,speaker:null,aligned:true}],provenance:{origin:'project-generated-controlled-fixture',verification:'verified',rights:'allowed',privacy:'private'},createdAt:1});
  const reference=createTranscriptSourceAdapter({getTranscriptAggregate:()=>aggregate}).createRef(aggregate),base={skill:'listening',profiles:['academic','general-training'],form:{id:'lm-form',revision:1},section:{id:'lm-section',revision:1,number:1},order:reusePolicy==='SINGLE_USE'?1:2,itemId:`lm-${reusePolicy.toLowerCase()}`,itemRevision:1},id=deriveIeltsObjectiveInventoryId(base),payload={id,kind:'listening-matching',prompt:'Match controlled tone positions.',slots:[{id:'first',label:'First tone',acceptedOptionId:'low'},{id:'second',label:'Second tone',acceptedOptionId:reusePolicy==='ALLOW_REUSE'?'low':'high'}],options:[{id:'low',label:'Low tone'},{id:'high',label:'High tone'}],reusePolicy,target:{schemaVersion:2,targetType:'ielts-objective-item',targetId:id,cardId:null,senseId:null,skill:'listening',sourceId:reference.sourceId,sourceRevision:reference.revisionId},sourceRevisionRef:reference,createdAt:1,updatedAt:1};
  const seed=createObjectiveMatchingResponseQuestion(payload,{ownerAdapter:createObjectiveMatchingResponseOwnerAdapter({readVerifiedQuestion:()=>payload})}),binding={kind:seed.kind,schemaVersion:seed.version,registryRevision:seed.registryRevision,questionId:seed.id,promptRevision:seed.promptRevision,promptDigest:seed.promptDigest,keyRevision:seed.keyRevision,keyDigest:seed.keyDigest,rubricRevision:seed.rubricRevision,rubricDigest:seed.rubricDigest,scorer:seed.scorer,reviewPolicyRevision:seed.reviewPolicyRevision,requiredCapabilities:seed.requiredCapabilities};
  const draft=createIeltsObjectiveInventoryItem({...base,kind:'ielts-objective-inventory-item',schemaVersion:1,sourceRevisionRef:reference,questionBinding:binding,questionPayload:payload,status:'draft',createdAt:'2026-08-11T00:00:00.000Z',verifiedAt:null,retiredAt:null,retirementReason:null,rights:null,provenance:null,humanReview:null,extensions:{fixture:'CONTROLLED_LOCAL_TEST_ONLY'}}),verified=createIeltsObjectiveInventoryItem({...draft,status:'verified',verifiedAt:'2026-08-11T00:01:00.000Z',rights:approval('rights',draft.contentDigest),provenance:approval('provenance',draft.contentDigest),humanReview:approval('review',draft.contentDigest)});
  return {aggregate,reference,verified};
}

function draftWithSourceReference(verified,sourceRevisionRef){
  const payload={...verified.questionPayload,sourceRevisionRef,target:{...verified.questionPayload.target,sourceId:sourceRevisionRef.sourceId,sourceRevision:sourceRevisionRef.revisionId}},seed=createObjectiveMatchingResponseQuestion(payload,{ownerAdapter:createObjectiveMatchingResponseOwnerAdapter({readVerifiedQuestion:()=>payload})}),questionBinding={kind:seed.kind,schemaVersion:seed.version,registryRevision:seed.registryRevision,questionId:seed.id,promptRevision:seed.promptRevision,promptDigest:seed.promptDigest,keyRevision:seed.keyRevision,keyDigest:seed.keyDigest,rubricRevision:seed.rubricRevision,rubricDigest:seed.rubricDigest,scorer:seed.scorer,reviewPolicyRevision:seed.reviewPolicyRevision,requiredCapabilities:seed.requiredCapabilities},candidate={...verified,sourceRevisionRef,questionPayload:payload,questionBinding,status:'draft',rights:null,provenance:null,humanReview:null,verifiedAt:null,retiredAt:null,retirementReason:null};delete candidate.contentDigest;return candidate;
}

function activity(question,id){const plan=composeTodayPlan({content:[{id,type:'listening',target:question.item.target,executor:'qar-objective-matching-response',estimatedSeconds:60}],now:1_000,minutes:5});return {...plan.activities[0],execution:{kind:'qar-objective-matching-response',status:'ready'},assistanceCollectionMode:'qar-listening',launchBinding:'wave4-listening-matching',launch:{promptRevision:question.promptRevision,configRevision:question.registryRevision,configDigest:question.promptDigest},evaluationBinding:{applicable:true,revision:question.registryRevision,keyRevision:question.keyRevision,keyDigest:question.keyDigest,rubricRevision:question.rubricRevision,rubricDigest:question.rubricDigest,scoringPolicyRevision:question.scorer.id,reviewPolicyRevision:question.reviewPolicyRevision}};}

// Contract RED: Listening matching needs its own branded owner seam, rather
// than piggy-backing on the Text Response adapter.
test('Listening matching exposes a branded owner adapter contract', async () => {
  const listening = await import('../src/ielts-listening-question-activity.js');
  assert.equal(typeof listening.createIeltsListeningMatchingOwnerAdapter, 'function');
  assert.equal(typeof listening.adaptIeltsListeningMatchingItem, 'function');
  assert.equal(typeof listening.createDurableIeltsListeningMatchingOwnerAdapter, 'function');
});

test('Listening matching accepts safe canonical Transcript metadata but rejects owner and lifecycle substitutions',()=>{
  const {verified,reference}=fixture(),safe={...reference,display:{label:'Controlled Transcript'},extensions:{sourceNote:'portable'}},readingSource=createIeltsReadingSourceRevision({id:'lm-cross-owner-source',revision:1,profile:'academic',title:'Controlled Reading source',passage:'CONTROLLED_LOCAL_TEST_ONLY source passage.',objectiveItems:[],status:'verified',createdAt:1,updatedAt:1}),invalid=[{...reference,kind:'core-card',authority:'core-card-registry'},{...reference,authority:'custom-owner'},{...reference,locator:{revisionId:'wrong-revision'}},{...reference,tombstone:{kind:'deleted'}},{...reference,provenance:{...reference.provenance,verification:'unverified'}},{...reference,provenance:{...reference.provenance,rights:'blocked'}}];
  assert.doesNotThrow(()=>createIeltsObjectiveInventoryItem(draftWithSourceReference(verified,reference)));assert.doesNotThrow(()=>createIeltsObjectiveInventoryItem(draftWithSourceReference(verified,safe)));assert.throws(()=>createIeltsObjectiveInventoryItem(draftWithSourceReference(verified,readingSource.sourceRevisionRef)),error=>error.code==='IELTS_INVENTORY_INVALID');for(const sourceRevisionRef of invalid)assert.throws(()=>createIeltsObjectiveInventoryItem(draftWithSourceReference(verified,sourceRevisionRef)));
});

test('Listening matching seals exact Transcript inventory, scores reuse modes, and never exposes bindings',async()=>{
  assert.deepEqual(IELTS_LISTENING_MATCHING_KINDS,['listening-matching','listening-plan-map-diagram-labelling']);
  for(const reusePolicy of ['SINGLE_USE','ALLOW_REUSE']){
    const {aggregate,reference,verified}=fixture(reusePolicy),owner=createIeltsListeningMatchingOwnerAdapter({readVerifiedInventory:async id=>id===verified.id?verified:null,getTranscriptAggregate:async id=>id===reference.revisionId?aggregate:null}),question=await adaptIeltsListeningMatchingItem(verified,reference,{ownerAdapter:owner}),matching=await import('../src/objective-matching-response.js');
    assert.equal(question.kind,'listening-matching');assert.equal(JSON.stringify(question).includes('acceptedOptionId'),false);assert.equal((await matching.scoreObjectiveMatchingResponseAsync(question,{slots:[{slotId:'first',optionId:'low'},{slotId:'second',optionId:reusePolicy==='ALLOW_REUSE'?'low':'high'}]})).disposition,'correct');
    assert.equal((await matching.scoreObjectiveMatchingResponseAsync(question,{slots:[{slotId:'first',optionId:null},{slotId:'second',optionId:reusePolicy==='ALLOW_REUSE'?'low':'high'}]})).disposition,'partial');
    const duplicate=await matching.scoreObjectiveMatchingResponseAsync(question,{slots:[{slotId:'first',optionId:'low'},{slotId:'second',optionId:'low'}]});assert.equal(duplicate.valid,reusePolicy==='ALLOW_REUSE');
  }
});

test('Listening matching executes one canonical terminal receipt with default-deny replay/conflict',async()=>{
  const {aggregate,reference,verified}=fixture(),owner=createIeltsListeningMatchingOwnerAdapter({readVerifiedInventory:async()=>verified,getTranscriptAggregate:async()=>aggregate}),question=await adaptIeltsListeningMatchingItem(verified,reference,{ownerAdapter:owner}),registry=createQuestionRegistry();registry.registerExecutor(question.kind,question.version,question.requiredCapabilities);const sourceRegistry=createSourceRevisionRegistry({adapters:[createIeltsListeningSourceAdapter({getAggregate:async()=>aggregate})]}),runActivity=activity(question,`lm-run:${verified.id}`),response={slots:[{slotId:'first',optionId:'low'},{slotId:'second',optionId:'high'}]};
  const first=await executeQuestionActivity({activity:runActivity,question,response,sourceRegistry,questionRegistry:registry,now:1_001}),replay=await executeQuestionActivity({activity:runActivity,question,response,sourceRegistry,questionRegistry:registry,now:1_002});assert.equal(first.run.status,'completed');assert.equal(first.decision.eligible,false);assert.equal(first.decision.affectsSchedule,false);assert.equal(replay.run.receiptId,first.run.receiptId);
  await assert.rejects(executeQuestionActivity({activity:runActivity,question,response:{slots:[{slotId:'first',optionId:'high'},{slotId:'second',optionId:'low'}]},sourceRegistry,questionRegistry:registry,now:1_003}),error=>error.code==='QUESTION_ACTIVITY_TERMINAL_RESPONSE_CONFLICT');
});

test('Listening matching owner changes and accessor options fail closed before scoring',async()=>{
  const {aggregate,reference,verified}=fixture();let current=aggregate;const owner=createIeltsListeningMatchingOwnerAdapter({readVerifiedInventory:async()=>verified,getTranscriptAggregate:async()=>current}),question=await adaptIeltsListeningMatchingItem(verified,reference,{ownerAdapter:owner}),matching=await import('../src/objective-matching-response.js');current=null;assert.deepEqual((await matching.scoreObjectiveMatchingResponseAsync(question,{slots:[{slotId:'first',optionId:'low'},{slotId:'second',optionId:'high'}]})).errors,['QUESTION_ACTIVITY_OWNER_UNAVAILABLE']);let calls=0;assert.throws(()=>createIeltsListeningMatchingOwnerAdapter({get readVerifiedInventory(){calls++;return async()=>null;},getTranscriptAggregate:async()=>null}),error=>error.code==='QUESTION_ACTIVITY_OWNER_UNAVAILABLE');assert.equal(calls,0);
  const row=getQuestionCoverageReport().kinds.find(value=>value.kind==='listening-matching');assert.equal(row.coverage,'PARTIAL');assert.equal(row.dimensions.section,'GAP');assert.equal(row.dimensions.readiness,'GAP');
});

test('Listening matching rejects every inventory and Transcript lifecycle drift before a canonical mutation',async()=>{
  const cases=[
    ['inventory-null',state=>{state.inventory=null;}],
    ['inventory-throw',state=>{state.throwInventory=true;}],
    ['inventory-accessor',state=>{const value=structuredClone(state.verified);Object.defineProperty(value,'questionPayload',{get(){state.inventoryGets+=1;return state.verified.questionPayload;}});state.inventory=value;}],
    ['inventory-draft',state=>{state.inventory={...state.verified,status:'draft',verifiedAt:null,rights:null,provenance:null,humanReview:null};}],
    ['inventory-retired',state=>{state.inventory={...state.verified,status:'retired'};}],
    ['profiles-reordered',state=>{state.inventory={...state.verified,profiles:['general-training','academic']};}],
    ['profiles-missing',state=>{state.inventory={...state.verified,profiles:['academic']};}],
    ['payload-mutated',state=>{state.inventory={...state.verified,questionPayload:{...state.verified.questionPayload,prompt:'changed'}};}],
    ['binding-mutated',state=>{state.inventory={...state.verified,questionBinding:{...state.verified.questionBinding,promptDigest:'changed'}};}],
    ['target-mutated',state=>{state.inventory={...state.verified,questionPayload:{...state.verified.questionPayload,target:{...state.verified.questionPayload.target,sourceRevision:'changed'}}};}],
    ['source-ref-mutated',state=>{state.inventory={...state.verified,sourceRevisionRef:{...state.verified.sourceRevisionRef,integrity:'fnv1a64:1:0'}};}],
    ['transcript-null',state=>{state.source=null;}],
    ['transcript-throw',state=>{state.throwSource=true;}],
    ['transcript-accessor',state=>{const value=structuredClone(state.aggregate);Object.defineProperty(value,'source',{get(){state.sourceGets+=1;return state.aggregate.source;}});state.source=value;}],
    ['source-identity',state=>{state.source={...structuredClone(state.aggregate),source:{...state.aggregate.source,id:'changed'}};}],
    ['revision-identity',state=>{state.source={...structuredClone(state.aggregate),revision:{...state.aggregate.revision,id:'changed'}};}],
    ['digest',state=>{state.source={...structuredClone(state.aggregate),revision:{...state.aggregate.revision,contentDigest:'fnv1a64:1:0'}};}],
    ['segment-order',state=>{state.source={...structuredClone(state.aggregate),segments:[...state.aggregate.segments].reverse()};}],
    ['segment-body',state=>{state.source={...structuredClone(state.aggregate),segments:[{...state.aggregate.segments[0],text:'changed'},...state.aggregate.segments.slice(1)]};}],
    ['segment-timing',state=>{state.source={...structuredClone(state.aggregate),segments:[{...state.aggregate.segments[0],endMs:599},...state.aggregate.segments.slice(1)]};}],
    ['segment-alignment',state=>{state.source={...structuredClone(state.aggregate),segments:[{...state.aggregate.segments[0],aligned:false},...state.aggregate.segments.slice(1)]};}],
    ['coverage',state=>{state.source={...structuredClone(state.aggregate),revision:{...state.aggregate.revision,coverage:{...state.aggregate.revision.coverage,ratio:.5}}};}],
    ['provenance',state=>{state.source={...structuredClone(state.aggregate),revision:{...state.aggregate.revision,provenance:{...state.aggregate.revision.provenance,verification:'unverified'}}};}],
    ['rights',state=>{state.source={...structuredClone(state.aggregate),revision:{...state.aggregate.revision,provenance:{...state.aggregate.revision.provenance,rights:'blocked'}}};}],
    ['source-lifecycle',state=>{state.source={...structuredClone(state.aggregate),source:{...state.aggregate.source,status:'unverified'}};}],
    ['revision-lifecycle',state=>{state.source={...structuredClone(state.aggregate),revision:{...state.aggregate.revision,status:'unverified'}};}],
    ['tombstone',state=>{state.source={...structuredClone(state.aggregate),revision:{...state.aggregate.revision,tombstone:{kind:'deleted'}}};}]
  ];
  for(const [index,[name,mutate]] of cases.entries()){
    const {aggregate,reference,verified}=fixture(),state={aggregate,verified,inventory:verified,source:aggregate,throwInventory:false,throwSource:false,inventoryGets:0,sourceGets:0},owner=createIeltsListeningMatchingOwnerAdapter({readVerifiedInventory:async()=>{if(state.throwInventory)throw new Error('offline');return state.inventory;},getTranscriptAggregate:async()=>{if(state.throwSource)throw new Error('offline');return state.source;}}),question=await adaptIeltsListeningMatchingItem(verified,reference,{ownerAdapter:owner}),registry=createQuestionRegistry();registry.registerExecutor(question.kind,question.version,question.requiredCapabilities);const context={questionRegistry:registry,sourceRegistry:createSourceRevisionRegistry({adapters:[createIeltsListeningSourceAdapter({getAggregate:async()=>state.source})]})},response={slots:[{slotId:'first',optionId:'low'},{slotId:'second',optionId:'high'}]},before={runs:(await listV10Records(V10_STORES.todayRuns,{sortBy:null})).map(row=>row.id).sort(),reviews:(await listReviewEvents()).map(row=>row.id).sort(),errors:(await listErrorCandidates()).map(row=>row.id).sort(),providers:(await listV10Records(V10_STORES.resolverEvents,{sortBy:null})).map(row=>row.id).sort()};mutate(state);await assert.rejects(executeQuestionActivity({activity:activity(question,`lm-r5-lifecycle:${index}`),question,response,...context,now:60_000+index}),error=>['QUESTION_ACTIVITY_OWNER_UNAVAILABLE','QUESTION_ACTIVITY_OWNER_CHANGED','QUESTION_ACTIVITY_OWNER_VERIFICATION_REQUIRED','QUESTION_ACTIVITY_SOURCE_BINDING_MISMATCH'].includes(error.code),name);assert.deepEqual({runs:(await listV10Records(V10_STORES.todayRuns,{sortBy:null})).map(row=>row.id).sort(),reviews:(await listReviewEvents()).map(row=>row.id).sort(),errors:(await listErrorCandidates()).map(row=>row.id).sort(),providers:(await listV10Records(V10_STORES.resolverEvents,{sortBy:null})).map(row=>row.id).sort()},before,name);if(name==='inventory-accessor')assert.equal(state.inventoryGets,0);if(name==='transcript-accessor')assert.equal(state.sourceGets,0);
  }
});

test('controlled matching fixture prepares durable owners and publishes only selected matching state',async()=>{
  const fixture=JSON.parse(await readFile(new URL('./fixtures/wave4-listening-matching-fixture.json',import.meta.url),'utf8')),ui=await import('../src/listening-value-slice-ui.js'),proof=await ui.createControlledListeningMatchingProof({fixture}),opened=await proof.open();assert.equal(opened.items.length,2);assert.equal(JSON.stringify(opened).includes('acceptedOptionId'),false);const first=opened.items[0],terminal=await proof.submit(first.id,{slots:[{slotId:'first',optionId:'low'},{slotId:'middle',optionId:'high'}]});assert.equal(terminal.result.disposition,'correct');assert.equal(terminal.result.eligible,false);assert.equal(terminal.result.affectsSchedule,false);assert.equal(JSON.stringify(terminal).includes('answerBindingDigest'),false);assert.equal(JSON.stringify(terminal).includes('keyDigest'),false);
});

test('controlled matching fixture rejects deterministic manifest mutations and accessors before opening owners',async()=>{
  const original=JSON.parse(await readFile(new URL('./fixtures/wave4-listening-matching-fixture.json',import.meta.url),'utf8')),ui=await import('../src/listening-value-slice-ui.js');for(const mutate of [fixture=>fixture.transcript.segments[0].text='changed',fixture=>fixture.transcript.coverage.endMs=1700,fixture=>fixture.definitions[0].slots[0].acceptedOptionId='high',fixture=>fixture.definitions[1].reusePolicy='SINGLE_USE',fixture=>fixture.audio.sha256='0'.repeat(64),fixture=>fixture.claims.humanSpeech=true]){const value=structuredClone(original);mutate(value);await assert.rejects(ui.createControlledListeningMatchingProof({fixture:value}),error=>error.code==='LISTENING_FIXTURE_INVALID');}let calls=0;const accessor=structuredClone(original);Object.defineProperty(accessor,'definitions',{get(){calls++;return [];}});await assert.rejects(ui.createControlledListeningMatchingProof({fixture:accessor}),error=>error.code==='LISTENING_FIXTURE_INVALID');assert.equal(calls,0);
});

test('Listening matching exhaustive response matrix fails before a Run and preserves default-deny terminals',async()=>{
  const matching=await import('../src/objective-matching-response.js');for(const reusePolicy of ['SINGLE_USE','ALLOW_REUSE']){const {aggregate,reference,verified}=fixture(reusePolicy),owner=createIeltsListeningMatchingOwnerAdapter({readVerifiedInventory:async()=>verified,getTranscriptAggregate:async()=>aggregate}),question=await adaptIeltsListeningMatchingItem(verified,reference,{ownerAdapter:owner}),registry=createQuestionRegistry();registry.registerExecutor(question.kind,question.version,question.requiredCapabilities);const context={questionRegistry:registry,sourceRegistry:createSourceRevisionRegistry({adapters:[createIeltsListeningSourceAdapter({getAggregate:async()=>aggregate})]})},second=reusePolicy==='ALLOW_REUSE'?'low':'high',valid=[['correct',[['first','low'],['second',second]],'correct'],['partial',[['first',null],['second',second]],'partial'],['wrong',[['first','high'],['second',reusePolicy==='ALLOW_REUSE'?'high':'low']],'wrong'],['null',[['first',null],['second',null]],'wrong']];for(const [index,[name,slots,disposition]] of valid.entries()){const response={slots:slots.map(([slotId,optionId])=>({slotId,optionId}))},score=await matching.scoreObjectiveMatchingResponseAsync(question,response);assert.equal(score.disposition,disposition,`${reusePolicy}/${name}`);const result=await executeQuestionActivity({activity:activity(question,`lm-r3:${reusePolicy}:${name}:${index}`),question,response,...context,now:30_000+index});assert.equal(result.decision.eligible,false);assert.equal(result.decision.affectsSchedule,false);}const before=(await listV10Records(V10_STORES.todayRuns,{sortBy:null})).length,invalid=[{}, {slots:[]},{slots:[{slotId:'second',optionId:second},{slotId:'first',optionId:'low'}]},{slots:[{slotId:'first',optionId:'missing'},{slotId:'second',optionId:second}]},...(reusePolicy==='SINGLE_USE'?[{slots:[{slotId:'first',optionId:'low'},{slotId:'second',optionId:'low'}]}]:[])];for(const [index,response] of invalid.entries()){await assert.rejects(executeQuestionActivity({activity:activity(question,`lm-r3-invalid:${reusePolicy}:${index}`),question,response,...context,now:40_000+index}),error=>error.code==='QUESTION_ACTIVITY_RESPONSE_INVALID');assert.equal((await listV10Records(V10_STORES.todayRuns,{sortBy:null})).length,before);} }
});

test('Listening matching promotion accepts only the live branded adapter question and preserves the draft on every forgery',async()=>{
  const {aggregate,reference,verified}=fixture('ALLOW_REUSE'),draft={...verified,status:'draft',verifiedAt:null,rights:null,provenance:null,humanReview:null},owner=createIeltsListeningMatchingOwnerAdapter({readVerifiedInventory:async()=>verified,getTranscriptAggregate:async()=>aggregate}),question=await adaptIeltsListeningMatchingItem(verified,reference,{ownerAdapter:owner});
  await saveIeltsObjectiveInventoryItem(draft,{at:Date.parse(draft.createdAt)});
  const generic=createObjectiveMatchingResponseQuestion(verified.questionPayload,{ownerAdapter:createObjectiveMatchingResponseOwnerAdapter({readVerifiedQuestion:()=>verified.questionPayload})});
  for(const forged of [generic,structuredClone(question),{...question,item:{...question.item}},{...question,kind:'reading-matching-information'},{...question,sourceRevisionRef:{...question.sourceRevisionRef,revisionId:'forged'}}])await assert.rejects(saveIeltsObjectiveInventoryItem(verified,{at:Date.parse(verified.verifiedAt),questionActivity:forged}),error=>error.code==='IELTS_INVENTORY_INVALID');
  assert.equal((await getIeltsObjectiveInventoryItem(verified.id)).status,'draft');await saveIeltsObjectiveInventoryItem(verified,{at:Date.parse(verified.verifiedAt),questionActivity:question});assert.equal((await getIeltsObjectiveInventoryItem(verified.id)).status,'verified');await saveIeltsObjectiveInventoryItem(verified,{at:Date.parse(verified.verifiedAt),questionActivity:question});
});

test('Listening matching controlled terminal rejects learner, score, and receipt tampering without replacing its winner',async()=>{
  const proof=await createControlledListeningMatchingProof({fixture:controlledFixture}),opened=await proof.open(),item=opened.items[1],response={slots:[{slotId:item.slots[0].id,optionId:'low'},{slotId:item.slots[1].id,optionId:'low'}]},first=item.result?{result:item.result}:await proof.submit(item.id,response),stored=await getV10Record(V10_STORES.todayRuns,first.result.runId);
  for(const [name,mutate] of [['learner-output',row=>{row.envelope.attempt.learnerOutput='{"slots":[]}';}],['matching-score',row=>{row.envelope.attempt.metadata.objectiveMatchingResponse.totals={numerator:0,denominator:2};}],['receipt-binding',row=>{row.envelope.receipt.metadata.questionResult.answerBindingDigest='tampered';}]]){const injected=structuredClone(stored);mutate(injected);await putV10Record(V10_STORES.todayRuns,injected,'wave4-listening-matching-terminal-tamper');const persisted=await getV10Record(V10_STORES.todayRuns,stored.id);await assert.rejects(proof.submit(item.id,response),error=>['QUESTION_ACTIVITY_TERMINAL_RESPONSE_CONFLICT','LISTENING_FIXTURE_TERMINAL_INVALID'].includes(error.code),name);assert.deepEqual(await getV10Record(V10_STORES.todayRuns,stored.id),persisted,name);await putV10Record(V10_STORES.todayRuns,stored,'wave4-listening-matching-terminal-restore');}
  assert.equal((await proof.submit(item.id,response)).result.runId,first.result.runId);await assert.rejects(proof.submit(item.id,{slots:[{slotId:item.slots[0].id,optionId:'high'},{slotId:item.slots[1].id,optionId:'high'}]}),error=>error.code==='QUESTION_ACTIVITY_TERMINAL_RESPONSE_CONFLICT');
});

test('Listening matching combined backup validates before mutation and restores Transcript, verified inventory, and terminal',async()=>{
  const proof=await createControlledListeningMatchingProof({fixture:controlledFixture}),opened=await proof.open(),item=opened.items[0],response={slots:[{slotId:item.slots[0].id,optionId:'low'},{slotId:item.slots[1].id,optionId:'high'}]},terminal=item.result?{result:item.result}:await proof.submit(item.id,response),inventory=(await listIeltsObjectiveInventoryItems({skill:'listening',status:'verified'})).find(row=>row.itemId===controlledFixture.definitions[0].id),run=await getV10Record(V10_STORES.todayRuns,terminal.result.runId),aggregate=await getTranscriptAggregate(inventory.sourceRevisionRef.revisionId),backup=await buildCombinedBackup(),privateInventory=backup.domains.ielts.stores.objectiveInventory.find(row=>row.id===inventory.id),publicRun=backup.domains.v10.stores.todayRuns.find(row=>row.id===run.id);
  const internalMatchingMetadata=run.envelope.attempt.metadata.objectiveMatchingResponse;assert.ok(privateInventory);assert.ok(publicRun);assert.equal(JSON.stringify(privateInventory).includes('acceptedOptionId'),true);assert.equal(JSON.stringify(publicRun).includes('acceptedOptionId'),false);assert.deepEqual(publicRun.envelope.attempt.metadata.objectiveMatchingResponse,internalMatchingMetadata);assert.equal(publicRun.envelope.attempt.metadata.objectiveMatchingResponse.answerBindingDigest,internalMatchingMetadata.answerBindingDigest);
  const tampered=structuredClone(backup);tampered.domains.ielts.stores.objectiveInventory.find(row=>row.id===inventory.id).questionPayload.prompt='tampered';const before=await buildCombinedBackup();await assert.rejects(restoreCombinedBackup(tampered),error=>error.code==='BACKUP_INVALID');assert.equal((await buildCombinedBackup()).payloadDigest,before.payloadDigest);
  await ieltsTesting.deleteOne(IELTS_STORE_NAMES.objectiveInventory,inventory.id);await deleteV10Record(V10_STORES.todayRuns,run.id,'wave4-listening-matching-backup-delete');for(const segment of aggregate.segments)await deleteV10Record(V10_STORES.canonicalTranscriptSegments,segment.id,'wave4-listening-matching-transcript-delete');await deleteV10Record(V10_STORES.transcriptRevisions,aggregate.revision.id,'wave4-listening-matching-transcript-delete');await deleteV10Record(V10_STORES.transcriptSources,aggregate.source.id,'wave4-listening-matching-transcript-delete');await reopenIeltsDatabase();await reopenV10Database();assert.equal(await getIeltsObjectiveInventoryItem(inventory.id),null);assert.equal(await getV10Record(V10_STORES.todayRuns,run.id),undefined);assert.equal(await getTranscriptAggregate(aggregate.revision.id),null);
  await restoreCombinedBackup(backup);await reopenIeltsDatabase();await reopenV10Database();assert.deepEqual(await getIeltsObjectiveInventoryItem(inventory.id),inventory);assert.deepEqual(await getV10Record(V10_STORES.todayRuns,run.id),run);assert.deepEqual(await getTranscriptAggregate(aggregate.revision.id),aggregate);
  const restored=await createControlledListeningMatchingProof({fixture:controlledFixture}),reopened=await restored.open();assert.equal(reopened.items.find(value=>value.id===item.id).result.runId,run.id);assert.equal((await restored.submit(item.id,response)).result.runId,run.id);await assert.rejects(restored.submit(item.id,{slots:[{slotId:item.slots[0].id,optionId:'high'},{slotId:item.slots[1].id,optionId:'low'}]}),error=>error.code==='QUESTION_ACTIVITY_TERMINAL_RESPONSE_CONFLICT');
});
