import { deleteCaptureDraft, listCaptureDrafts, persistCaptureDraft } from './persistence.js';

const escape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function notice(message){const toast=document.querySelector('#toast');if(toast){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600);}}
function qualityLabel(draft){if(!draft.term)return'Thiếu từ/cụm';if(!draft.sourceContext)return'Thiếu ngữ cảnh';if(!draft.meaning)return'Cần chọn nghĩa';return'Sẵn sàng hoàn thiện';}
export async function mountCaptureInbox(){
  const route=document.querySelector('[data-view="capture"]');if(!route||document.querySelector('#quickCapturePanel'))return;
  const panel=document.createElement('section');panel.id='quickCapturePanel';panel.className='quick-capture-panel';panel.innerHTML=`<div class="quick-capture-head"><div><span class="greeting-badge">GHI NHANH</span><h2>Bắt từ trước, hoàn thiện sau</h2><p>Bản nháp không vào Today hoặc lịch FSRS cho tới khi bạn xác nhận bằng form đầy đủ.</p></div><strong id="draftCount">0 bản nháp</strong></div><form id="quickCaptureForm" class="quick-capture-form"><label>Từ hoặc cụm từ *<input id="quickTerm" required autocomplete="off" placeholder="Ví dụ: run into" /></label><label>Ngữ cảnh<textarea id="quickContext" rows="2" placeholder="Câu hoặc đoạn bạn vừa gặp"></textarea></label><label>Nguồn<input id="quickSource" placeholder="Sách, video, bài viết…" /></label><button class="primary-button" type="submit">Lưu nhanh</button></form><div id="qualityInbox" class="quality-inbox" aria-live="polite"></div>`;
  route.prepend(panel);
  let activeDraftId=null;
  const render=async()=>{const drafts=await listCaptureDrafts();document.querySelector('#draftCount').textContent=`${drafts.length} bản nháp`;const host=document.querySelector('#qualityInbox');host.innerHTML=drafts.length?drafts.map(draft=>`<article class="draft-row" data-draft-id="${escape(draft.id)}"><div><strong>${escape(draft.term||'Chưa có từ')}</strong><span>${escape(qualityLabel(draft))}</span><p>${escape(draft.sourceContext||'Chưa lưu ngữ cảnh')}</p><small>${escape(draft.sourceLabel||'Nguồn chưa ghi')}</small></div><div class="draft-actions"><button class="secondary-button" data-draft-complete>Hoàn thiện</button><button class="ai-button" data-draft-ai>AI bổ sung</button><button class="icon-button" data-draft-delete aria-label="Xóa bản nháp">×</button></div></article>`).join(''):'<p class="muted">Chưa có bản nháp. Ghi nhanh một từ khi bạn vừa gặp nó.</p>';};
  document.querySelector('#quickCaptureForm').addEventListener('submit',async event=>{event.preventDefault();const term=document.querySelector('#quickTerm').value.trim();if(!term)return;await persistCaptureDraft({term,sourceContext:document.querySelector('#quickContext').value,sourceLabel:document.querySelector('#quickSource').value,status:'captured'});event.currentTarget.reset();await render();notice('Đã lưu vào Hộp thư từ mới; chưa vào lịch học.');});
  panel.addEventListener('click',async event=>{const row=event.target.closest('[data-draft-id]');if(!row)return;const drafts=await listCaptureDrafts();const draft=drafts.find(item=>item.id===row.dataset.draftId);if(!draft)return;if(event.target.closest('[data-draft-delete]')){await deleteCaptureDraft(draft.id);await render();return;}if(event.target.closest('[data-draft-complete],[data-draft-ai]')){activeDraftId=draft.id;document.querySelector('#wordInput').value=draft.term||'';document.querySelector('#sourceContextInput').value=draft.sourceContext||'';document.querySelector('#wordInput').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'center'});document.querySelector('#wordInput').focus();if(event.target.closest('[data-draft-ai]'))setTimeout(()=>document.querySelector('#aiEnrichButton')?.click(),80);}});
  document.querySelector('#addWordForm')?.addEventListener('submit',()=>{if(!activeDraftId)return;const id=activeDraftId;setTimeout(async()=>{if(!document.querySelector('#wordInput')?.value){await deleteCaptureDraft(id);activeDraftId=null;await render();}},800);});
  await render();
}
