import { browseContentPacks,deleteContentPack,installContentPack,listContentLessons,openContentLesson,refreshContentCatalog } from './content-platform.js';
import { resolveTranscriptWithFallback,continueTranscriptProgressively,listCachedTranscripts,parseYouTubeVideoId } from './transcript-resolver-v2.js';
import { handlePhase5FallbackChange,handlePhase5FallbackClick,phase5FallbackMarkup,phase5RecoveryMessage,phase5RequestPolicy } from './phase5-fallback-ui.js';
import { createYoutubeSentencePlayer } from './youtube-sentence-player.js';
import { IELTS_STORE_NAMES } from './ielts-domain.js';
import { listIeltsRecords } from './ielts-persistence.js';

const escape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
let activeTab='discover';
let videoBusy=false;
let bypassLegacyLauncher=false;
const boundLaunchers=new WeakSet();
let renderGeneration=0;

function dialog(){return document.querySelector('#v10IeltsHubDialog');}
function panel(){return document.querySelector('#v10IeltsHubPanel');}
function toast(message){const node=document.querySelector('#toast');if(!node)return;node.textContent=message;node.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.remove('show'),3500);}
function openLegacyTab(tab){const launcher=document.querySelector('#openIeltsLabButton,#openIeltsLabMobile');if(!launcher)return;bypassLegacyLauncher=true;try{launcher.click();}finally{bypassLegacyLauncher=false;}setTimeout(()=>document.querySelector(`[data-ielts-tab="${tab}"]`)?.click(),60);}
async function openVideoLoop(row){const youtubeId=parseYouTubeVideoId(row.videoId),player=youtubeId?createYoutubeSentencePlayer(youtubeId,row.segments?.[0]):null;await globalThis.VocabMasterSentenceLoop?.open?.({sourceId:youtubeId?`youtube:${youtubeId}`:`transcript:${row.transcriptRevisionId||row.videoId}`,sourceType:youtubeId?'video':'imported-transcript',title:row.title||'Imported transcript',sentences:row.segments||[],player,transcriptRevisionId:row.transcriptRevisionId||null});}

function shell(content, currentTrack = 'academic'){return`<div class="v10-ielts-shell"><header class="v10-ielts-header"><div><p class="eyebrow">VOCAB MASTER · IELTS LEARNING SYSTEM</p><h2>IELTS</h2><p>Kho từ trung tâm · nội dung theo nhu cầu · học theo câu · lỗi được theo dõi dài hạn</p></div><div class="ielts-track-switcher" role="group" aria-label="IELTS Track"><button type="button" class="ielts-track-btn" data-ielts-track="academic" aria-pressed="${currentTrack==='academic'}">Academic</button><button type="button" class="ielts-track-btn" data-ielts-track="general-training" aria-pressed="${currentTrack==='general-training'}">General Training</button></div><button class="ielts-icon-button" data-v10-ielts-close aria-label="Đóng IELTS">×</button></header><nav class="v10-ielts-tabs" role="tablist">${[['discover','Khám phá bài học'],['videos','Video của tôi'],['skills','Lỗi & kỹ năng']].map(([id,label])=>`<button role="tab" data-v10-ielts-tab="${id}" aria-selected="${activeTab===id}">${label}</button>`).join('')}</nav><main class="v10-ielts-panel">${content}</main></div>`;}

function formatBytes(value){const bytes=Math.max(0,Number(value||0));if(bytes<1024)return`${bytes} B`;if(bytes<1024*1024)return`${(bytes/1024).toFixed(1)} KB`;return`${(bytes/1024/1024).toFixed(1)} MB`;}
function packCardsMarkup(packs){return packs.length?packs.map(row=>`<article class="v10-content-card" data-pack-state="${escape(row.state)}"><div><span class="v10-pack-badges"><em>${row.catalogInstallable?'Đã xác minh':'LKG hết hạn'}</em>${row.state==='installed'?'<em>Đã cài · offline</em>':''}${row.updateAvailable?'<em>Có bản cập nhật</em>':''}${row.revoked?'<em class="error">Đã thu hồi</em>':''}</span><h3>${escape(row.title)}</h3><p>${escape(row.summary)}</p><small>Revision ${row.revision} · ${row.lessonCount} bài · ${formatBytes(row.byteLength)}</small><details><summary>Quyền & nguồn</summary><p>${escape(row.rights?.licenseId||row.rights?.status||'Không có dữ liệu quyền')}</p><p>${escape(row.provenance?.sourceDescription||row.provenance?.sourceType||'Không có provenance')}</p><p>Review: ${escape(row.review?.status||'missing')}</p></details></div><div class="v10-content-actions">${row.state==='installed'?`<button class="secondary-button" data-v10-delete-pack="${escape(row.id)}">Xóa pack</button>`:row.revoked||!row.catalogInstallable?'':`<button class="primary-button" data-v10-install-pack="${escape(row.id)}">${row.updateAvailable?'Cập nhật':'Cài để học offline'}</button>`}</div></article>`).join(''):'<div class="ielts-empty"><strong>Catalog đã xác minh nhưng chưa có pack được phát hành</strong><p>Nội dung draft không xuất hiện cho đến khi có quyền và human approval hợp lệ.</p></div>';}
function lessonCardsMarkup(lessons){return lessons.length?lessons.map(row=>`<article class="v10-content-card"><div><span>${escape(row.difficulty)} · ${escape(row.skill)} · offline</span><h3>${escape(row.title)}</h3><p>${escape(row.learningObjective)}</p><small>${row.estimatedMinutes} phút · revision ${row.contentRevision}</small></div><div class="v10-content-actions"><button class="primary-button" data-v10-open-content="${escape(row.id)}">Mở bài đã cài</button></div></article>`).join(''):'<p class="muted">Chưa có bài đã cài.</p>';}
async function discoverMarkup(){let catalog=await browseContentPacks();if(catalog.state==='no-valid-catalog'){try{await refreshContentCatalog();catalog=await browseContentPacks();}catch(error){console.warn('[content catalog]',error);}}
  const lessons=await listContentLessons();const stateLabel=catalog.state==='verified'?'Catalog đã xác minh':catalog.state==='expired-last-known-good'?'Last-known-good đã hết hạn · chỉ bài đã cài':catalog.state==='no-valid-catalog'?'Chưa có catalog hợp lệ':'Đang dùng last-known-good';return`<section class="v10-hub-hero"><div><p class="eyebrow">SIGNED REMOTE CONTENT</p><h3>${escape(stateLabel)}</h3><p>Pack chỉ được kích hoạt sau khi chữ ký, quyền, review và mọi asset digest đều hợp lệ. Cache có thể tải lại; tiến độ ở IndexedDB.</p></div><button class="secondary-button" data-v10-refresh-catalog>Làm mới catalog</button></section><p id="v10ContentStatus" class="v10-content-status" role="status" aria-live="polite">${escape(catalog.catalog?`Revision ${catalog.catalog.revision} · sequence ${catalog.catalog.sequence}${catalog.state==='expired-last-known-good'?' · hết hạn, không thể cài/cập nhật':''}`:'Kết nối mạng và thử lại; dữ liệu học hiện có không bị xóa.')}</p><section><div class="section-heading"><div><p class="eyebrow">PACK KHẢ DỤNG</p><h3>Cài theo hành động của bạn</h3></div></div><div id="v10ContentPacks" class="v10-content-grid">${packCardsMarkup(catalog.packs)}</div></section><section><div class="section-heading"><div><p class="eyebrow">ĐÃ CÀI · OFFLINE</p><h3>Bài học có exact immutable target</h3></div></div><div id="v10ContentCards" class="v10-content-grid">${lessonCardsMarkup(lessons)}</div></section>`;}

async function videosMarkup(){const [cached,media,fallback]=await Promise.all([listCachedTranscripts(),listIeltsRecords(IELTS_STORE_NAMES.mediaSources,{sortBy:'updatedAt'}).catch(()=>[]),phase5FallbackMarkup()]);const byVideo=new Map();for(const row of [...cached,...media]){const key=row.videoId||row.id;if(!byVideo.has(key))byVideo.set(key,row);}const rows=[...byVideo.values()];return`<section class="v10-hub-hero"><div><p class="eyebrow">PASTE URL → LEARN</p><h3>Dán YouTube URL và học câu đầu càng sớm càng tốt</h3><p>Ưu tiên transcript đã cache, sau đó luôn thử caption trước. Local/Gemini không tự bật; import luôn tạo revision riêng tư chưa xác minh.</p></div></section><form id="v10VideoForm" class="v10-video-form"><input name="url" type="url" required placeholder="https://www.youtube.com/watch?v=..."><label>Bắt đầu (phút)<input name="startMinutes" type="number" min="0" value="0"></label><button class="primary-button" ${videoBusy?'disabled':''}>${videoBusy?'Đang chuẩn bị…':'Dán URL và học'}</button></form><div id="v10VideoStatus" class="v10-video-status" aria-live="polite"></div>${fallback}<section><div class="section-heading"><div><p class="eyebrow">VIDEO ĐÃ HỌC</p><h3>Tiếp tục đúng câu đang dở</h3></div></div><div class="v10-video-grid">${rows.map(row=>`<button data-v10-cached-video="${escape(row.videoId||'')}" data-v10-cached-id="${escape(row.id||'')}"><strong>${escape(row.title||row.videoId||'Video')}</strong><span>${row.segments?.length||0} câu đã cache</span><small>${escape(row.provider||row.transcriptStatus||'media')}</small></button>`).join('')||'<p class="muted">Chưa có video.</p>'}</div></section>`;}

async function skillsMarkup(){const [errors,sets,readings,labs]=await Promise.all([listIeltsRecords(IELTS_STORE_NAMES.errors,{sortBy:'lastSeenAt'}).catch(()=>[]),listIeltsRecords(IELTS_STORE_NAMES.lexicalSets).catch(()=>[]),listIeltsRecords(IELTS_STORE_NAMES.readingPassages).catch(()=>[]),listIeltsRecords(IELTS_STORE_NAMES.labItems).catch(()=>[])]);const openErrors=errors.filter(row=>!['resolved','ignored'].includes(row.status));const categories=new Map();for(const row of openErrors)categories.set(row.category,(categories.get(row.category)||0)+Number(row.occurrenceCount||1));return`<section class="v10-hub-hero"><div><p class="eyebrow">ERROR-DRIVEN LEARNING</p><h3>Lỗi không biến mất sau khi đóng bài</h3><p>Error Notebook liên kết về Kho từ, câu nguồn và FSRS evidence đúng kỹ năng.</p></div><strong>${openErrors.length} lỗi mở</strong></section><div class="v10-skill-metrics"><button data-v10-legacy-tab="errors"><strong>${openErrors.length}</strong><span>Error Notebook</span></button><button data-v10-legacy-tab="lexical"><strong>${sets.filter(row=>row.status==='active').length}</strong><span>Lexical Sets</span></button><button data-v10-legacy-tab="reading"><strong>${readings.filter(row=>row.status==='verified').length}</strong><span>Reading đã duyệt</span></button><button data-v10-legacy-tab="paraphrase"><strong>${labs.filter(row=>row.status==='verified').length}</strong><span>Paraphrase đã duyệt</span></button></div><section class="v10-error-map"><h3>Mẫu lỗi nổi bật</h3>${[...categories.entries()].sort((a,b)=>b[1]-a[1]).slice(0,8).map(([category,count])=>`<div><strong>${escape(category)}</strong><span>${count} lần</span></div>`).join('')||'<p class="muted">Chưa đủ lỗi để tạo bản đồ.</p>'}</section><div class="v10-hub-tools"><button class="primary-button" data-v10-legacy-tab="errors">Mở Error Notebook</button><button class="secondary-button" data-v10-legacy-tab="lexical">Mở Lexical Sets</button></div>`;}

async function render(){const host=panel();if(!host)return;const currentGeneration=++renderGeneration;const expectedTab=activeTab;const { getSelectedIeltsTrack }=await import('./ielts-persistence.js');const currentTrack=(await getSelectedIeltsTrack().catch(()=>null))||'academic';host.innerHTML=shell('<div class="v10-loading">Đang chuẩn bị…</div>',currentTrack);let content;try{content=expectedTab==='videos'?await videosMarkup():expectedTab==='skills'?await skillsMarkup():await discoverMarkup();}catch(error){content=`<div class="ielts-empty"><strong>Không tải được IELTS Hub</strong><p>${escape(error.message)}</p></div>`;}if(currentGeneration!==renderGeneration||expectedTab!==activeTab)return;host.innerHTML=shell(content,currentTrack);}
export function shouldRefreshIeltsHub(tab){return tab==='discover';}
async function refreshIeltsHub(){if(shouldRefreshIeltsHub(activeTab))await render();}

function filterContent(){const level=document.querySelector('#v10ContentLevel')?.value||'',topic=document.querySelector('#v10ContentTopic')?.value||'',skill=document.querySelector('#v10ContentSkill')?.value||'';document.querySelectorAll('.v10-content-card').forEach(card=>{const visible=(!level||card.dataset.contentLevel===level)&&(!topic||card.dataset.contentTopic===topic)&&(!skill||String(card.dataset.contentSkills).split(',').includes(skill));card.hidden=!visible;});}
async function handleVideoSubmit(form){if(videoBusy)return;const data=new FormData(form),url=String(data.get('url')||''),videoId=parseYouTubeVideoId(url);if(!videoId){toast('URL YouTube không hợp lệ.');return;}const {policy,sharing}=await phase5RequestPolicy(dialog());videoBusy=true;await render();const status=document.querySelector('#v10VideoStatus');if(status)status.innerHTML='<p>✓ Đã tải player metadata</p><p>● Đang tìm caption trước…</p>';try{const startSeconds=Math.max(0,Number(data.get('startMinutes')||0)*60);const row=await resolveTranscriptWithFallback({url,startSeconds,firstChunkSeconds:60,policy,sharing,onProgress:progress=>{const current=document.querySelector('#v10VideoStatus');if(current)current.textContent=`Resolver: ${progress.status}`;}});const currentStatus=document.querySelector('#v10VideoStatus');if(currentStatus)currentStatus.innerHTML=`<p>✓ Có ${row.segments.length} câu đầu từ ${escape(row.provider)}</p><p>● Kết quả fallback là riêng tư và chưa xác minh</p>`;await openVideoLoop(row);if(row.provider==='caption-resolver-v2')void continueTranscriptProgressively({url,startSeconds:startSeconds+60,totalSeconds:180,chunkSeconds:60}).catch(error=>console.warn('[progressive transcript]',error));}catch(error){const currentStatus=document.querySelector('#v10VideoStatus');if(currentStatus)currentStatus.innerHTML=`<p class="error">${escape(error.code||'UNKNOWN')}: ${escape(error.message)}</p><p>${escape(phase5RecoveryMessage(error))}</p>`;}finally{videoBusy=false;}}

async function handleClick(event){
  if(event.target.closest('[data-v10-ielts-close]')){dialog()?.close();return;}
  const trackBtn=event.target.closest?.('[data-ielts-track]');if(trackBtn){const track=trackBtn.dataset.ieltsTrack;const { setSelectedIeltsTrack }=await import('./ielts-persistence.js');await setSelectedIeltsTrack(track).catch(()=>{});await render();return;}
  const tab=event.target.closest('[data-v10-ielts-tab]');if(tab){activeTab=tab.dataset.v10IeltsTab;await render();return;}
  const fallback=await handlePhase5FallbackClick(event.target,dialog());if(fallback.handled){if(fallback.refresh)await render();if(fallback.row)await openVideoLoop(fallback.row);return;}
  const legacy=event.target.closest('[data-v10-legacy-tab]');if(legacy){dialog()?.close();openLegacyTab(legacy.dataset.v10LegacyTab);return;}
  if(event.target.closest('[data-v10-refresh-catalog]')){try{await refreshContentCatalog();await render();toast('Đã làm mới content catalog.');}catch(error){toast(error.message);}return;}
  const open=event.target.closest('[data-v10-open-content]');if(open){try{await openContentLesson(open.dataset.v10OpenContent);}catch(error){toast(error.message);}return;}
  const install=event.target.closest('[data-v10-install-pack]');if(install){install.disabled=true;const status=document.querySelector('#v10ContentStatus');if(status)status.textContent='Đang tải và xác minh pack…';try{await installContentPack(install.dataset.v10InstallPack);toast('Pack đã được xác minh và cài offline.');await render();}catch(error){if(status)status.textContent=`${error.code||'PACK_INSTALL_FAILED'}: ${error.message}`;toast(error.message);install.disabled=false;}return;}
  const remove=event.target.closest('[data-v10-delete-pack]');if(remove){if(!globalThis.confirm?.('Xóa asset offline của pack? Tiến độ, attempt, receipt, từ đã lưu và Error Repository sẽ được giữ.'))return;remove.disabled=true;try{await deleteContentPack(remove.dataset.v10DeletePack);toast('Đã xóa asset pack; tiến độ được giữ.');await render();}catch(error){toast(error.message);remove.disabled=false;}return;}
  const cached=event.target.closest('[data-v10-cached-video]');if(cached){const rows=await listCachedTranscripts(cached.dataset.v10CachedVideo);const row=rows.find(item=>item.id===cached.dataset.v10CachedId)||rows[0];if(row)await openVideoLoop(row);}
}

function ensureDialog(){if(dialog())return;const node=document.createElement('dialog');node.id='v10IeltsHubDialog';node.className='v10-ielts-dialog';node.innerHTML='<div id="v10IeltsHubPanel"></div>';node.addEventListener('click',event=>void handleClick(event));node.addEventListener('change',event=>{if(event.target.matches('#v10ContentLevel,#v10ContentTopic,#v10ContentSkill'))filterContent();else void handlePhase5FallbackChange(event.target);});node.addEventListener('submit',event=>{if(event.target.id==='v10VideoForm'){event.preventDefault();void handleVideoSubmit(event.target);}});document.body.append(node);}
export async function openIeltsHub(tab='discover'){activeTab=['discover','videos','skills'].includes(tab)?tab:'discover';ensureDialog();if(!dialog().open)dialog().showModal();await render();}

function launcherHandler(event){if(bypassLegacyLauncher)return;event.preventDefault();event.stopImmediatePropagation();void openIeltsHub('discover');}
function bindLegacyLaunchers(){for(const launcher of document.querySelectorAll('#openIeltsLabButton,#openIeltsLabMobile')){if(boundLaunchers.has(launcher))continue;boundLaunchers.add(launcher);launcher.addEventListener('click',launcherHandler,true);}}
function interceptLegacyLauncher(){bindLegacyLaunchers();document.addEventListener('vocab:ielts-launcher-mounted',bindLegacyLaunchers);}
export function mountIeltsHubV2(){ensureDialog();interceptLegacyLauncher();globalThis.addEventListener('vocab:v10-open-ielts-hub',event=>void openIeltsHub(event.detail?.tab||'discover'));globalThis.VocabMasterIeltsHub={open:openIeltsHub,refresh:refreshIeltsHub,openLegacyTab};}
