import { sanitizeCardInput, cardIdentityKey, normalizeText } from './learning.js';
import { applyFsrsRating } from './fsrs-scheduler.js';
import { persistCard, persistReviewResult } from './persistence.js';
import {
  IELTS_STORE_NAMES,
  createIeltsId,
  createErrorRecord,
  normalizeComparableText,
  resolveIeltsEvidence,
  sanitizeLexicalSet,
  validateLexicalSet,
  sanitizeLabItem,
  validateLabItem,
  sanitizeReadingPassage,
  validateReadingPassage,
  parseYouTubeUrl,
  sanitizeTranscriptSegment,
  validateTranscriptSegments,
  splitTranscriptSegment,
  mergeTranscriptSegments,
  diffWords,
  planMediaSession,
  sanitizeMediaSource,
  sanitizeMediaAttempt
} from './ielts-domain.js';
import {
  initializeIeltsPersistence,
  listIeltsRecords,
  getIeltsRecord,
  saveIeltsRecord,
  deleteIeltsRecord,
  upsertErrorRecord,
  setErrorStatus,
  saveLabItem,
  saveReadingPassage,
  saveReadingAttempt,
  saveMediaSource,
  findMediaByVideoId,
  saveTranscriptionJob,
  replaceTranscriptSegments,
  listTranscriptSegments,
  saveMediaAttempt,
  saveMediaProgress,
  getMediaProgress,
  downloadIeltsBackup,
  validateIeltsBackup,
  restoreIeltsBackup
} from './ielts-persistence.js';
import { CURATED_LEXICAL_SETS, CURATED_PARAPHRASE_ITEMS, CURATED_READING_PASSAGES } from './ielts-content.js';
import { YouTubeSegmentPlayer } from './ielts-media-player.js';

const SESSION_KEY='vocab-master-gemini-key';
const TABS=Object.freeze([
  ['overview','Tổng quan'],['errors','Error Notebook'],['lexical','Lexical Sets'],['paraphrase','Paraphrase'],['reading','Reading'],['media','Media Lab']
]);
const state={
  mounted:false,tab:'overview',busy:false,status:'',statusKind:'info',selectedErrorId:null,selectedSetId:null,selectedLabId:null,selectedReadingId:null,
  mediaSourceId:null,segments:[],currentSegmentId:null,player:null,recording:null,recordingUrl:null,retellRecognition:null,dictationRevealed:false,pendingCoreError:null,processedErrorSignatures:new Set()
};

const $=(selector,root=document)=>root.querySelector(selector);
const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));}
function escapeAttr(value){return escapeHtml(value).replace(/`/g,'&#96;');}
function formatTime(ms=0){const seconds=Math.max(0,Number(ms||0))/1000;const minutes=Math.floor(seconds/60);return`${String(minutes).padStart(2,'0')}:${(seconds%60).toFixed(1).padStart(4,'0')}`;}
function coreState(){return globalThis.VocabMasterApp?.getState?.()||{cards:[],settings:{},fsrsConfig:{},metrics:{}};}
function activeCards(){return(coreState().cards||[]).filter(card=>!card.suspendedAt&&!card.archivedAt);}
function findCard(id){return(coreState().cards||[]).find(card=>card.id===id)||null;}
function dispatchCards(cards){const current=coreState();globalThis.dispatchEvent(new CustomEvent('vocab:external-change',{detail:{reason:'ielts-lab',state:{...current,cards}}}));}
function showStatus(message,kind='info'){state.status=String(message||'');state.statusKind=kind;const node=$('#ieltsLabStatus');if(node){node.className=`ielts-status ${kind}`;node.textContent=state.status;}}
function setBusy(value,message=''){state.busy=Boolean(value);const dialog=$('#ieltsLabDialog');if(dialog)$$('button, input, textarea, select',dialog).forEach(control=>{if(control.dataset.keepEnabled!=='true')control.disabled=state.busy;});if(message)showStatus(message,'loading');}
function cardOptions(selected=''){return`<option value="">Không liên kết thẻ</option>${activeCards().map(card=>`<option value="${escapeAttr(card.id)}" ${card.id===selected?'selected':''}>${escapeHtml(card.front)} — ${escapeHtml(card.back)}</option>`).join('')}`;}
function currentMediaSegment(){return state.segments.find(segment=>segment.id===state.currentSegmentId)||state.segments[0]||null;}

async function callIeltsApi(path,payload,{timeoutMs=130_000}={}){
  const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeoutMs);const current=coreState();const headers={'content-type':'application/json','x-gemini-model':current.settings?.model||'gemini-3.6-flash'};const key=sessionStorage.getItem(SESSION_KEY)||'';if(key)headers['x-gemini-key']=key;
  try{const response=await fetch(path,{method:'POST',headers,body:JSON.stringify(payload),signal:controller.signal});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`IELTS API lỗi HTTP ${response.status}`);return data;}
  catch(error){if(error.name==='AbortError')throw new Error('AI xử lý quá lâu. Dữ liệu cục bộ vẫn được giữ để thử lại.');throw error;}finally{clearTimeout(timer);}
}

async function seedCuratedContent(){
  const existingSets=new Set((await listIeltsRecords(IELTS_STORE_NAMES.lexicalSets)).map(row=>row.id));
  for(const item of CURATED_LEXICAL_SETS)if(!existingSets.has(item.id))await saveIeltsRecord(IELTS_STORE_NAMES.lexicalSets,{...sanitizeLexicalSet(item),suggestedEntries:structuredClone(item.suggestedEntries||[])},'ielts-curated-set-seeded');
  const existingLabs=new Set((await listIeltsRecords(IELTS_STORE_NAMES.labItems)).map(row=>row.id));
  for(const item of CURATED_PARAPHRASE_ITEMS)if(!existingLabs.has(item.id))await saveLabItem(item);
  const existingReadings=new Set((await listIeltsRecords(IELTS_STORE_NAMES.readingPassages)).map(row=>row.id));
  for(const item of CURATED_READING_PASSAGES)if(!existingReadings.has(item.id))await saveReadingPassage(item);
}

function ensureStyles(){if(document.querySelector('link[href="/ielts-lab.css"]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href='/ielts-lab.css';document.head.append(link);}
function ensureLauncher(){
  if($('#openIeltsLabButton'))return;
  const button=document.createElement('button');button.type='button';button.id='openIeltsLabButton';button.className='ielts-launcher';button.innerHTML='<span aria-hidden="true">🎓</span><span><strong>IELTS Lab</strong><small>Lỗi · Lexical · Reading · Media</small></span>';
  const sidebar=$('.sidebar-widget');sidebar?.insertAdjacentElement('afterend',button);
  const mobile=document.createElement('button');mobile.type='button';mobile.id='openIeltsLabMobile';mobile.className='ielts-mobile-launcher';mobile.setAttribute('aria-label','Mở IELTS Lab');mobile.textContent='🎓';$('.top-stats')?.prepend(mobile);
  button.addEventListener('click',openLab);mobile.addEventListener('click',openLab);
}
function ensureDialog(){
  if($('#ieltsLabDialog'))return;
  const dialog=document.createElement('dialog');dialog.id='ieltsLabDialog';dialog.className='ielts-lab-dialog';dialog.setAttribute('aria-labelledby','ieltsLabTitle');dialog.innerHTML=`
    <div class="ielts-shell">
      <header class="ielts-header"><div><p class="ielts-eyebrow">VOCAB MASTER · IELTS LEARNING LOOP</p><h2 id="ieltsLabTitle">IELTS Lab</h2><p>Hoạt động IELTS chỉ tạo FSRS evidence khi kiểm tra độc lập, có mục tiêu và đã xác minh.</p></div><button type="button" class="ielts-icon-button" data-ielts-action="close" aria-label="Đóng IELTS Lab">×</button></header>
      <nav class="ielts-tabs" role="tablist" aria-label="Các khu vực IELTS">${TABS.map(([id,label])=>`<button type="button" role="tab" data-ielts-tab="${id}" aria-selected="${id==='overview'}">${label}</button>`).join('')}</nav>
      <div id="ieltsLabStatus" class="ielts-status" aria-live="polite"></div>
      <main id="ieltsLabPanel" class="ielts-panel" tabindex="-1"></main>
      <footer class="ielts-footer"><span>Dữ liệu IELTS được lưu trong IndexedDB riêng và có backup riêng.</span><div><button type="button" class="secondary-button" data-ielts-action="backup">Tải backup IELTS</button><label class="secondary-button ielts-file-label">Khôi phục<input type="file" accept="application/json" data-ielts-restore hidden></label></div></footer>
    </div>`;
  document.body.append(dialog);dialog.addEventListener('click',handleDialogClick);dialog.addEventListener('submit',handleDialogSubmit);dialog.addEventListener('change',handleDialogChange);dialog.addEventListener('close',()=>{stopRecording();state.player?.pause();});
}

async function openLab(tab=state.tab){state.tab=tab;const dialog=$('#ieltsLabDialog');if(!dialog)return;if(!dialog.open)dialog.showModal();await renderLab();$(`[data-ielts-tab="${state.tab}"]`,dialog)?.focus();}
function closeLab(){const dialog=$('#ieltsLabDialog');if(dialog?.open)dialog.close();}

async function renderLab(){
  const panel=$('#ieltsLabPanel');if(!panel)return;
  $$('[data-ielts-tab]').forEach(button=>button.setAttribute('aria-selected',String(button.dataset.ieltsTab===state.tab)));
  panel.setAttribute('aria-busy','true');
  try{
    if(state.tab==='overview')await renderOverview(panel);
    else if(state.tab==='errors')await renderErrors(panel);
    else if(state.tab==='lexical')await renderLexical(panel);
    else if(state.tab==='paraphrase')await renderParaphrase(panel);
    else if(state.tab==='reading')await renderReading(panel);
    else if(state.tab==='media')await renderMedia(panel);
  }catch(error){panel.innerHTML=`<div class="ielts-empty"><strong>Không tải được khu vực này</strong><p>${escapeHtml(error.message)}</p><button class="primary-button" data-ielts-action="retry-render">Thử lại</button></div>`;showStatus(error.message,'error');}
  finally{panel.setAttribute('aria-busy','false');}
}

async function renderOverview(panel){
  const [errors,sets,labs,readings,media]=await Promise.all([
    listIeltsRecords(IELTS_STORE_NAMES.errors),listIeltsRecords(IELTS_STORE_NAMES.lexicalSets),listIeltsRecords(IELTS_STORE_NAMES.labItems),listIeltsRecords(IELTS_STORE_NAMES.readingPassages),listIeltsRecords(IELTS_STORE_NAMES.mediaSources)
  ]);
  const openErrors=errors.filter(row=>!['resolved','ignored'].includes(row.status));
  panel.innerHTML=`<section class="ielts-overview-grid">
    <button class="ielts-metric" data-ielts-go="errors"><strong>${openErrors.length}</strong><span>Lỗi đang theo dõi</span><small>${errors.reduce((sum,row)=>sum+Number(row.occurrenceCount||1),0)} lần xuất hiện</small></button>
    <button class="ielts-metric" data-ielts-go="lexical"><strong>${sets.filter(row=>row.status==='active').length}</strong><span>Lexical sets</span><small>${sets.reduce((sum,row)=>sum+(row.itemIds?.length||0),0)} thẻ đã liên kết</small></button>
    <button class="ielts-metric" data-ielts-go="paraphrase"><strong>${labs.filter(row=>row.status==='verified').length}</strong><span>Paraphrase đã duyệt</span><small>${labs.filter(row=>row.status==='draft').length} bản nháp AI</small></button>
    <button class="ielts-metric" data-ielts-go="reading"><strong>${readings.filter(row=>row.status==='verified').length}</strong><span>Reading micro-practice</span><small>Evidence bắt buộc</small></button>
    <button class="ielts-metric" data-ielts-go="media"><strong>${media.length}</strong><span>Video đang học</span><small>Phiên mặc định 20 phút</small></button>
  </section>
  <section class="ielts-card"><h3>Vòng lặp học tập đã khóa</h3><ol class="ielts-flow"><li>Nội dung thật hoặc curated</li><li>Hoạt động có mục tiêu</li><li>Lỗi có learner response và source</li><li>Người học xác nhận card/target</li><li>Evidence gateway quyết định FSRS</li></ol></section>
  <section class="ielts-card"><h3>Ranh giới an toàn</h3><div class="ielts-rule-grid"><p><b>Shadowing:</b> coaching-only, không tăng FSRS.</p><p><b>Retell:</b> chỉ target chọn trước và dùng đúng mới tạo production evidence.</p><p><b>AI content:</b> luôn là draft trước khi xác nhận.</p><p><b>YouTube:</b> phát qua iframe; ứng dụng không tải hoặc tách audio/video.</p></div></section>`;
}

async function renderErrors(panel){
  const errors=await listIeltsRecords(IELTS_STORE_NAMES.errors,{sortBy:'lastSeenAt'});if(!state.selectedErrorId&&errors[0])state.selectedErrorId=errors[0].id;const selected=errors.find(row=>row.id===state.selectedErrorId)||null;
  panel.innerHTML=`<div class="ielts-two-column"><section class="ielts-card"><div class="ielts-section-head"><div><h3>Personal Error Notebook</h3><p>Lỗi trùng được gộp theo category, target, learner response và expected response.</p></div><select id="errorStatusFilter" aria-label="Lọc trạng thái"><option value="all">Tất cả</option>${['open','practicing','monitoring','resolved','ignored'].map(value=>`<option value="${value}">${value}</option>`).join('')}</select></div>
    <div class="ielts-list" id="errorList">${errors.length?errors.map(row=>`<button class="ielts-list-row ${row.id===selected?.id?'active':''}" data-error-id="${escapeAttr(row.id)}" data-error-status="${escapeAttr(row.status)}"><span><strong>${escapeHtml(row.correction||row.expectedResponse||row.category)}</strong><small>${escapeHtml(row.learnerResponse||'Không có câu trả lời')} → ${escapeHtml(row.expectedResponse||row.correction||'')}</small></span><span class="ielts-count">×${Number(row.occurrenceCount||1)}</span><em>${escapeHtml(row.status)}</em></button>`).join(''):'<div class="ielts-empty"><strong>Chưa có lỗi</strong><p>Lỗi từ bài hiện tại, Paraphrase, Reading và Media sẽ xuất hiện ở đây.</p></div>'}</div>
    <details class="ielts-manual-error"><summary>Thêm lỗi thủ công</summary><form id="manualErrorForm" class="ielts-form"><label>Loại lỗi<select name="category"><option>meaning</option><option>spelling</option><option>collocation</option><option>grammar</option><option>lexical-gap</option><option>other</option></select></label><label>Câu trả lời của tôi<textarea name="learnerResponse" required></textarea></label><label>Cách sửa<textarea name="expectedResponse" required></textarea></label><label>Giải thích<textarea name="explanation"></textarea></label><label>Liên kết card<select name="linkedCardId">${cardOptions()}</select></label><button class="primary-button">Lưu lỗi</button></form></details></section>
    <section class="ielts-card" id="errorDetail">${selected?errorDetailMarkup(selected):'<div class="ielts-empty"><p>Chọn một lỗi để xem chi tiết.</p></div>'}</section></div>`;
}
function errorDetailMarkup(row){return`<div class="ielts-section-head"><div><p class="ielts-eyebrow">${escapeHtml(row.category)} · ${escapeHtml(row.sourceRef?.type||'manual')}</p><h3>${escapeHtml(row.correction||row.expectedResponse||'Lỗi')}</h3></div><span class="ielts-count large">×${Number(row.occurrenceCount||1)}</span></div>
  <dl class="ielts-definition"><dt>Prompt/source</dt><dd>${escapeHtml(row.prompt||row.sourceRef?.context||'—')}</dd><dt>Learner response</dt><dd>${escapeHtml(row.learnerResponse||'—')}</dd><dt>Expected response</dt><dd>${escapeHtml(row.expectedResponse||'—')}</dd><dt>Correction</dt><dd>${escapeHtml(row.correction||'—')}</dd><dt>Giải thích</dt><dd>${escapeHtml(row.explanation||'—')}</dd><dt>Source</dt><dd>${escapeHtml(row.sourceRef?.title||row.sourceRef?.sourceId||row.sourceRef?.type||'—')}</dd><dt>Linked cards</dt><dd>${(row.linkedCardIds||[]).map(id=>escapeHtml(findCard(id)?.front||`Thẻ đã xóa: ${id}`)).join(', ')||'Chưa liên kết'}</dd></dl>
  <form id="errorCorrectionForm" class="ielts-form compact" data-error="${escapeAttr(row.id)}"><label>Kiểm tra sửa lỗi độc lập<input name="answer" autocomplete="off" required placeholder="Tự nhập đáp án đúng, không nhìn phần trên" /></label><label>Kỹ năng<select name="skill"><option value="recall">Recall</option><option value="listening">Listening</option><option value="collocation">Collocation</option><option value="production">Production</option><option value="recognition">Recognition</option></select></label><button class="primary-button">Kiểm tra và ghi evidence</button></form>
  <div class="ielts-actions"><button class="secondary-button" data-error-status-set="practicing" data-error-target="${escapeAttr(row.id)}">Đang luyện</button><button class="secondary-button" data-error-status-set="monitoring" data-error-target="${escapeAttr(row.id)}">Theo dõi</button><button class="secondary-button" data-error-status-set="resolved" data-error-target="${escapeAttr(row.id)}">Đã xử lý</button><button class="text-button" data-error-status-set="ignored" data-error-target="${escapeAttr(row.id)}">Bỏ qua</button></div>`;}

async function renderLexical(panel){
  const sets=await listIeltsRecords(IELTS_STORE_NAMES.lexicalSets);if(!state.selectedSetId&&sets[0])state.selectedSetId=sets[0].id;const selected=sets.find(row=>row.id===state.selectedSetId)||null;
  panel.innerHTML=`<div class="ielts-two-column"><section class="ielts-card"><div class="ielts-section-head"><div><h3>IELTS Lexical Sets</h3><p>Nhóm theo chức năng giao tiếp, register, context và common mistakes.</p></div></div><div class="ielts-list">${sets.map(row=>`<button class="ielts-list-row ${row.id===selected?.id?'active':''}" data-set-id="${escapeAttr(row.id)}"><span><strong>${escapeHtml(row.name)}</strong><small>${escapeHtml((row.functions||[]).join(' · '))}</small></span><em>${row.itemIds?.length||0} thẻ</em></button>`).join('')}</div></section><section class="ielts-card">${selected?lexicalSetMarkup(selected):'<div class="ielts-empty">Chọn một set.</div>'}</section></div>`;
}
function lexicalSetMarkup(set){
  const validation=validateLexicalSet(set);const entries=Array.isArray(set.suggestedEntries)?set.suggestedEntries:[];
  return`<div class="ielts-section-head"><div><p class="ielts-eyebrow">${escapeHtml(set.level)} · ${escapeHtml(set.register)}</p><h3>${escapeHtml(set.name)}</h3><p>${escapeHtml(set.description)}</p></div><span class="ielts-pill ${validation.valid?'good':'warning'}">${validation.valid?'Đủ metadata':'Thiếu metadata'}</span></div>
  <div class="ielts-meta-grid"><p><b>Functions</b>${escapeHtml((set.functions||[]).join(', '))}</p><p><b>Production task</b>${escapeHtml(set.productionTask||'—')}</p><p class="full"><b>Common mistakes</b>${(set.commonMistakes||[]).map(item=>`<span>• ${escapeHtml(item)}</span>`).join('')||'—'}</p></div>
  <h4>Mục curated</h4><div class="ielts-entry-list">${entries.map((entry,index)=>{const linked=(set.itemIds||[]).map(findCard).filter(Boolean).find(card=>normalizeComparableText(card.front)===normalizeComparableText(entry.term));return`<article class="ielts-entry"><div><strong>${escapeHtml(entry.term)}</strong><p>${escapeHtml(entry.meaning)}</p><small>${escapeHtml(entry.context)}</small><details><summary>Usage constraints</summary><p><b>Function:</b> ${escapeHtml(entry.function)}</p><p><b>Register:</b> ${escapeHtml(entry.register)}</p><p><b>Common mistake:</b> ${escapeHtml(entry.commonMistake)}</p><p><b>Production:</b> ${escapeHtml(entry.productionPrompt)}</p></details></div>${linked?`<span class="ielts-pill good">Trong Library</span>`:`<button class="secondary-button" data-add-set-entry="${index}" data-set-target="${escapeAttr(set.id)}">Thêm vào Library</button>`}</article>`;}).join('')}</div>
  <div class="ielts-actions"><button class="primary-button" data-set-production="${escapeAttr(set.id)}" ${set.itemIds?.length<3?'disabled title="Cần ít nhất 3 card trong Library"':''}>Production task</button></div>`;
}

async function renderParaphrase(panel){
  const items=await listIeltsRecords(IELTS_STORE_NAMES.labItems);if(!state.selectedLabId&&items[0])state.selectedLabId=items[0].id;const selected=items.find(row=>row.id===state.selectedLabId)||null;
  panel.innerHTML=`<div class="ielts-two-column"><section class="ielts-card"><div class="ielts-section-head"><div><h3>Paraphrase & Distractor Lab</h3><p>AI chỉ tạo draft. Mỗi option phải có rationale và đúng một đáp án.</p></div><button class="primary-button" data-ielts-action="new-paraphrase">Tạo draft</button></div><div class="ielts-list">${items.map(row=>`<button class="ielts-list-row ${row.id===selected?.id?'active':''}" data-lab-id="${escapeAttr(row.id)}"><span><strong>${escapeHtml(row.context||row.prompt)}</strong><small>${escapeHtml(row.kind)}</small></span><em>${escapeHtml(row.status)}</em></button>`).join('')}</div></section><section class="ielts-card">${selected?labItemMarkup(selected):'<div class="ielts-empty">Chọn một item.</div>'}</section></div>`;
}
function labItemMarkup(item){const validation=validateLabItem(item);return`<div class="ielts-section-head"><div><p class="ielts-eyebrow">${escapeHtml(item.kind)} · ${escapeHtml(item.status)}</p><h3>${escapeHtml(item.prompt)}</h3><p>${escapeHtml(item.context)}</p></div><span class="ielts-pill ${validation.valid?'good':'warning'}">${validation.valid?'Schema hợp lệ':`${validation.errors.length} lỗi`}</span></div>
  ${item.status==='draft'?`<form id="labEditorForm" class="ielts-form" data-lab="${escapeAttr(item.id)}"><label>Prompt<textarea name="prompt" required>${escapeHtml(item.prompt)}</textarea></label><label>Context<textarea name="context" required>${escapeHtml(item.context)}</textarea></label><div class="ielts-options-editor">${(item.options||[]).map((option,index)=>`<fieldset><legend>Option ${index+1}</legend><input name="optionText-${index}" value="${escapeAttr(option.text)}" required><textarea name="optionRationale-${index}" required>${escapeHtml(option.rationale)}</textarea><label><input type="radio" name="correctIndex" value="${index}" ${option.correct?'checked':''}> Đáp án đúng</label></fieldset>`).join('')}</div><div class="ielts-actions"><button class="primary-button" name="intent" value="verify">Lưu và xác nhận</button><button class="secondary-button" name="intent" value="draft">Lưu draft</button><button type="button" class="text-button danger" data-delete-lab="${escapeAttr(item.id)}">Xóa</button></div></form>`:`<form id="labPracticeForm" class="ielts-form" data-lab="${escapeAttr(item.id)}"><fieldset><legend>${escapeHtml(item.prompt)}</legend>${(item.options||[]).map(option=>`<label class="ielts-choice"><input type="radio" name="answer" value="${escapeAttr(option.id)}" required><span>${escapeHtml(option.text)}</span></label>`).join('')}</fieldset><button class="primary-button">Kiểm tra</button></form><div id="labFeedback"></div>`}`;}
function paraphraseDraftMarkup(){return`<form id="paraphraseDraftForm" class="ielts-form"><label>Loại<select name="kind"><option value="paraphrase">Paraphrase</option><option value="distractor">Distractor</option></select></label><label>Câu/ý nguồn<textarea name="sourceText" required placeholder="Dán câu cần tạo bài luyện"></textarea></label><label>Context<textarea name="context" placeholder="Ngữ cảnh để khóa đúng sense"></textarea></label><label>Liên kết card<select name="cardId">${cardOptions()}</select></label><button class="primary-button">Tạo AI draft</button></form>`;}

async function renderReading(panel){
  const passages=await listIeltsRecords(IELTS_STORE_NAMES.readingPassages);if(!state.selectedReadingId&&passages[0])state.selectedReadingId=passages[0].id;const selected=passages.find(row=>row.id===state.selectedReadingId)||null;
  panel.innerHTML=`<div class="ielts-two-column reading-layout"><section class="ielts-card"><div class="ielts-section-head"><div><h3>Reading Micro-practice</h3><p>Passage ngắn, một micro-skill, evidence bắt buộc và giải thích từng distractor.</p></div><button class="primary-button" data-ielts-action="new-reading">Tạo draft</button></div><div class="ielts-list">${passages.map(row=>`<button class="ielts-list-row ${row.id===selected?.id?'active':''}" data-reading-id="${escapeAttr(row.id)}"><span><strong>${escapeHtml(row.title)}</strong><small>${escapeHtml(row.microSkill)}</small></span><em>${escapeHtml(row.status)}</em></button>`).join('')}</div></section><section class="ielts-card">${selected?readingMarkup(selected):'<div class="ielts-empty">Chọn một passage.</div>'}</section></div>`;
}
function readingMarkup(passage){const validation=validateReadingPassage(passage);return`<div class="ielts-section-head"><div><p class="ielts-eyebrow">${escapeHtml(passage.microSkill)} · ${escapeHtml(passage.status)}</p><h3>${escapeHtml(passage.title)}</h3></div><span class="ielts-pill ${validation.valid?'good':'warning'}">${validation.valid?'Đủ evidence':'Cần sửa'}</span></div><article class="ielts-passage">${escapeHtml(passage.passage)}</article>
  ${passage.status==='draft'?`<div class="ielts-validation">${validation.errors.length?validation.errors.map(error=>`<p>⚠ ${escapeHtml(error)}</p>`).join(''):'<p>Schema hợp lệ. Hãy đọc lại nội dung trước khi xác nhận.</p>'}</div><div class="ielts-question-preview">${(passage.questions||[]).map(question=>`<article><strong>${escapeHtml(question.prompt)}</strong><p>Evidence: “${escapeHtml(question.evidenceText)}”</p>${question.options.map(option=>`<small>${option.correct?'✓':'✕'} ${escapeHtml(option.text)} — ${escapeHtml(option.rationale)}</small>`).join('')}</article>`).join('')}</div><div class="ielts-actions"><button class="primary-button" data-verify-reading="${escapeAttr(passage.id)}" ${validation.valid?'':'disabled'}>Xác nhận passage</button><button class="text-button danger" data-delete-reading="${escapeAttr(passage.id)}">Xóa</button></div>`:`<form id="readingPracticeForm" class="ielts-form" data-reading="${escapeAttr(passage.id)}">${passage.questions.map((question,index)=>`<fieldset data-reading-question="${escapeAttr(question.id)}"><legend>${index+1}. ${escapeHtml(question.prompt)}</legend>${question.options.map(option=>`<label class="ielts-choice"><input type="radio" name="answer-${escapeAttr(question.id)}" value="${escapeAttr(option.id)}" required><span>${escapeHtml(option.text)}</span></label>`).join('')}<label>Evidence trong passage<input name="evidence-${escapeAttr(question.id)}" required placeholder="Chép cụm/câu làm bằng chứng"></label></fieldset>`).join('')}<button class="primary-button">Nộp bài</button></form><div id="readingFeedback"></div><details class="ielts-capture-reading"><summary>Lưu từ từ passage</summary><form id="readingCaptureForm" class="ielts-form" data-reading="${escapeAttr(passage.id)}"><label>Từ/collocation<input name="term" required></label><label>Nghĩa<input name="meaning" required></label><label>Ví dụ từ passage<textarea name="example"></textarea></label><button class="secondary-button">Thêm vào Library</button></form></details>`}`;}
function readingDraftMarkup(){return`<form id="readingDraftForm" class="ielts-form"><label>Chủ đề<input name="topic" required value="education and technology"></label><label>CEFR<select name="level"><option>B1</option><option selected>B2</option><option>C1</option></select></label><button class="primary-button">Tạo AI draft</button></form>`;}

async function renderMedia(panel){
  const sources=await listIeltsRecords(IELTS_STORE_NAMES.mediaSources);if(!state.mediaSourceId&&sources[0])state.mediaSourceId=sources[0].id;const source=sources.find(row=>row.id===state.mediaSourceId)||null;
  if(source&&(!state.segments.length||state.segments[0]?.mediaSourceId!==source.id)){state.segments=await listTranscriptSegments(source.id);state.currentSegmentId=(await getMediaProgress(source.id))?.lastSegmentId||state.segments[0]?.id||null;}
  panel.innerHTML=`<section class="ielts-card"><div class="ielts-section-head"><div><h3>Media Segment Lab</h3><p>Dán URL YouTube công khai → auto transcript/timestamp → Dictation, Shadowing, Retell. Không tải hoặc tách media.</p></div><label>Phiên<select id="mediaSessionMinutes"><option value="10">10 phút</option><option value="20" selected>20 phút</option><option value="30">30 phút</option></select></label></div>
    <form id="mediaUrlForm" class="ielts-inline-form"><label class="grow">URL YouTube<input name="url" type="url" required placeholder="https://www.youtube.com/watch?v=..."></label><label>Bắt đầu (phút)<input name="startMinutes" type="number" min="0" step="1" value="0"></label><button class="primary-button">Tạo transcript tối đa 20 phút</button></form><p class="ielts-disclaimer">Auto transcript dùng Gemini public YouTube input ở trạng thái preview. Transcript phải được người học kiểm tra trước khi dùng làm đáp án.</p>
    ${sources.length?`<div class="ielts-media-source-tabs">${sources.map(row=>`<button data-media-source="${escapeAttr(row.id)}" class="${row.id===source?.id?'active':''}">${escapeHtml(row.title)}<small>${escapeHtml(row.transcriptStatus)}</small></button>`).join('')}</div>`:''}</section>
    ${source?mediaWorkspaceMarkup(source):'<div class="ielts-empty"><strong>Chưa có video</strong><p>Dán URL YouTube công khai. Video private, unlisted, age-restricted hoặc chặn embed có thể không xử lý được.</p></div>'}`;
  if(source)queueMicrotask(()=>mountMediaPlayer(source).catch(error=>showStatus(error.message,'error')));
}
function mediaWorkspaceMarkup(source){
  const segment=currentMediaSegment();const progress=planMediaSession({minutes:Number($('#mediaSessionMinutes')?.value||20),availableSegments:state.segments.length,completedSegments:0,weakSegments:0});
  return`<div class="ielts-media-layout"><section class="ielts-card media-player-card"><div id="ieltsYoutubeHost" class="ielts-youtube-host" aria-label="YouTube player"></div><div class="ielts-player-controls"><button class="secondary-button" data-media-action="play-segment">▶ Đoạn hiện tại</button><label><input type="checkbox" id="mediaLoopToggle"> Lặp A–B</label><label>Tốc độ<select id="mediaPlaybackRate"><option>.75</option><option selected>1</option><option>1.25</option><option>1.5</option></select></label><span id="mediaCurrentTime">00:00.0</span></div><p><b>${escapeHtml(source.title)}</b> · ${state.segments.length} segments · kế hoạch ${progress.dictationSegments} dictation, ${progress.shadowingSegments} shadowing, ${progress.retellSegments} retell.</p></section>
  <section class="ielts-card transcript-card"><div class="ielts-section-head"><div><h3>Transcript editor</h3><p>Timestamp và confidence là dữ liệu cần kiểm tra, không phải ground truth.</p></div><button class="primary-button" data-media-action="save-transcript">Lưu transcript</button></div><div class="ielts-segment-list">${state.segments.length?state.segments.map((row,index)=>segmentEditorMarkup(row,index)).join(''):'<div class="ielts-empty"><p>Chưa có transcript. Có thể thử tạo lại.</p></div>'}</div></section></div>
  ${segment?`<section class="ielts-card"><div class="ielts-mode-tabs" role="tablist"><button class="active" data-media-mode="dictation">Dictation</button><button data-media-mode="shadowing">Shadowing</button><button data-media-mode="retell">Retell</button></div><div id="mediaPracticePanel">${dictationMarkup(segment)}</div></section>`:''}`;
}
function segmentEditorMarkup(row,index){return`<article class="ielts-segment-row ${row.id===state.currentSegmentId?'active':''}" data-segment-row="${escapeAttr(row.id)}"><button class="ielts-segment-play" data-select-segment="${escapeAttr(row.id)}" aria-label="Chọn segment ${index+1}">${index+1}<small>${formatTime(row.startMs)}–${formatTime(row.endMs)}</small></button><label>Bắt đầu<input data-segment-start type="number" step="0.1" min="0" value="${(row.startMs/1000).toFixed(1)}"></label><label>Kết thúc<input data-segment-end type="number" step="0.1" min="0" value="${(row.endMs/1000).toFixed(1)}"></label><label class="grow">Transcript<textarea data-segment-text rows="2">${escapeHtml(row.text)}</textarea></label><div class="ielts-segment-actions"><label><input data-segment-verified type="checkbox" ${row.status==='verified'?'checked':''}> Đã kiểm tra</label><button type="button" class="text-button" data-split-segment="${escapeAttr(row.id)}">Tách</button><button type="button" class="text-button" data-merge-segment="${escapeAttr(row.id)}" ${index===state.segments.length-1?'disabled':''}>Gộp sau</button></div><small>confidence: ${row.confidence==null?'—':`${Math.round(row.confidence*100)}% (${escapeHtml(row.confidenceSource||'unknown')})`}</small></article>`;}
function dictationMarkup(segment){return`<div class="ielts-practice-grid"><div><p class="ielts-eyebrow">DICTATION · ${formatTime(segment.startMs)}–${formatTime(segment.endMs)}</p><h3>Nghe rồi chép lại câu</h3><button class="secondary-button" data-media-action="play-segment">🔊 Nghe đoạn</button><p class="ielts-hidden-transcript ${state.dictationRevealed?'revealed':''}" id="dictationTranscript">${state.dictationRevealed?escapeHtml(segment.text):'Transcript đang ẩn'}</p></div><form id="mediaDictationForm" class="ielts-form" data-segment="${escapeAttr(segment.id)}"><label>Câu trả lời<textarea name="answer" required rows="3"></textarea></label><label>Target card<select name="cardId">${cardOptions(segment.linkedCardIds?.[0]||'')}</select></label><label>Khi sai, nguyên nhân chính<select name="errorType"><option value="listening">Không nghe ra/segment sai</option><option value="spelling-only">Nghe ra nhưng viết sai</option><option value="transcript-source">Transcript nguồn sai</option></select></label><div class="ielts-actions"><button class="primary-button">So sánh</button><button type="button" class="secondary-button" data-media-action="reveal-transcript">${state.dictationRevealed?'Ẩn':'Hiện'} transcript</button></div></form></div><div id="mediaPracticeFeedback"></div>`;}
function shadowingMarkup(segment){return`<div class="ielts-practice-grid"><div><p class="ielts-eyebrow">SHADOWING · COACHING ONLY</p><h3>${escapeHtml(segment.text)}</h3><p>Nghe, bắt chước thought group, rồi nghe lại bản thân. Hoạt động này không tạo review event FSRS.</p><button class="secondary-button" data-media-action="play-segment">🔊 Nghe mẫu</button></div><div class="ielts-recorder"><button class="primary-button" data-media-action="record-shadow">🎙️ Thu tối đa 15 giây</button><p id="shadowRecordingStatus">Chưa thu âm.</p><audio id="shadowPlayback" controls></audio><button class="secondary-button" data-media-action="save-shadow" disabled>Lưu coaching attempt</button></div></div>`;}
function retellMarkup(segment){
  const nearby=state.segments.filter(row=>row.startMs>=segment.startMs&&row.startMs<segment.startMs+90_000);const source=nearby.map(row=>row.text).join(' ');return`<div class="ielts-practice-grid"><div><p class="ielts-eyebrow">RETELL · 30–90 GIÂY</p><h3>Nghe đoạn, ẩn transcript và kể lại ý chính</h3><button class="secondary-button" data-media-action="play-retell">▶ Nghe nguồn</button><details><summary>Xem transcript nguồn để chuẩn bị</summary><p>${escapeHtml(source)}</p></details></div><form id="mediaRetellForm" class="ielts-form" data-source="${escapeAttr(source)}"><label>Retell transcript<textarea name="learnerTranscript" required rows="6" placeholder="Gõ lại hoặc dùng nhận giọng nói"></textarea></label><button type="button" class="secondary-button" data-media-action="speech-retell">🎤 Nhận giọng nói</button><fieldset><legend>Chọn trước lexical targets</legend><div class="ielts-target-grid">${activeCards().slice(0,30).map(card=>`<label><input type="checkbox" name="target" value="${escapeAttr(card.id)}"> ${escapeHtml(card.front)}</label>`).join('')}</div></fieldset><button class="primary-button">Phân tích retell</button><small>Không cung cấp band score; chỉ trích lexical gaps và tối đa ba lỗi.</small></form></div><div id="mediaPracticeFeedback"></div>`;}

async function mountMediaPlayer(source){
  const host=$('#ieltsYoutubeHost');if(!host)return;state.player?.destroy();state.player=new YouTubeSegmentPlayer({host,onTimeUpdate:time=>{const node=$('#mediaCurrentTime');if(node)node.textContent=formatTime(time*1000);},onError:error=>showStatus(error.message,'error')});const segment=currentMediaSegment();await state.player.mount(source.videoId,{startSeconds:(segment?.startMs||0)/1000,endSeconds:(segment?.endMs||0)/1000});const progress=await getMediaProgress(source.id);if(progress?.lastPositionMs)state.player.seek(progress.lastPositionMs/1000);if(progress?.playbackRate)state.player.setPlaybackRate(progress.playbackRate);}
function collectSegmentsFromEditor(){return $$('[data-segment-row]').map((row,index)=>sanitizeTranscriptSegment({id:row.dataset.segmentRow,mediaSourceId:state.mediaSourceId,order:index,startSeconds:Number($('[data-segment-start]',row)?.value||0),endSeconds:Number($('[data-segment-end]',row)?.value||0),text:$('[data-segment-text]',row)?.value||'',status:$('[data-segment-verified]',row)?.checked?'verified':'needs-review',userCorrected:true,linkedCardIds:state.segments.find(item=>item.id===row.dataset.segmentRow)?.linkedCardIds||[],confidence:state.segments.find(item=>item.id===row.dataset.segmentRow)?.confidence,confidenceSource:state.segments.find(item=>item.id===row.dataset.segmentRow)?.confidenceSource},index));}

async function saveCardFromEntry(entry,set){
  const current=coreState();const card=sanitizeCardInput({front:entry.term,back:entry.meaning,type:entry.term.includes(' ')?'collocation':'word',learningGoal:'active',deck:`IELTS · ${set.name}`,cefr:String(set.level||'B2').split('–')[0],example:entry.context,usageNote:`Function: ${entry.function}. Register: ${entry.register}. Common mistake: ${entry.commonMistake}`,sourceContext:entry.context,provenance:{source:'manual',sourceContext:`IELTS Lexical Set: ${set.name}`,confirmedByUser:true}});
  const duplicate=current.cards.find(item=>cardIdentityKey(item)===cardIdentityKey(card));if(duplicate)return duplicate;
  await persistCard(card,'ielts-lexical-card-added');dispatchCards([card,...current.cards]);return card;
}

async function commitEvidence({decision,card,exerciseType,metadata}){
  if(!decision.affectsSchedule||!card)return null;const current=coreState();const result=applyFsrsRating(card,decision.rating,Date.now(),current.fsrsConfig,decision.skill);await persistReviewResult({card:result.card,event:{cardId:card.id,skill:decision.skill,exerciseType,sessionMode:'ielts-lab',resultLog:result.log,rating:decision.rating,reviewedAt:Date.now(),assisted:false,metadata:{...metadata,evidenceReason:decision.reason}},reason:`ielts-${exerciseType}`});dispatchCards(current.cards.map(item=>item.id===card.id?result.card:item));return result;
}

async function captureError(input){const saved=await upsertErrorRecord(input);await renderTodayErrors();return saved;}

async function handleDialogClick(event){
  const button=event.target.closest('button');if(!button)return;
  if(button.dataset.ieltsAction==='close')return closeLab();
  if(button.dataset.ieltsAction==='retry-render')return renderLab();
  if(button.dataset.ieltsAction==='backup'){try{await downloadIeltsBackup();showStatus('Đã tạo backup IELTS đầy đủ.','success');}catch(error){showStatus(error.message,'error');}return;}
  if(button.dataset.ieltsTab){state.tab=button.dataset.ieltsTab;return renderLab();}
  if(button.dataset.ieltsGo){state.tab=button.dataset.ieltsGo;return renderLab();}
  if(button.dataset.errorId){state.selectedErrorId=button.dataset.errorId;return renderErrors($('#ieltsLabPanel'));}
  if(button.dataset.errorStatusSet){await setErrorStatus(button.dataset.errorTarget,button.dataset.errorStatusSet);showStatus('Đã cập nhật trạng thái lỗi.','success');await renderErrors($('#ieltsLabPanel'));await renderTodayErrors();return;}
  if(button.dataset.setId){state.selectedSetId=button.dataset.setId;return renderLexical($('#ieltsLabPanel'));}
  if(button.dataset.addSetEntry!=null){return addLexicalEntry(button.dataset.setTarget,Number(button.dataset.addSetEntry));}
  if(button.dataset.setProduction)return openSetProduction(button.dataset.setProduction);
  if(button.dataset.ieltsAction==='new-paraphrase'){$('#ieltsLabPanel').innerHTML=`<section class="ielts-card"><div class="ielts-section-head"><h3>Tạo Paraphrase/Distractor draft</h3><button class="text-button" data-ielts-tab="paraphrase">Quay lại</button></div>${paraphraseDraftMarkup()}</section>`;return;}
  if(button.dataset.labId){state.selectedLabId=button.dataset.labId;return renderParaphrase($('#ieltsLabPanel'));}
  if(button.dataset.deleteLab){await deleteIeltsRecord(IELTS_STORE_NAMES.labItems,button.dataset.deleteLab);state.selectedLabId=null;return renderParaphrase($('#ieltsLabPanel'));}
  if(button.dataset.ieltsAction==='new-reading'){$('#ieltsLabPanel').innerHTML=`<section class="ielts-card"><div class="ielts-section-head"><h3>Tạo Reading draft</h3><button class="text-button" data-ielts-tab="reading">Quay lại</button></div>${readingDraftMarkup()}</section>`;return;}
  if(button.dataset.readingId){state.selectedReadingId=button.dataset.readingId;return renderReading($('#ieltsLabPanel'));}
  if(button.dataset.verifyReading){const passage=await getIeltsRecord(IELTS_STORE_NAMES.readingPassages,button.dataset.verifyReading);const validation=validateReadingPassage(passage);if(!validation.valid)return showStatus(validation.errors.join(' '),'error');await saveReadingPassage({...passage,status:'verified',provenance:{...(passage.provenance||{}),status:'verified',verifiedAt:Date.now(),verifiedBy:'learner'}});showStatus('Đã xác nhận passage.','success');return renderReading($('#ieltsLabPanel'));}
  if(button.dataset.deleteReading){await deleteIeltsRecord(IELTS_STORE_NAMES.readingPassages,button.dataset.deleteReading);state.selectedReadingId=null;return renderReading($('#ieltsLabPanel'));}
  if(button.dataset.mediaSource){state.mediaSourceId=button.dataset.mediaSource;state.segments=[];state.currentSegmentId=null;return renderMedia($('#ieltsLabPanel'));}
  if(button.dataset.selectSegment){state.currentSegmentId=button.dataset.selectSegment;state.dictationRevealed=false;const segment=currentMediaSegment();state.player?.setSegment(segment.startMs/1000,segment.endMs/1000);return renderMedia($('#ieltsLabPanel'));}
  if(button.dataset.mediaAction)return handleMediaAction(button.dataset.mediaAction,button);
  if(button.dataset.splitSegment)return splitSegment(button.dataset.splitSegment);
  if(button.dataset.mergeSegment)return mergeSegment(button.dataset.mergeSegment);
  if(button.dataset.mediaMode){$$('[data-media-mode]').forEach(item=>item.classList.toggle('active',item===button));const segment=currentMediaSegment();const panel=$('#mediaPracticePanel');if(button.dataset.mediaMode==='dictation')panel.innerHTML=dictationMarkup(segment);if(button.dataset.mediaMode==='shadowing')panel.innerHTML=shadowingMarkup(segment);if(button.dataset.mediaMode==='retell')panel.innerHTML=retellMarkup(segment);}
}

async function handleDialogSubmit(event){
  event.preventDefault();const form=event.target;
  try{
    if(form.id==='manualErrorForm')return submitManualError(form);
    if(form.id==='errorCorrectionForm')return submitErrorCorrection(form);
    if(form.id==='setProductionForm')return submitSetProduction(form);
    if(form.id==='paraphraseDraftForm')return generateParaphraseDraft(form);
    if(form.id==='labEditorForm')return saveLabEditor(form,event.submitter?.value||'draft');
    if(form.id==='labPracticeForm')return submitLabPractice(form);
    if(form.id==='readingDraftForm')return generateReadingDraft(form);
    if(form.id==='readingPracticeForm')return submitReadingPractice(form);
    if(form.id==='readingCaptureForm')return captureReadingCard(form);
    if(form.id==='mediaUrlForm')return createMediaTranscript(form);
    if(form.id==='mediaDictationForm')return submitMediaDictation(form);
    if(form.id==='mediaRetellForm')return submitMediaRetell(form);
  }catch(error){showStatus(error.message,'error');setBusy(false);}
}
async function handleDialogChange(event){
  if(event.target.matches('[data-ielts-restore]')){const file=event.target.files?.[0];if(!file)return;try{const input=JSON.parse(await file.text());const validation=validateIeltsBackup(input);if(!validation.valid)throw new Error(validation.errors.join('\n'));await restoreIeltsBackup(input);showStatus(`Đã khôi phục IELTS backup${validation.warnings.length?` với ${validation.warnings.length} cảnh báo`:''}.`,'success');await renderLab();await renderTodayErrors();}catch(error){showStatus(error.message,'error');}finally{event.target.value='';}}
  if(event.target.id==='errorStatusFilter'){const value=event.target.value;$$('[data-error-status]').forEach(row=>{row.hidden=value!=='all'&&row.dataset.errorStatus!==value;});}
  if(event.target.id==='mediaLoopToggle')state.player?.setLoop(event.target.checked);
  if(event.target.id==='mediaPlaybackRate'){const selected=state.player?.setPlaybackRate(Number(event.target.value));const source=await getIeltsRecord(IELTS_STORE_NAMES.mediaSources,state.mediaSourceId);if(source)await saveMediaProgress({mediaSourceId:source.id,lastSegmentId:state.currentSegmentId,lastPositionMs:state.player?.getCurrentTime()*1000||0,playbackRate:selected||1,sessionMinutes:Number($('#mediaSessionMinutes')?.value||20)});}
}

async function submitManualError(form){const data=new FormData(form);await captureError(createErrorRecord({category:data.get('category'),learnerResponse:data.get('learnerResponse'),expectedResponse:data.get('expectedResponse'),correction:data.get('expectedResponse'),explanation:data.get('explanation'),linkedCardIds:data.get('linkedCardId')?[data.get('linkedCardId')]:[],sourceRef:{type:'manual',title:'Lỗi nhập thủ công'}}));form.reset();showStatus('Đã lưu lỗi; lỗi trùng sẽ tăng occurrence count.','success');await renderErrors($('#ieltsLabPanel'));}
async function submitErrorCorrection(form){const error=await getIeltsRecord(IELTS_STORE_NAMES.errors,form.dataset.error);if(!error)throw new Error('Không tìm thấy lỗi.');const data=new FormData(form);const answer=String(data.get('answer')||'');const expected=error.correction||error.expectedResponse;const correct=normalizeComparableText(answer)===normalizeComparableText(expected);const card=error.linkedCardIds?.length===1?findCard(error.linkedCardIds[0]):null;const decision=resolveIeltsEvidence({activityType:'error-correction',targetCardId:card?.id,skill:data.get('skill'),independent:true,assisted:false,verified:true,result:correct?'correct':'wrong'});if(correct){await setErrorStatus(error.id,'monitoring');await commitEvidence({decision,card,exerciseType:'ielts-error-correction',metadata:{errorId:error.id,learnerResponse:answer,expectedResponse:expected}});showStatus(decision.affectsSchedule?'Sửa đúng độc lập; đã ghi một FSRS evidence.':'Sửa đúng; không có target card phù hợp nên không thay đổi FSRS.','success');}else{await captureError({...error,id:createIeltsId('error-occurrence'),learnerResponse:answer,lastSeenAt:Date.now(),occurrenceCount:1});showStatus('Chưa đúng. Lượt hỗ trợ tiếp theo không kéo dài FSRS.','error');}await renderErrors($('#ieltsLabPanel'));}

async function addLexicalEntry(setId,index){const set=await getIeltsRecord(IELTS_STORE_NAMES.lexicalSets,setId);const entry=set?.suggestedEntries?.[index];if(!set||!entry)throw new Error('Không tìm thấy lexical entry.');setBusy(true,'Đang thêm vào Library…');try{const card=await saveCardFromEntry(entry,set);const itemIds=[...new Set([...(set.itemIds||[]),card.id])];await saveIeltsRecord(IELTS_STORE_NAMES.lexicalSets,{...set,itemIds,updatedAt:Date.now()},'ielts-set-membership');showStatus(`Đã liên kết “${entry.term}” với Library.`,'success');await renderLexical($('#ieltsLabPanel'));}finally{setBusy(false);}}
async function openSetProduction(setId){const set=await getIeltsRecord(IELTS_STORE_NAMES.lexicalSets,setId);const cards=(set.itemIds||[]).map(findCard).filter(Boolean);$('#ieltsLabPanel').innerHTML=`<section class="ielts-card"><div class="ielts-section-head"><div><p class="ielts-eyebrow">PRODUCTION TASK</p><h3>${escapeHtml(set.name)}</h3><p>${escapeHtml(set.productionTask)}</p></div><button class="text-button" data-set-id="${escapeAttr(set.id)}">Quay lại</button></div><div class="ielts-target-chips">${cards.map(card=>`<span>${escapeHtml(card.front)}</span>`).join('')}</div><form id="setProductionForm" class="ielts-form" data-set="${escapeAttr(set.id)}"><label>Đoạn của bạn<textarea name="paragraph" rows="7" required></textarea></label><button class="primary-button">Đánh giá từng target bằng AI hiện có</button></form><div id="setProductionFeedback"></div></section>`;}
async function submitSetProduction(form){const set=await getIeltsRecord(IELTS_STORE_NAMES.lexicalSets,form.dataset.set);const cards=(set.itemIds||[]).map(findCard).filter(Boolean).slice(0,5);const paragraph=String(new FormData(form).get('paragraph')||'');if(cards.length<3)throw new Error('Cần ít nhất 3 card trong set.');setBusy(true,'AI đang đánh giá từng target…');try{const data=await callExistingAi('/api/ai/output-practice',{terms:cards.map(card=>({id:card.id,front:card.front,back:card.back})),paragraph});const assessments=Array.isArray(data.termAssessments)?data.termAssessments:[];const results=[];for(const card of cards){const assessment=assessments.find(row=>row.id===card.id);const decision=resolveIeltsEvidence({activityType:'retell',targetCardId:card.id,preselectedTarget:true,usedTargetCorrectly:Boolean(assessment?.targetUsedCorrectly),independent:true,assisted:false,verified:true,result:assessment?.rating==='hard'?'near':'correct'});if(assessment?.targetUsedCorrectly)await commitEvidence({decision,card,exerciseType:'ielts-lexical-production',metadata:{setId:set.id,paragraph,feedback:assessment.feedback}});else await captureError({category:'lexical-gap',prompt:set.productionTask,learnerResponse:paragraph,expectedResponse:`Dùng đúng ${card.front}`,correction:data.correctedParagraph||'',explanation:assessment?.feedback||'Không có bằng chứng sử dụng đúng target.',linkedCardIds:[card.id],sourceRef:{type:'lexical-set',sourceId:set.id,title:set.name}});results.push(`<p><b>${escapeHtml(card.front)}:</b> ${assessment?.targetUsedCorrectly?'✓':'✕'} ${escapeHtml(assessment?.feedback||'')}</p>`);}$('#setProductionFeedback').innerHTML=`<div class="ielts-feedback">${results.join('')}<p>${escapeHtml(data.feedback||'')}</p></div>`;showStatus('Đã xử lý production task theo từng target.','success');}finally{setBusy(false);}}
async function callExistingAi(path,payload,{timeoutMs=45_000}={}){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeoutMs);const current=coreState();const headers={'content-type':'application/json','x-gemini-model':current.settings?.model||'gemini-3.6-flash'};const key=sessionStorage.getItem(SESSION_KEY)||'';if(key)headers['x-gemini-key']=key;try{const response=await fetch(path,{method:'POST',headers,body:JSON.stringify(payload),signal:controller.signal});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`AI HTTP ${response.status}`);return data;}finally{clearTimeout(timer);}}

async function generateParaphraseDraft(form){const data=new FormData(form);setBusy(true,'Đang tạo bản nháp có rationale…');try{const result=await callIeltsApi('/api/ielts/paraphrase-draft',{kind:data.get('kind'),sourceText:data.get('sourceText'),context:data.get('context'),sourceCardIds:data.get('cardId')?[data.get('cardId')]:[]},{timeoutMs:55_000});const item=sanitizeLabItem({...result.item,kind:data.get('kind'),sourceCardIds:data.get('cardId')?[data.get('cardId')]:result.item.sourceCardIds,status:'draft'});await saveLabItem(item);state.selectedLabId=item.id;showStatus(result.validation?.valid?'Đã tạo draft hợp lệ; vẫn cần người học xác nhận.':'Đã tạo draft nhưng validator phát hiện vấn đề.','success');await renderParaphrase($('#ieltsLabPanel'));}finally{setBusy(false);}}
async function saveLabEditor(form,intent){const item=await getIeltsRecord(IELTS_STORE_NAMES.labItems,form.dataset.lab);const data=new FormData(form);const options=(item.options||[]).map((option,index)=>({...option,text:data.get(`optionText-${index}`),rationale:data.get(`optionRationale-${index}`),correct:String(data.get('correctIndex'))===String(index)}));const value=sanitizeLabItem({...item,prompt:data.get('prompt'),context:data.get('context'),options,status:intent==='verify'?'verified':'draft',provenance:{...(item.provenance||{}),status:intent==='verify'?'verified':'draft',verifiedAt:intent==='verify'?Date.now():null,verifiedBy:intent==='verify'?'learner':null}});const validation=validateLabItem(value);if(intent==='verify'&&!validation.valid)throw new Error(validation.errors.join(' '));await saveLabItem(value);showStatus(intent==='verify'?'Đã xác nhận item.':'Đã lưu draft.','success');await renderParaphrase($('#ieltsLabPanel'));}
async function submitLabPractice(form){const item=await getIeltsRecord(IELTS_STORE_NAMES.labItems,form.dataset.lab);if(item.status!=='verified')throw new Error('Chỉ item verified mới được luyện.');const data=new FormData(form);const selected=item.options.find(option=>option.id===data.get('answer'));const correct=Boolean(selected?.correct);const feedback=$('#labFeedback');feedback.innerHTML=`<div class="ielts-feedback ${correct?'success':'error'}"><strong>${correct?'✓ Giữ nguyên nghĩa':'✕ Chưa đúng'}</strong>${item.options.map(option=>`<p><b>${option.correct?'Đáp án':'Distractor'}:</b> ${escapeHtml(option.text)} — ${escapeHtml(option.rationale)}</p>`).join('')}</div>`;if(!correct)await captureError({category:item.kind==='distractor'?'distractor':'paraphrase',prompt:item.prompt,learnerResponse:selected?.text||'',expectedResponse:item.options.find(option=>option.correct)?.text||'',correction:item.options.find(option=>option.correct)?.text||'',explanation:selected?.rationale||'',linkedCardIds:item.sourceCardIds||[],sourceRef:{type:'paraphrase',sourceId:item.id,title:item.prompt,context:item.context}});showStatus(correct?'Đúng; bài relation không tự động tăng FSRS.':'Đã lưu lỗi vào Notebook; không tự động thay đổi card FSRS.',correct?'success':'error');}

async function generateReadingDraft(form){const data=new FormData(form);setBusy(true,'Đang tạo passage và kiểm tra evidence…');try{const result=await callIeltsApi('/api/ielts/reading-draft',{topic:data.get('topic'),level:data.get('level')},{timeoutMs:60_000});const passage=sanitizeReadingPassage({...result.passage,status:'draft'});await saveReadingPassage(passage);state.selectedReadingId=passage.id;showStatus(result.validation?.valid?'Draft đạt schema; cần đọc và xác nhận.':'Draft cần sửa trước khi xác nhận.','success');await renderReading($('#ieltsLabPanel'));}finally{setBusy(false);}}
async function submitReadingPractice(form){const passage=await getIeltsRecord(IELTS_STORE_NAMES.readingPassages,form.dataset.reading);if(passage.status!=='verified')throw new Error('Passage chưa verified.');const data=new FormData(form);const answers=[];let correctCount=0;const feedback=[];for(const question of passage.questions){const selected=question.options.find(option=>option.id===data.get(`answer-${question.id}`));const evidence=String(data.get(`evidence-${question.id}`)||'');const evidenceMatch=normalizeComparableText(evidence)&&normalizeComparableText(question.evidenceText).includes(normalizeComparableText(evidence))||normalizeComparableText(evidence).includes(normalizeComparableText(question.evidenceText));const correct=Boolean(selected?.correct&&evidenceMatch);if(correct)correctCount++;answers.push({questionId:question.id,optionId:selected?.id||null,evidence,correct,evidenceMatch});feedback.push(`<article><strong>${correct?'✓':'✕'} ${escapeHtml(question.prompt)}</strong><p>Evidence: “${escapeHtml(question.evidenceText)}”</p><p>${escapeHtml(question.explanation)}</p>${question.options.map(option=>`<small>${option.correct?'Đúng':'Sai'}: ${escapeHtml(option.rationale)}</small>`).join('')}</article>`);if(!correct)await captureError({category:selected?.correct&&!evidenceMatch?'reading-strategy':'distractor',prompt:question.prompt,learnerResponse:`${selected?.text||'Không chọn'} | Evidence: ${evidence}`,expectedResponse:`${question.options.find(option=>option.correct)?.text||''} | Evidence: ${question.evidenceText}`,correction:question.options.find(option=>option.correct)?.text||'',explanation:question.explanation,sourceRef:{type:'reading',sourceId:passage.id,subId:question.id,title:passage.title,context:passage.passage}});}
  await saveReadingAttempt({passageId:passage.id,answers,score:correctCount/passage.questions.length,evidence:answers.map(row=>row.evidence)});$('#readingFeedback').innerHTML=`<div class="ielts-feedback"><h4>${correctCount}/${passage.questions.length} câu có cả đáp án và evidence đúng</h4>${feedback.join('')}</div>`;showStatus('Reading completion không thay đổi FSRS; lỗi đã được lưu có source/evidence.','success');}
async function captureReadingCard(form){const passage=await getIeltsRecord(IELTS_STORE_NAMES.readingPassages,form.dataset.reading);const data=new FormData(form);const current=coreState();const card=sanitizeCardInput({front:data.get('term'),back:data.get('meaning'),example:data.get('example'),sourceContext:passage.passage,deck:`IELTS Reading · ${passage.title}`,learningGoal:'active',provenance:{source:'manual',sourceContext:`Reading: ${passage.title}`,confirmedByUser:true}});if(current.cards.some(row=>cardIdentityKey(row)===cardIdentityKey(card)))throw new Error('Card này đã có trong Library.');await persistCard(card,'ielts-reading-card-added');dispatchCards([card,...current.cards]);form.reset();showStatus('Đã thêm card với source passage; chưa tạo FSRS review.','success');}

async function createMediaTranscript(form){const data=new FormData(form);const parsed=parseYouTubeUrl(data.get('url'));if(!parsed.valid)throw new Error(parsed.error);const startSeconds=Math.max(parsed.startSeconds,Number(data.get('startMinutes')||0)*60);const minutes=20;let source=await findMediaByVideoId(parsed.videoId);if(!source){source=await saveMediaSource(sanitizeMediaSource({url:parsed.canonicalUrl,videoId:parsed.videoId,title:`YouTube · ${parsed.videoId}`,language:'en',transcriptStatus:'draft'}));}state.mediaSourceId=source.id;const cacheKey=`${parsed.videoId}:en:${startSeconds}:${minutes}:transcript-v1`;const job=await saveTranscriptionJob({mediaSourceId:source.id,cacheKey,model:coreState().settings?.model,status:'processing',language:'en'});setBusy(true,'Đang tạo transcript và timestamp cho đoạn tối đa 20 phút…');try{const result=await callIeltsApi('/api/ielts/transcript',{url:parsed.canonicalUrl,mediaSourceId:source.id,startSeconds,minutes,language:'en'});source=await saveMediaSource({...source,title:result.title||source.title,durationMs:Number(result.durationSeconds||0)*1000,transcriptStatus:'needs-review',transcriptModel:result.model,updatedAt:Date.now()});const saved=await replaceTranscriptSegments(source.id,result.segments,{durationMs:source.durationMs||((startSeconds+minutes*60)*1000)});state.segments=saved.segments;state.currentSegmentId=state.segments[0]?.id||null;await saveTranscriptionJob({...job,status:'needs-review',error:''});await saveMediaProgress({mediaSourceId:source.id,lastSegmentId:state.currentSegmentId,lastPositionMs:state.segments[0]?.startMs||0,sessionMinutes:20});showStatus(`Đã tạo ${state.segments.length} segments. Hãy kiểm tra transcript trước khi dùng làm đáp án.${result.cached?' Dùng bản cache.':''}`,'success');await renderMedia($('#ieltsLabPanel'));}catch(error){await saveTranscriptionJob({...job,status:'failed',retryCount:Number(job.retryCount||0)+1,error:error.message});throw error;}finally{setBusy(false);}}
async function saveTranscriptEditor(){const source=await getIeltsRecord(IELTS_STORE_NAMES.mediaSources,state.mediaSourceId);const rows=collectSegmentsFromEditor();const validation=validateTranscriptSegments(rows,{durationMs:source.durationMs});if(!validation.valid)throw new Error(validation.errors.join(' '));const saved=await replaceTranscriptSegments(source.id,validation.segments,{durationMs:source.durationMs});state.segments=saved.segments;const allVerified=state.segments.every(row=>row.status==='verified');await saveMediaSource({...source,transcriptStatus:allVerified?'verified':'needs-review',updatedAt:Date.now()});showStatus(`Đã lưu transcript${allVerified?' và xác nhận toàn bộ':''}.${validation.warnings.length?` ${validation.warnings.length} cảnh báo.`:''}`,'success');await renderMedia($('#ieltsLabPanel'));}
async function splitSegment(id){const rows=collectSegmentsFromEditor();const index=rows.findIndex(row=>row.id===id);if(index<0)return;const value=rows[index];const [a,b]=splitTranscriptSegment(value,(value.startMs+value.endMs)/2);rows.splice(index,1,a,b);const source=await getIeltsRecord(IELTS_STORE_NAMES.mediaSources,state.mediaSourceId);const saved=await replaceTranscriptSegments(source.id,rows,{durationMs:source.durationMs});state.segments=saved.segments;state.currentSegmentId=a.id;showStatus('Đã tách segment tại điểm giữa; hãy chỉnh timestamp/text rồi xác nhận.','success');await renderMedia($('#ieltsLabPanel'));}
async function mergeSegment(id){const rows=collectSegmentsFromEditor();const index=rows.findIndex(row=>row.id===id);if(index<0||index===rows.length-1)return;const merged=mergeTranscriptSegments(rows[index],rows[index+1]);rows.splice(index,2,merged);const source=await getIeltsRecord(IELTS_STORE_NAMES.mediaSources,state.mediaSourceId);const saved=await replaceTranscriptSegments(source.id,rows,{durationMs:source.durationMs});state.segments=saved.segments;state.currentSegmentId=merged.id;showStatus('Đã gộp hai segment; cần xác nhận lại.','success');await renderMedia($('#ieltsLabPanel'));}

async function handleMediaAction(action,button){
  const segment=currentMediaSegment();if(!segment&&action!=='save-transcript')return;
  if(action==='play-segment'){state.player?.setSegment(segment.startMs/1000,segment.endMs/1000);state.player?.playSegment({loop:$('#mediaLoopToggle')?.checked});return;}
  if(action==='reveal-transcript'){state.dictationRevealed=!state.dictationRevealed;$('#mediaPracticePanel').innerHTML=dictationMarkup(segment);return;}
  if(action==='save-transcript')return saveTranscriptEditor();
  if(action==='record-shadow')return startShadowRecording();
  if(action==='save-shadow'){await saveMediaAttempt(sanitizeMediaAttempt({mediaSourceId:state.mediaSourceId,segmentId:segment.id,mode:'shadowing',expectedResponse:segment.text,result:'coaching',durationMs:state.recording?.durationMs||0,evidenceDecisions:[{affectsSchedule:false,reason:'shadowing-is-imitation'}]}));showStatus('Đã lưu coaching attempt. Shadowing không tạo FSRS review event.','success');return;}
  if(action==='play-retell'){const nearby=state.segments.filter(row=>row.startMs>=segment.startMs&&row.startMs<segment.startMs+90_000);const end=nearby.at(-1)?.endMs||segment.endMs;state.player?.setSegment(segment.startMs/1000,end/1000);state.player?.playSegment({loop:false});return;}
  if(action==='speech-retell')return startRetellRecognition(button);
}

async function submitMediaDictation(form){const segment=state.segments.find(row=>row.id===form.dataset.segment);const source=await getIeltsRecord(IELTS_STORE_NAMES.mediaSources,state.mediaSourceId);const data=new FormData(form);const answer=String(data.get('answer')||'');const errorType=String(data.get('errorType')||'listening');const card=findCard(data.get('cardId'));const diff=diffWords(segment.text,answer);const result=diff.accuracy>=.98?'correct':diff.accuracy>=.75?'near':'wrong';const verified=segment.status==='verified';const decision=resolveIeltsEvidence({activityType:'dictation',targetCardId:card?.id,skill:'listening',independent:true,assisted:false,verified,result,errorType});await saveMediaAttempt(sanitizeMediaAttempt({mediaSourceId:source.id,segmentId:segment.id,mode:'dictation',learnerResponse:answer,expectedResponse:segment.text,result,wordErrors:diff.operations.filter(row=>row.type!=='equal'),linkedCardIds:card?[card.id]:[],evidenceDecisions:[decision]}));if(result!=='correct'&&errorType!=='transcript-source')await captureError({category:errorType==='spelling-only'?'spelling':'listening',prompt:'YouTube dictation',learnerResponse:answer,expectedResponse:segment.text,correction:segment.text,explanation:errorType==='spelling-only'?'Người học nhận ra nội dung nhưng viết sai; không giảm listening FSRS.':'Kiểm tra segmentation, weak forms và target đã liên kết.',linkedCardIds:card?[card.id]:[],sourceRef:{type:'media',sourceId:source.id,subId:segment.id,title:source.title,url:source.canonicalUrl,context:segment.text}});if(errorType==='transcript-source'){segment.status='needs-review';segment.userCorrected=true;showStatus('Đã đánh dấu transcript cần sửa; không ghi lỗi người học hoặc FSRS.','error');}
  await commitEvidence({decision,card,exerciseType:'ielts-media-dictation',metadata:{mediaSourceId:source.id,segmentId:segment.id,learnerResponse:answer,expectedResponse:segment.text,errorType,accuracy:diff.accuracy}});const feedback=$('#mediaPracticeFeedback');feedback.innerHTML=`<div class="ielts-feedback ${result==='correct'?'success':'error'}"><strong>${result==='correct'?'✓ Chính xác':`${Math.round(diff.accuracy*100)}% token match`}</strong><div class="ielts-word-diff">${diff.operations.map(row=>`<span class="${row.type}">${escapeHtml(row.actual??row.expected??'')}</span>`).join(' ')}</div><p>Đáp án: ${escapeHtml(segment.text)}</p><p>${decision.affectsSchedule?`FSRS ${decision.skill}: ${decision.rating}`:`Không cập nhật FSRS: ${escapeHtml(decision.reason)}`}</p></div>`;await updateMediaProgressAfterAttempt(source,segment,result);}
async function updateMediaProgressAfterAttempt(source,segment,result){const previous=await getMediaProgress(source.id)||{};const completed=new Set(previous.completedSegmentIds||[]);if(result==='correct')completed.add(segment.id);const weak=new Set(previous.weakSegmentIds||[]);if(result!=='correct')weak.add(segment.id);else weak.delete(segment.id);await saveMediaProgress({...previous,mediaSourceId:source.id,lastSegmentId:segment.id,lastPositionMs:segment.endMs,completedSegmentIds:[...completed],weakSegmentIds:[...weak],playbackRate:Number($('#mediaPlaybackRate')?.value||1),sessionMinutes:Number($('#mediaSessionMinutes')?.value||20)});}

async function startShadowRecording(){
  if(state.recording?.recorder?.state==='recording'){state.recording.recorder.stop();return;}
  if(!navigator.mediaDevices?.getUserMedia)throw new Error('Trình duyệt không hỗ trợ microphone.');stopRecording();const stream=await navigator.mediaDevices.getUserMedia({audio:true});const recorder=new MediaRecorder(stream);const chunks=[];const startedAt=Date.now();state.recording={recorder,stream,chunks,startedAt,durationMs:0};recorder.ondataavailable=event=>{if(event.data?.size)chunks.push(event.data);};recorder.onstop=()=>{stream.getTracks().forEach(track=>track.stop());const blob=new Blob(chunks,{type:recorder.mimeType||'audio/webm'});state.recording.durationMs=Date.now()-startedAt;state.recording.blob=blob;if(state.recordingUrl)URL.revokeObjectURL(state.recordingUrl);state.recordingUrl=URL.createObjectURL(blob);const audio=$('#shadowPlayback');if(audio){audio.src=state.recordingUrl;audio.hidden=false;}const status=$('#shadowRecordingStatus');if(status)status.textContent=`Đã thu ${(state.recording.durationMs/1000).toFixed(1)} giây. Nghe lại trước khi lưu.`;const save=$('[data-media-action="save-shadow"]');if(save)save.disabled=false;};recorder.start();$('#shadowRecordingStatus').textContent='Đang thu… bấm lại để dừng.';setTimeout(()=>{if(recorder.state==='recording')recorder.stop();},15_000);
}
function stopRecording(){if(state.recording?.recorder?.state==='recording')try{state.recording.recorder.stop();}catch{}state.recording?.stream?.getTracks?.().forEach(track=>track.stop());if(state.recordingUrl){URL.revokeObjectURL(state.recordingUrl);state.recordingUrl=null;}state.recording=null;}
function startRetellRecognition(button){const Recognition=globalThis.SpeechRecognition||globalThis.webkitSpeechRecognition;if(!Recognition)throw new Error('Trình duyệt không hỗ trợ nhận giọng nói; bạn vẫn có thể gõ transcript.');state.retellRecognition?.abort?.();const recognition=new Recognition();state.retellRecognition=recognition;recognition.lang='en-US';recognition.interimResults=true;recognition.continuous=true;const textarea=$('#mediaRetellForm textarea[name="learnerTranscript"]');recognition.onresult=event=>{let text='';for(let i=0;i<event.results.length;i++)text+=`${event.results[i][0].transcript} `;textarea.value=text.trim();};recognition.onerror=event=>showStatus(`Nhận giọng nói lỗi: ${event.error}`,'error');recognition.onend=()=>{button.textContent='🎤 Nhận giọng nói';};button.textContent='■ Dừng nhận';button.onclick=()=>recognition.stop();recognition.start();setTimeout(()=>recognition.stop(),60_000);}
async function submitMediaRetell(form){const segment=currentMediaSegment();const source=await getIeltsRecord(IELTS_STORE_NAMES.mediaSources,state.mediaSourceId);const data=new FormData(form);const learnerTranscript=String(data.get('learnerTranscript')||'');const targetIds=data.getAll('target');const targets=targetIds.map(id=>findCard(id)).filter(Boolean).map(card=>({cardId:card.id,term:card.front,meaning:card.back}));const sourceTranscript=form.dataset.source;setBusy(true,'AI đang phân tích retell; không tạo band score…');try{const result=await callIeltsApi('/api/ielts/retell',{sourceTranscript,learnerTranscript,targets},{timeoutMs:60_000});const evidenceDecisions=[];for(const target of result.targetAssessments||[]){const card=findCard(target.cardId);const decision=resolveIeltsEvidence({activityType:'retell',targetCardId:card?.id,preselectedTarget:true,usedTargetCorrectly:Boolean(target.usedCorrectly),independent:true,assisted:false,verified:true,result:'correct'});evidenceDecisions.push({...decision,cardId:target.cardId});await commitEvidence({decision,card,exerciseType:'ielts-media-retell',metadata:{mediaSourceId:source.id,segmentId:segment.id,learnerTranscript,feedback:target.feedback}});}
    for(const error of result.errors||[])await captureError({category:error.category||'production',prompt:'Retell đoạn YouTube',learnerResponse:error.learnerResponse||learnerTranscript,expectedResponse:error.correction,correction:error.correction,explanation:error.explanation,linkedCardIds:targets.map(row=>row.cardId),sourceRef:{type:'retell',sourceId:source.id,subId:segment.id,title:source.title,url:source.canonicalUrl,context:sourceTranscript}});
    for(const gap of result.lexicalGaps||[])await captureError({category:'lexical-gap',prompt:'Retell lexical gap',learnerResponse:learnerTranscript,expectedResponse:gap,correction:gap,explanation:'Lexical gap được trích từ retell; cần người học xác nhận trước khi tạo card.',sourceRef:{type:'retell',sourceId:source.id,subId:segment.id,title:source.title,context:sourceTranscript},provenance:{status:'draft',model:result.model,generatedAt:Date.now()}});
    await saveMediaAttempt(sanitizeMediaAttempt({mediaSourceId:source.id,segmentId:segment.id,mode:'retell',learnerResponse,expectedResponse:sourceTranscript,result:'coaching',linkedCardIds:targetIds,evidenceDecisions,durationMs:0}));$('#mediaPracticeFeedback').innerHTML=`<div class="ielts-feedback"><strong>Phản hồi retell — không phải band score</strong><p>${escapeHtml(result.feedback||'')}</p><h4>Main ideas</h4>${(result.mainIdeas||[]).map(row=>`<p>${row.covered?'✓':'○'} ${escapeHtml(row.idea)} ${row.evidence?`— ${escapeHtml(row.evidence)}`:''}</p>`).join('')}<h4>Targets</h4>${(result.targetAssessments||[]).map(row=>`<p>${row.usedCorrectly?'✓':'✕'} <b>${escapeHtml(row.term)}</b> — ${escapeHtml(row.feedback)}</p>`).join('')}<h4>Lexical gaps</h4><p>${escapeHtml((result.lexicalGaps||[]).join(', ')||'Không có gap rõ.')}</p></div>`;showStatus('Đã lưu retell, lexical gaps và lỗi phù hợp. Chỉ target chọn trước/dùng đúng mới cập nhật production FSRS.','success');}finally{setBusy(false);}}

async function renderTodayErrors(){
  const today=$('[data-view="today"]');if(!today)return;let widget=$('#ieltsTodayErrors');if(!widget){widget=document.createElement('section');widget.id='ieltsTodayErrors';widget.className='section-block ielts-today-errors';const anchor=$('.quick-modes-section',today);anchor?.insertAdjacentElement('beforebegin',widget);}
  const errors=(await listIeltsRecords(IELTS_STORE_NAMES.errors,{sortBy:'lastSeenAt'})).filter(row=>!['resolved','ignored'].includes(row.status)).sort((a,b)=>(b.severity==='high'?2:b.severity==='medium'?1:0)-(a.severity==='high'?2:a.severity==='medium'?1:0)||Number(b.occurrenceCount||1)-Number(a.occurrenceCount||1)).slice(0,3);
  widget.innerHTML=errors.length?`<div class="section-heading"><div><p class="eyebrow">PERSONAL ERROR NOTEBOOK</p><h3>Lỗi cần xử lý</h3></div><button class="text-button" id="openIeltsErrorsToday">Xem tất cả</button></div><div class="ielts-today-error-grid">${errors.map(row=>`<button data-today-error="${escapeAttr(row.id)}"><strong>${escapeHtml(row.correction||row.expectedResponse)}</strong><span>${escapeHtml(row.learnerResponse)} → ${escapeHtml(row.expectedResponse)}</span><small>${row.occurrenceCount} lần · ${escapeHtml(row.category)}</small></button>`).join('')}</div>`:'';
  $('#openIeltsErrorsToday')?.addEventListener('click',()=>openLab('errors'));$$('[data-today-error]',widget).forEach(button=>button.addEventListener('click',()=>{state.selectedErrorId=button.dataset.todayError;openLab('errors');}));
}

function inferLinkedCard(expected,prompt){const expectedNorm=normalizeComparableText(expected),promptNorm=normalizeComparableText(prompt);const cards=activeCards();return cards.find(card=>normalizeComparableText(card.front)===expectedNorm)||cards.find(card=>promptNorm.includes(normalizeComparableText(card.front))||promptNorm.includes(normalizeComparableText(card.back)))||cards.find(card=>normalizeComparableText(card.front).split(' ').includes(expectedNorm))||null;}
function installCoreErrorCapture(){
  document.addEventListener('submit',event=>{const form=event.target;if(form.id==='answerForm'){state.pendingCoreError={kind:'input',learnerResponse:$('#answerInput')?.value||'',prompt:$('.exercise-card h2')?.textContent||'',label:$('.exercise-type')?.textContent||'',createdAt:Date.now()};}if(form.id==='outputForm'){state.pendingCoreError={kind:'output',learnerResponse:$('#outputInput')?.value||'',prompt:$('.exercise-card h2')?.textContent||'',createdAt:Date.now()};}},true);
  document.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;if(button.id==='evaluateAi'||button.id==='manualAgain'){const prompt=$('.exercise-card h2')?.textContent||'';const learner=$('#productionInput')?.value||'';state.pendingCoreError={kind:'production',learnerResponse:learner,prompt,createdAt:Date.now()};if(button.id==='manualAgain')setTimeout(()=>captureCoreProductionGap(),0);}},true);
  const observer=new MutationObserver(()=>void inspectCoreFeedback());observer.observe(document.body,{childList:true,subtree:true,characterData:true});
}
async function inspectCoreFeedback(){const pending=state.pendingCoreError;if(!pending||Date.now()-pending.createdAt>15_000)return;const feedback=$('#answerFeedback');if(!feedback||!feedback.textContent.trim())return;const text=feedback.textContent;if(pending.kind==='input'&&!/Chưa đúng|Gần đúng/.test(text))return;if(pending.kind==='production'&&!/Chưa dùng đúng|✕/.test(text))return;if(pending.kind==='output'&&!/✕/.test(text))return;
  const expected=feedback.querySelector('b')?.textContent||extractQuotedTarget(pending.prompt)||'';const signature=`${pending.kind}|${pending.prompt}|${pending.learnerResponse}|${expected}|${text.slice(0,120)}`;if(state.processedErrorSignatures.has(signature))return;state.processedErrorSignatures.add(signature);state.pendingCoreError=null;
  if(pending.kind==='output'){for(const paragraph of $$('p',feedback)){if(!paragraph.textContent.includes('✕'))continue;const term=paragraph.querySelector('b')?.textContent?.replace(/:$/,'')||'';const card=inferLinkedCard(term,pending.prompt);await captureError({category:'production',prompt:pending.prompt,learnerResponse:pending.learnerResponse,expectedResponse:`Dùng đúng ${term}`,correction:'',explanation:paragraph.textContent.replace(term,'').replace('✕','').trim(),linkedCardIds:card?[card.id]:[],sourceRef:{type:'exercise',sourceId:'core-output',title:'Vocab Master output practice'}});}return;}
  const card=inferLinkedCard(expected,pending.prompt);await captureError({category:pending.kind==='production'?'production':/CHÍNH TẢ/i.test(pending.label)?'spelling':/COLLOCATION/i.test(pending.label)?'collocation':'meaning',prompt:pending.prompt,learnerResponse:pending.learnerResponse,expectedResponse:expected,correction:expected,explanation:'Lỗi được ghi tự động từ bài học hiện có. Hãy mở Notebook để bổ sung giải thích nếu cần.',linkedCardIds:card?[card.id]:[],sourceRef:{type:'exercise',sourceId:'core-study',title:'Phiên học Vocab Master',context:pending.prompt}});
}
function extractQuotedTarget(prompt){return String(prompt||'').match(/[“"]([^”"]+)[”"]/)?.[1]||'';}
async function captureCoreProductionGap(){const pending=state.pendingCoreError;if(!pending||pending.kind!=='production')return;const target=extractQuotedTarget(pending.prompt),card=inferLinkedCard(target,pending.prompt);const signature=`manual-production|${pending.prompt}|${pending.learnerResponse}|${target}`;if(state.processedErrorSignatures.has(signature))return;state.processedErrorSignatures.add(signature);state.pendingCoreError=null;await captureError({category:'lexical-gap',prompt:pending.prompt,learnerResponse:pending.learnerResponse,expectedResponse:`Dùng được ${target}`,correction:'',explanation:'Người học tự báo chưa dùng được target.',linkedCardIds:card?[card.id]:[],sourceRef:{type:'exercise',sourceId:'core-production',title:'Production practice'}});}

async function mount(){
  if(state.mounted)return;state.mounted=true;ensureStyles();ensureLauncher();ensureDialog();await initializeIeltsPersistence();await seedCuratedContent();installCoreErrorCapture();await renderTodayErrors();globalThis.addEventListener('vocab:ielts-external-change',()=>{void renderTodayErrors();if($('#ieltsLabDialog')?.open)void renderLab();});globalThis.addEventListener('vocab:card-added',()=>{if($('#ieltsLabDialog')?.open)void renderLab();});
}

export async function mountIeltsLab(){return mount();}
export const __testing=Object.freeze({state,inferLinkedCard,collectSegmentsFromEditor});
