import { listContentLessons,refreshContentCatalog,downloadContentLesson,openContentLesson } from './content-platform.js';
import { resolveTranscriptFast,continueTranscriptProgressively,listCachedTranscripts,parseYouTubeVideoId } from './transcript-resolver-v2.js';
import { createYoutubeSentencePlayer } from './youtube-sentence-player.js';
import { IELTS_STORE_NAMES } from './ielts-domain.js';
import { listIeltsRecords } from './ielts-persistence.js';

const escape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
let activeTab='discover';
let videoBusy=false;
let bypassLegacyLauncher=false;
const boundLaunchers=new WeakSet();

function dialog(){return document.querySelector('#v10IeltsHubDialog');}
function panel(){return document.querySelector('#v10IeltsHubPanel');}
function toast(message){const node=document.querySelector('#toast');if(!node)return;node.textContent=message;node.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.remove('show'),3500);}
function openLegacyTab(tab){const launcher=document.querySelector('#openIeltsLabButton,#openIeltsLabMobile');if(!launcher)return;bypassLegacyLauncher=true;try{launcher.click();}finally{bypassLegacyLauncher=false;}setTimeout(()=>document.querySelector(`[data-ielts-tab="${tab}"]`)?.click(),60);}
async function openVideoLoop(row){const player=createYoutubeSentencePlayer(row.videoId,row.segments?.[0]);await globalThis.VocabMasterSentenceLoop?.open?.({sourceId:`youtube:${row.videoId}`,sourceType:'video',title:row.title||'YouTube video',sentences:row.segments||[],player});}

function shell(content){return`<div class="v10-ielts-shell"><header class="v10-ielts-header"><div><p class="eyebrow">VOCAB MASTER · IELTS LEARNING SYSTEM</p><h2>IELTS</h2><p>Kho từ trung tâm · nội dung theo nhu cầu · học theo câu · lỗi được theo dõi dài hạn</p></div><button class="ielts-icon-button" data-v10-ielts-close aria-label="Đóng IELTS">×</button></header><nav class="v10-ielts-tabs" role="tablist">${[['discover','Khám phá bài học'],['videos','Video của tôi'],['skills','Lỗi & kỹ năng']].map(([id,label])=>`<button role="tab" data-v10-ielts-tab="${id}" aria-selected="${activeTab===id}">${label}</button>`).join('')}</nav><main class="v10-ielts-panel">${content}</main></div>`;}

async function discoverMarkup(){let lessons=await listContentLessons();if(!lessons.length){try{await refreshContentCatalog();lessons=await listContentLessons();}catch(error){console.warn('[content catalog]',error);}}
  const levels=[...new Set(lessons.map(row=>row.level))],topics=[...new Set(lessons.map(row=>row.topic))];return`<section class="v10-hub-hero"><div><p class="eyebrow">REMOTE CONTENT CATALOG</p><h3>Bài chất lượng sẵn sàng, không làm phồng bundle</h3><p>Lesson chỉ tải khi mở hoặc khi bạn ghim offline. Từ mục tiêu không tự động đổ vào Kho từ.</p></div><button class="secondary-button" data-v10-refresh-catalog>Làm mới catalog</button></section><div class="v10-content-filters"><select id="v10ContentLevel"><option value="">Mọi CEFR</option>${levels.map(value=>`<option>${escape(value)}</option>`).join('')}</select><select id="v10ContentTopic"><option value="">Mọi chủ đề</option>${topics.map(value=>`<option>${escape(value)}</option>`).join('')}</select><select id="v10ContentSkill"><option value="">Mọi kỹ năng</option><option value="dictation">Dictation</option><option value="shadowing">Shadowing</option><option value="reading">Reading</option><option value="paraphrase">Paraphrase</option></select></div><div id="v10ContentCards" class="v10-content-grid">${contentCardsMarkup(lessons)}</div>`;}
function contentCardsMarkup(lessons){return lessons.length?lessons.map(row=>`<article class="v10-content-card" data-content-level="${escape(row.level)}" data-content-topic="${escape(row.topic)}" data-content-skills="${escape((row.skills||[]).join(','))}"><div><span>${escape(row.level)} · độ khó ${row.listeningDifficulty}/10</span><h3>${escape(row.title)}</h3><p>${escape(row.description||row.topic)}</p><small>${escape(row.accent)} · ${escape(row.topic)} · ${row.sentenceCount} câu</small></div><div class="v10-content-actions"><button class="primary-button" data-v10-open-content="${escape(row.id)}">Học ngay</button><button class="secondary-button" data-v10-download-content="${escape(row.id)}">Tải offline</button></div></article>`).join(''):'<div class="ielts-empty"><strong>Catalog chưa có bài</strong><p>Kiểm tra kết nối hoặc thêm Starter Pack vào public/content.</p></div>';}

async function videosMarkup(){const [cached,media]=await Promise.all([listCachedTranscripts(),listIeltsRecords(IELTS_STORE_NAMES.mediaSources,{sortBy:'updatedAt'}).catch(()=>[])]);const byVideo=new Map();for(const row of [...cached,...media]){const key=row.videoId||row.id;if(!byVideo.has(key))byVideo.set(key,row);}const rows=[...byVideo.values()];return`<section class="v10-hub-hero"><div><p class="eyebrow">PASTE URL → LEARN</p><h3>Dán YouTube URL và học câu đầu càng sớm càng tốt</h3><p>Cache/caption/local companion chạy trước; Gemini chỉ xử lý từng chunk khi không có transcript nhanh.</p></div></section><form id="v10VideoForm" class="v10-video-form"><input name="url" type="url" required placeholder="https://www.youtube.com/watch?v=..."><label>Bắt đầu (phút)<input name="startMinutes" type="number" min="0" value="0"></label><button class="primary-button" ${videoBusy?'disabled':''}>${videoBusy?'Đang chuẩn bị…':'Dán URL và học'}</button></form><div id="v10VideoStatus" class="v10-video-status" aria-live="polite"></div><details class="v10-video-fallback"><summary>Tùy chọn cứu hộ</summary><p>Import SRT/VTT hoặc dán transcript chỉ xuất hiện khi mọi provider thất bại; không phải luồng học mặc định.</p><button class="secondary-button" data-v10-legacy-tab="media">Mở Transcript Editor nâng cao</button></details><section><div class="section-heading"><div><p class="eyebrow">VIDEO ĐÃ HỌC</p><h3>Tiếp tục đúng câu đang dở</h3></div></div><div class="v10-video-grid">${rows.map(row=>`<button data-v10-cached-video="${escape(row.videoId||'')}" data-v10-cached-id="${escape(row.id||'')}"><strong>${escape(row.title||row.videoId||'Video')}</strong><span>${row.segments?.length||0} câu đã cache</span><small>${escape(row.provider||row.transcriptStatus||'media')}</small></button>`).join('')||'<p class="muted">Chưa có video.</p>'}</div></section>`;}

async function skillsMarkup(){const [errors,sets,readings,labs]=await Promise.all([listIeltsRecords(IELTS_STORE_NAMES.errors,{sortBy:'lastSeenAt'}).catch(()=>[]),listIeltsRecords(IELTS_STORE_NAMES.lexicalSets).catch(()=>[]),listIeltsRecords(IELTS_STORE_NAMES.readingPassages).catch(()=>[]),listIeltsRecords(IELTS_STORE_NAMES.labItems).catch(()=>[])]);const openErrors=errors.filter(row=>!['resolved','ignored'].includes(row.status));const categories=new Map();for(const row of openErrors)categories.set(row.category,(categories.get(row.category)||0)+Number(row.occurrenceCount||1));return`<section class="v10-hub-hero"><div><p class="eyebrow">ERROR-DRIVEN LEARNING</p><h3>Lỗi không biến mất sau khi đóng bài</h3><p>Error Notebook liên kết về Kho từ, câu nguồn và FSRS evidence đúng kỹ năng.</p></div><strong>${openErrors.length} lỗi mở</strong></section><div class="v10-skill-metrics"><button data-v10-legacy-tab="errors"><strong>${openErrors.length}</strong><span>Error Notebook</span></button><button data-v10-legacy-tab="lexical"><strong>${sets.filter(row=>row.status==='active').length}</strong><span>Lexical Sets</span></button><button data-v10-legacy-tab="reading"><strong>${readings.filter(row=>row.status==='verified').length}</strong><span>Reading đã duyệt</span></button><button data-v10-legacy-tab="paraphrase"><strong>${labs.filter(row=>row.status==='verified').length}</strong><span>Paraphrase đã duyệt</span></button></div><section class="v10-error-map"><h3>Mẫu lỗi nổi bật</h3>${[...categories.entries()].sort((a,b)=>b[1]-a[1]).slice(0,8).map(([category,count])=>`<div><strong>${escape(category)}</strong><span>${count} lần</span></div>`).join('')||'<p class="muted">Chưa đủ lỗi để tạo bản đồ.</p>'}</section><div class="v10-hub-tools"><button class="primary-button" data-v10-legacy-tab="errors">Mở Error Notebook</button><button class="secondary-button" data-v10-legacy-tab="lexical">Mở Lexical Sets</button></div>`;}

async function render(){const host=panel();if(!host)return;host.innerHTML=shell('<div class="v10-loading">Đang chuẩn bị…</div>');let content;try{content=activeTab==='videos'?await videosMarkup():activeTab==='skills'?await skillsMarkup():await discoverMarkup();}catch(error){content=`<div class="ielts-empty"><strong>Không tải được IELTS Hub</strong><p>${escape(error.message)}</p></div>`;}host.innerHTML=shell(content);}

function filterContent(){const level=document.querySelector('#v10ContentLevel')?.value||'',topic=document.querySelector('#v10ContentTopic')?.value||'',skill=document.querySelector('#v10ContentSkill')?.value||'';document.querySelectorAll('.v10-content-card').forEach(card=>{const visible=(!level||card.dataset.contentLevel===level)&&(!topic||card.dataset.contentTopic===topic)&&(!skill||String(card.dataset.contentSkills).split(',').includes(skill));card.hidden=!visible;});}
async function handleVideoSubmit(form){if(videoBusy)return;const data=new FormData(form),url=String(data.get('url')||''),videoId=parseYouTubeVideoId(url);if(!videoId){toast('URL YouTube không hợp lệ.');return;}videoBusy=true;await render();const status=document.querySelector('#v10VideoStatus');if(status)status.innerHTML='<p>✓ Đã tải player metadata</p><p>● Đang tìm transcript nhanh…</p>';try{const startSeconds=Math.max(0,Number(data.get('startMinutes')||0)*60);const row=await resolveTranscriptFast({url,startSeconds,firstChunkSeconds:60});const currentStatus=document.querySelector('#v10VideoStatus');if(currentStatus)currentStatus.innerHTML=`<p>✓ Có ${row.segments.length} câu đầu từ ${escape(row.provider)}</p><p>● Các phần tiếp theo có thể tiếp tục xử lý trong nền</p>`;await openVideoLoop(row);void continueTranscriptProgressively({url,startSeconds:startSeconds+60,totalSeconds:180,chunkSeconds:60}).catch(error=>console.warn('[progressive transcript]',error));}catch(error){const currentStatus=document.querySelector('#v10VideoStatus');if(currentStatus)currentStatus.innerHTML=`<p class="error">${escape(error.message)}</p><p>Mở tùy chọn cứu hộ nếu video không có caption và AI không xử lý được.</p>`;}finally{videoBusy=false;}}

async function handleClick(event){
  if(event.target.closest('[data-v10-ielts-close]')){dialog()?.close();return;}
  const tab=event.target.closest('[data-v10-ielts-tab]');if(tab){activeTab=tab.dataset.v10IeltsTab;await render();return;}
  const legacy=event.target.closest('[data-v10-legacy-tab]');if(legacy){dialog()?.close();openLegacyTab(legacy.dataset.v10LegacyTab);return;}
  if(event.target.closest('[data-v10-refresh-catalog]')){try{await refreshContentCatalog();await render();toast('Đã làm mới content catalog.');}catch(error){toast(error.message);}return;}
  const open=event.target.closest('[data-v10-open-content]');if(open){try{await openContentLesson(open.dataset.v10OpenContent);}catch(error){toast(error.message);}return;}
  const download=event.target.closest('[data-v10-download-content]');if(download){download.disabled=true;try{await downloadContentLesson(download.dataset.v10DownloadContent,{pin:true});download.textContent='Đã tải offline';toast('Đã ghim bài để học offline.');}catch(error){toast(error.message);download.disabled=false;}return;}
  const cached=event.target.closest('[data-v10-cached-video]');if(cached){const rows=await listCachedTranscripts(cached.dataset.v10CachedVideo);const row=rows.find(item=>item.id===cached.dataset.v10CachedId)||rows[0];if(row)await openVideoLoop(row);}
}

function ensureDialog(){if(dialog())return;const node=document.createElement('dialog');node.id='v10IeltsHubDialog';node.className='v10-ielts-dialog';node.innerHTML='<div id="v10IeltsHubPanel"></div>';node.addEventListener('click',event=>void handleClick(event));node.addEventListener('change',event=>{if(event.target.matches('#v10ContentLevel,#v10ContentTopic,#v10ContentSkill'))filterContent();});node.addEventListener('submit',event=>{if(event.target.id==='v10VideoForm'){event.preventDefault();void handleVideoSubmit(event.target);}});document.body.append(node);}
export async function openIeltsHub(tab='discover'){activeTab=['discover','videos','skills'].includes(tab)?tab:'discover';ensureDialog();if(!dialog().open)dialog().showModal();await render();}

function launcherHandler(event){if(bypassLegacyLauncher)return;event.preventDefault();event.stopImmediatePropagation();void openIeltsHub('discover');}
function bindLegacyLaunchers(){for(const launcher of document.querySelectorAll('#openIeltsLabButton,#openIeltsLabMobile')){if(boundLaunchers.has(launcher))continue;boundLaunchers.add(launcher);launcher.addEventListener('click',launcherHandler,true);}}
function interceptLegacyLauncher(){bindLegacyLaunchers();document.addEventListener('vocab:ielts-launcher-mounted',bindLegacyLaunchers);}
export function mountIeltsHubV2(){ensureDialog();interceptLegacyLauncher();globalThis.addEventListener('vocab:v10-open-ielts-hub',event=>void openIeltsHub(event.detail?.tab||'discover'));globalThis.VocabMasterIeltsHub={open:openIeltsHub,refresh:render,openLegacyTab};}
