import { listReviewEvents, persistMetrics } from './persistence.js';
import { plannedSkillsForCard } from './fsrs-scheduler.js';
import { summarizeCalibration } from './progress.js';

function addStyle(){if(document.querySelector('#roadmapV9Style'))return;const style=document.createElement('style');style.id='roadmapV9Style';style.textContent=`button:focus-visible,a:focus-visible,input:focus-visible,textarea:focus-visible,select:focus-visible,[tabindex]:focus-visible{outline:3px solid currentColor;outline-offset:3px}.quick-capture-panel{margin:0 0 24px;padding:22px;border:1px solid var(--border,#e8e1dc);border-radius:20px;background:var(--surface,#fff)}.quick-capture-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start}.quick-capture-head h2{margin:.4rem 0}.quick-capture-form{display:grid;grid-template-columns:1fr 2fr 1fr auto;gap:12px;align-items:end}.quick-capture-form label{display:grid;gap:6px}.quality-inbox{display:grid;gap:10px;margin-top:16px}.draft-row{display:flex;justify-content:space-between;gap:16px;padding:14px;border:1px solid var(--border,#e8e1dc);border-radius:14px}.draft-row div:first-child{display:grid;gap:4px}.draft-row span{font-size:.8rem;font-weight:700}.draft-row p{margin:0}.draft-actions{display:flex;gap:8px;align-items:center}.learning-integrity-card{margin-top:20px;padding:18px;border:1px solid var(--border,#e8e1dc);border-radius:18px;background:var(--surface,#fff)}@media(max-width:800px){.quick-capture-form{grid-template-columns:1fr}.quick-capture-head,.draft-row{flex-direction:column}.draft-actions{flex-wrap:wrap}}`;document.head.append(style);}
function enhanceTabs(){document.querySelectorAll('[role=tablist]').forEach(list=>{const buttons=[...list.querySelectorAll('button')];buttons.forEach((button,index)=>{button.setAttribute('role','tab');button.setAttribute('aria-selected',String(button.classList.contains('active')));button.tabIndex=button.classList.contains('active')?0:-1;button.addEventListener('click',()=>buttons.forEach(item=>{item.setAttribute('aria-selected',String(item===button));item.tabIndex=item===button?0:-1;}));button.addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();let next=event.key==='Home'?0:event.key==='End'?buttons.length-1:(index+(event.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length;buttons[next]?.focus();buttons[next]?.click();});});});}
function discloseAi(){const key=document.querySelector('#geminiKey');if(!key||document.querySelector('#aiTransitDisclosure'))return;const note=document.createElement('small');note.id='aiTransitDisclosure';note.className='form-note';note.textContent='Khóa và nội dung yêu cầu được gửi qua máy chủ Vocab Master để gọi Gemini. Khóa chỉ được lưu trong phiên trình duyệt, nhưng vẫn truyền qua server trong mỗi yêu cầu.';key.closest('label,div')?.append(note);}
function renameMetrics(){document.querySelectorAll('.prog-stat-card.accuracy small,.accuracy small').forEach(node=>node.textContent='Truy hồi thành công');document.querySelectorAll('[title*="Tỷ lệ"]').forEach(node=>node.title=node.title.replace(/Tỷ lệ[^:]*:/,'Tỷ lệ truy hồi độc lập:'));}
function intervention(cards=[]){const counts={meaning:0,spelling:0,listening:0,collocation:0,production:0};for(const card of cards)for(const[key,value]of Object.entries(card.errorCounts||{}))if(key in counts)counts[key]+=Number(value||0);const best=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0];if(!best||!best[1])return'Chưa đủ dữ liệu lỗi; tiếp tục phiên Today để hệ thống hiệu chuẩn.';return({meaning:'Bạn hay nhầm nghĩa: ưu tiên bài đối chiếu nghĩa và tách sense.',spelling:'Bạn hay sai chính tả: ưu tiên dictation ngắn.',listening:'Bạn chưa nhận ra khi nghe: luyện nghe rồi chép lại.',collocation:'Bạn hay sai cấu trúc cụm: luân phiên phần bị khuyết.',production:'Bạn khó dùng chủ động: giảm từ mới và viết câu có phản hồi.'})[best[0]];}
async function renderIntegrity(){const progress=document.querySelector('[data-view="progress"]');if(!progress)return;let card=document.querySelector('#learningIntegrityCard');if(!card){card=document.createElement('section');card.id='learningIntegrityCard';card.className='learning-integrity-card';progress.append(card);}const events=await listReviewEvents();const state=globalThis.VocabMasterApp?.getState?.()||{cards:[]};const calibration=summarizeCalibration(events);const planned=state.cards.filter(item=>!item.suspendedAt&&!item.archivedAt).reduce((sum,item)=>sum+plannedSkillsForCard(item).length,0);card.innerHTML=`<h3>Độ tin cậy học tập</h3><p><strong>Hiệu chuẩn:</strong> ${calibration.label} · dự báo ${calibration.predicted}% / thực tế ${calibration.observed}% trên ${calibration.sampleSize} lượt.</p><p><strong>Phạm vi mục tiêu:</strong> ${planned} lịch kỹ năng được lên kế hoạch; kỹ năng nâng cao chỉ mở sau evidence nền.</p><p><strong>Hành động đề xuất:</strong> ${intervention(state.cards)}</p>`;}
async function reconcileDailyMetrics(){const state=globalThis.VocabMasterApp?.getState?.();if(!state?.metrics)return;const events=await listReviewEvents();const today=new Date();today.setHours(0,0,0,0);const eligible=events.filter(event=>Number(event.reviewedAt||0)>=today.getTime()&&!event.assisted&&['independent_review','self_assessed_production','ai_verified_production'].includes(event.evidenceType||event.metadata?.evidenceType));const metrics={...state.metrics,dailyDone:eligible.length,independentReviewsDone:eligible.length};if(Number(metrics.independentReviewsDone)!==Number(state.metrics.independentReviewsDone||0)){await persistMetrics(metrics);globalThis.dispatchEvent(new CustomEvent('vocab:metrics-reconciled',{detail:metrics}));}}
export async function mountRoadmapRuntime(){addStyle();enhanceTabs();discloseAi();renameMetrics();await renderIntegrity();await reconcileDailyMetrics();const overlay=document.querySelector('#studyOverlay');if(overlay)new MutationObserver(()=>{if(!overlay.classList.contains('open')){void reconcileDailyMetrics();void renderIntegrity();}}).observe(overlay,{attributes:true,attributeFilter:['class']});globalThis.addEventListener('hashchange',()=>{renameMetrics();void renderIntegrity();});}
